"""Translate Google R1 drill docs to Chinese -- Batch 1 (docs 55/56/60/61).

Per T-P1-475 [KG-G-01]. Idempotent: if the sentinel
`<!-- CN_TRANSLATED_20260416 -->` already appears in the target doc content,
the seeder prints [UNCHANGED] for that doc and skips.

Translation rules (project memory feedback_lc_notes_chinese):
- Chinese prose throughout
- Keep English: algorithm names (RankNet / LambdaRank / NDCG@K), complexity
  notation (O(n^2)), paper citations (Burges 2005), variable names (s_i, y_i)
- Glossary terms: first-use bold English with Chinese in parentheses, e.g.
  **Position Bias (位置偏差)**
- Math via $...$ inline and $$...$$ display (unchanged)
- Tables kept in English where content is technical terminology (per task note);
  prose rows translated
"""
from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent.parent / "data" / "mle_prep.db"
SENTINEL = "<!-- CN_TRANSLATED_20260416 -->"


# -------------------------------------------------------------------------
# Doc 55 -- Regularization Deep Dive
# Already Chinese-prose throughout. Only the header comment updated.
# -------------------------------------------------------------------------
DOC_55 = """<!-- KG_P2_02_REGULARIZATION_20260416 -->
""" + SENTINEL + """

# Regularization Deep Dive -- Google R1 Prep (Drill)

> **正典** [Regularization (pillar2.regularization.regularization_canonical_hub)](/framework/195)

本 drill 服务 Google R1 面试的**口述练习**：L1 / L2 几何推导、KKT、soft-thresholding、Bayesian prior、AdamW 等核心内容已固化到 canonical hub。此处只保留 **drill-specific** 的战术要点——dropout、early stopping、data augmentation、以及 7 法全景表与 30 秒口述自测。

## Prerequisites

- Canonical hub: [Regularization](/framework/195)（务必先过一遍）
- 神经网络训练循环（forward / backward pass）
- 随机采样与蒙特卡洛的基本直觉

## 1. Dropout -- Bayesian Approximation & Ensemble View

训练阶段：每次前向把每个单元以概率 $p$ 置零。推理阶段：启用全部单元，activation 乘以 $(1-p)$；或训练时用 **inverted dropout** 直接除以 $(1-p)$，推理不变。

**集成视角（Srivastava 2014）**：$n$ 个单元 -> $2^n$ 个 thinned networks。平均预测近似等于一个指数级 ensemble 的平均。

**Bayesian 视角（Gal & Ghahramani 2016）**：推理时**保持 dropout 开启**，做 $T$ 次 forward，得到预测均值与不确定性。MC Dropout 的方差估计：

$$\\mathrm{Var}[y^*] \\approx \\frac{1}{T}\\sum_{t=1}^{T} f_{\\theta_t}(x^*)^2 - \\left(\\frac{1}{T}\\sum_{t=1}^{T} f_{\\theta_t}(x^*)\\right)^2$$

**口述捷径**："Dropout 是 $2^n$ 子网络的廉价集成；推理时不关它还能免费拿到不确定性。"

## 2. Early Stopping -- Implicit L2

从 $w=0$ 起，小学习率的 GD 在权重空间画一条轨迹；**停得早就等于限制 $\\|w\\|$ 的增长**。$T$ 步 x 学习率 $\\eta$ x 梯度上界 $G_{\\max}$：

$$\\|w_T\\| \\le \\eta \\cdot T \\cdot G_{\\max}$$

Bishop (1995) / Sjoberg & Ljung (1995) 证明：在二次损失下，early stopping 的第 $T$ 步等价于 L2 正则 $\\lambda_{\\text{eff}} \\propto 1/(\\eta T)$。

**口述捷径**："Early stopping = 隐式 L2；步数少 = 范数小 = 正则强。免费但把优化和正则耦合在一起。"

## 3. Data Augmentation -- Vicinal Risk Minimization

ERM 最小化的是**训练点上的平均损失**；数据增广把每个点替换为一个**邻域（vicinity）**。形式化（Chapelle 等 2000）：

$$R_{\\text{VRM}} = \\frac{1}{n}\\sum_{i=1}^{n} \\mathbb{E}_{x' \\sim \\nu(x_i)}[\\ell(f(x'), y_i)]$$

vicinity 分布 $\\nu$ 编码领域先验：图像用 flip / crop，NLP 用 synonym replacement，Mixup 用插值。**正则化效果**：模型必须在邻域内都对，决策边界被平滑，variance 下降而 bias 不变（只要 augmentation 保标签）。

**口述捷径**："Augmentation 就是在邻域上训练，不是在点上。数学上是 VRM——vicinity kernel 取代 ERM 里的 Dirac delta。"

## 4. AdamW in One Breath（canonical 已详述，此处仅口述）

> **正典** [Regularization §7 AdamW](/framework/195)

"Adam 的 $v_t$ 把 L2 梯度按历史自适应地缩小，所以正则强度不均匀；AdamW 把 decay 挪到 Adam 步之外，所有参数均匀 $(1-\\eta\\lambda)$。transformer 用 AdamW。"

## 5. 7-Method Regularization Panorama

| Method | What It Constrains | Oral 10-Second Pitch |
| --- | --- | --- |
| L1 | 激活的特征数 | 菱形顶点在坐标轴 => 稀疏 |
| L2 / Ridge | 权重整体幅度 | 圆面光滑；闭式 $(X'X+\\lambda I)^{-1} X'y$ |
| Elastic Net | 相关特征组 | L2 绑定整组，L1 删除整组 |
| Dropout | 隐层共适应 | $2^n$ 子网集成；MC 拿不确定性 |
| Early Stopping | 原点出发的轨迹长度 | 隐式 L2；$\\lambda \\sim 1/(\\eta T)$；最便宜 |
| AdamW | 各参数统一幅度 | decoupled decay；Adam+L2 非 AdamW |
| Data Aug / VRM | 决策边界光滑度 | 在邻域上训练而非点上 |

## 6. 30-Second Oral Self-Check

- [ ] L1 稀疏的三层解释（几何 / 代数 / Bayesian）--- 指向 canonical §1/§5
- [ ] L2 闭式解 $(X^\\top X+\\lambda I)^{-1}X^\\top y$ 与逐奇异值收缩 --- canonical §3
- [ ] Ridge vs Lasso 的 bias 谁更大？两者都 biased，L1 还额外把系数压到 0
- [ ] Dropout = $2^n$ ensemble + MC Dropout uncertainty
- [ ] Early stopping 是隐式 L2，$\\lambda\\propto 1/(\\eta T)$
- [ ] AdamW 的一句话解释（$v_t$ 吞 L2；decay 解耦）
- [ ] Data aug = VRM，vicinity kernel 取代 Dirac delta
- [ ] James-Stein：$p\\ge 3$ 时收缩估计严格优于 OLS

**面试口吻收尾**："L1 / L2 的推导我画图+写 KKT+ Bayesian 三条线都能走；dropout 我用 ensemble 和 MC 两种解释；AdamW 我能说清 $v_t$ 吞 L2 这个技术细节。"
"""


# -------------------------------------------------------------------------
# Doc 56 -- Bias-Variance + Overfitting Diagnosis Drill
# -------------------------------------------------------------------------
DOC_56 = """<!-- Generated by StudyNoteBuilder -->
<!-- doc_kind: drill -->
<!-- KG_P2_01_BIAS_VARIANCE_20260416 -->
""" + SENTINEL + """

# Bias-Variance + Overfitting Diagnosis Drill -- Google R1 Prep

> **正典** [Bias-Variance Tradeoff (pillar2.supervised_learning.bias_variance_tradeoff)](/framework/67)

口述战术速查。完整推导、正则理论和 double-descent 讨论都在 canonical hub。
本文件只保留 Google R1 drill 需要的面：诊断对照表、集成方差公式、学习曲线形状、以及口述捷径。

## 1. Diagnosis Label Cheat Sheet

复杂度-误差关系驱动所有诊断（推导见 canonical hub，这里只背一句结论）：

> 模型复杂度 up  =>  Bias down、Variance up。

**四象限诊断表**

| 症状 | 诊断 | 处置 |
| --- | --- | --- |
| 训练误差高、测试误差高 | Underfitting（high bias）| 更多特征、更复杂模型、减少正则 |
| 训练误差低、测试误差高 | Overfitting（high variance）| 更多数据、加正则、简化模型、dropout、early stopping |
| 训练误差低、测试误差低 | 拟合合适 | 可以上线 |
| 训练误差高、测试误差低 | 数据泄漏或评估 bug | 审计 pipeline，排查 target leakage |

**口述捷径**："Underfit 两端都高，bias 主导；overfit 是 train/test gap，variance 主导；leakage 是 test 比 train 还好，哪里一定出错了。"

## 2. Bagging Variance Formula + RF Insight

$B$ 个模型平均、两两相关系数为 $\\rho$ 时的方差：

$$\\text{Var}_{\\text{bag}} = \\rho\\,\\sigma_{\\text{tree}}^2 + \\frac{1-\\rho}{B}\\,\\sigma_{\\text{tree}}^2 \\;\\xrightarrow{B \\to \\infty}\\; \\rho\\,\\sigma_{\\text{tree}}^2$$

Bagging 的方差下限是 $\\rho\\sigma^2$。**Random Forest (随机森林)** 在每次分裂时随机选特征子集（分类常取 $m=\\sqrt{p}$、回归取 $m=p/3$）把 $\\rho$ 压低——$\\rho$ 越小、下限越低。

**口述捷径**："Bagging 方差下限 = rho 乘 sigma 方；RF 用随机特征把 rho 压低，下限就更低。"

## 3. RF Deep Trees vs GBDT Shallow Trees (Dual Aesthetics)

**RF (Random Forest)** 和 **GBDT (Gradient Boosted Decision Trees)** 从 bias-variance 权衡的两端进攻：

|  | Random Forest | GBDT |
| --- | --- | --- |
| Base learner | 深且不剪枝的树（低 bias、高 variance）| 浅树 / stump（高 bias、低 variance）|
| 集成策略 | 并行（bagging）- 降 variance | 顺序（boosting）- 降 bias |
| 过拟合风险 | 增加树的数量一般不会过拟合 | 轮数过多或树过深会过拟合 |
| 关键超参 | n_estimators、max_features | n_estimators、learning_rate、max_depth |
| Bias-variance 杠杆 | 随机特征子集降 rho（降 variance）| 每棵树拟合残差（降 bias）|

RF：$f(x) = \\frac{1}{B}\\sum_{b=1}^{B} T_b(x)$（深树平均）

GBDT：$f(x) = \\sum_{m=1}^{M} \\eta\\,h_m(x)$（浅树在残差上累加）

**口述捷径**："RF 是深树平均，主打降 variance；GBDT 是浅树串行堆，主打降 bias。入口相反，目的地相同。"

## 4. Learning Curve -- 四种诊断形状

把训练误差和验证误差画在同一张图上，横轴是训练集大小。曲线形状直接给出诊断：

| 形状 | Train | Val | 诊断 | 行动 |
| --- | --- | --- | --- | --- |
| 大 gap、两条都在下降 | 低 | 高但在降 | 高 variance（overfit）| 加数据可改善；或加正则 |
| 小 gap、两条都偏高 | 高 | 高，贴近 train | 高 bias（underfit）| 加数据**没用**，要加容量 |
| Gap 闭合、两条都低 | 低 | 低，收敛到 train | 拟合合适 | 已达最优复杂度；边际收益递减 |
| Train 接近 0、val 平直高 | 接近 0 | 高且水平 | 严重 overfit / 记忆化 | 加正则或简化模型，不是加数据 |

经验法则：

- Train-val gap 大 => variance 问题。加数据或加正则。
- 两条曲线都高位平台 => bias 问题。加特征或加容量。
- Train 误差 = 0 => 记忆化红灯。加正则。
- 曲线收敛到的水平可近似看作当前模型类下的 irreducible error。

**口述捷径**："Gap 大 = variance，加数据；两端都高 = bias，加容量；train=0、val 高 = 记忆化，加正则。"

## 5. 2-Minute Oral Self-Check

- [ ] 背 $E_D[(y - \\hat{f})^2] = \\text{Bias}^2 + \\text{Var} + \\sigma^2$
- [ ] 一句话说清三项各代表什么
- [ ] 复杂度 up => bias down、variance up（嘴上说一遍）
- [ ] Underfit 两端高；overfit 是 train/test 的 gap
- [ ] Bagging 方差 = $\\rho\\sigma^2 + (1-\\rho)\\sigma^2/B$，下限 $\\rho\\sigma^2$
- [ ] RF 用随机特征降 rho；GBDT 顺序地降 bias
- [ ] RF = 深树平均；GBDT = 浅树堆叠
- [ ] 学习曲线：大 gap = variance；都高 = bias；train=0 = 记忆化
"""


# -------------------------------------------------------------------------
# Doc 60 -- LambdaRank / LambdaMART Drill
# -------------------------------------------------------------------------
DOC_60 = """<!-- Generated by StudyNoteBuilder -->
""" + SENTINEL + """

# LambdaRank / LambdaMART Derivation Drill -- Google R1 Prep

## Prerequisites

- 有监督学习、cross-entropy 损失、sigmoid 梯度
- Gradient Boosted Decision Trees（MART / XGBoost / LightGBM）
- NDCG / DCG 定义（见 google_ndcg_map_mrr_drill.md 配套文档）

## Key Terms

- **LTR (Learning to Rank，学习排序)**：在 (query, doc) 对上训练一个打分函数的有监督问题
- **RankNet (成对 cross-entropy 排序损失，Burges 2005)**：把带标签对 $(i,j)$ 上的分数差 $s_i - s_j$ 送进 logistic loss
- **LambdaRank (NDCG 加权的伪梯度，Burges 2006)**：$\\lambda_{ij}$ = RankNet 梯度乘以交换这一对时的 $|\\Delta\\mathrm{NDCG}_{ij}|$
- **LambdaMART (把 LambdaRank 伪梯度塞进 MART / GBDT)**：业界标准 LTR，XGBoost `rank:ndcg` 与 LightGBM `LambdaRank` 就是这套
- **DCG (Discounted Cumulative Gain，折损累计增益)**：top-K 位置上 $(2^y - 1) / \\log_2(i+1)$ 求和
- **NDCG (Normalized DCG，归一化 DCG)**：DCG 除以 IDCG（理想排序），按 query 归一化
- **BCE (Binary Cross-Entropy，二元交叉熵)**：点击 / 下单预测用的逐点 logistic 损失
- **ListNet (Listwise softmax cross-entropy on top-1 分布)**：把 $\\mathrm{softmax}(s)$ 与 $\\mathrm{softmax}(y)$ 的分布差作为 query 级损失

## 1. **RankNet** -- 成对 Sigmoid 损失（必背）

场景：query $q$ 有若干候选文档；带标签对 $(i,j)$ 满足 $y_i > y_j$。模型给出标量分数 $s_i = f(x_i)$、$s_j = f(x_j)$。目标：把 $s_i$ 推到 $s_j$ 上面。

用分数差的 sigmoid 建模成对偏好：

$$P_{ij} \\;=\\; \\Pr(i \\succ j) \\;=\\; \\sigma\\!\\bigl(s_i - s_j\\bigr) \\;=\\; \\frac{1}{1 + e^{-(s_i - s_j)}}$$

交叉熵目标为 1（$i$ 应排在 $j$ 前面），所以损失是：

$$\\mathcal{L}_{ij} \\;=\\; -\\log P_{ij} \\;=\\; \\log\\!\\bigl(1 + e^{-(s_i - s_j)}\\bigr)$$

梯度（白板上一定写得出来）：

对称：$s_i$ 抬、$s_j$ 压，幅度相同。

$$\\frac{\\partial \\mathcal{L}_{ij}}{\\partial s_i} \\;=\\; -\\,(1 - P_{ij})\\qquad\\frac{\\partial \\mathcal{L}_{ij}}{\\partial s_j} \\;=\\; +\\,(1 - P_{ij})$$

**口述捷径**："RankNet = 对分数差的 logistic loss。梯度大小是 $1 - P_{ij}$：模型错得越离谱（$P_{ij}\\to 0$）梯度越大；模型对了就自动消失。"

**致命缺陷**：每对误排权重一样。交换位置 1 和位置 2 的代价等于交换位置 99 和 100，但顶部那对对用户伤害大得多。

## 2. **LambdaRank** -- $\\Delta\\mathrm{NDCG}$ 加权的成对梯度

诀窍：不对 NDCG 求导（argsort 是离散的），而是把 RankNet 每对的梯度乘以交换两个文档位置所造成的 $|\\Delta\\mathrm{NDCG}_{ij}|$。

Lambda 梯度 = RankNet 方向乘交换幅度：

$$\\lambda_{ij} \\;=\\; \\underbrace{-\\,(1 - P_{ij})}_{\\text{RankNet 梯度}}\\;\\cdot\\;\\underbrace{\\bigl|\\Delta\\mathrm{NDCG}_{ij}\\bigr|}_{\\text{交换幅度}}$$

交换后只有两个位置的 DCG 变化：

$$\\bigl|\\Delta\\mathrm{NDCG}_{ij}\\bigr| \\;=\\; \\frac{1}{\\mathrm{IDCG}}\\,\\bigl|\\,2^{y_i} - 2^{y_j}\\bigr|\\,\\left|\\,\\frac{1}{\\log_2(p_i + 1)} - \\frac{1}{\\log_2(p_j + 1)}\\right|$$

逐文档聚合——每个 doc 对它参与的所有对求和：

$doc\\ i$ 的伪梯度。$\\lambda_i$ 为负表示分数要推高。

$$\\lambda_i \\;=\\; \\sum_{j\\,:\\,y_i > y_j} \\lambda_{ij}\\;-\\; \\sum_{j\\,:\\,y_j > y_i} \\lambda_{ji}$$

**LambdaMART** = 把 $(\\lambda_i, w_i)$ 作为 (gradient, hessian) 塞给 MART。Hessian 近似 $w_{ij} = P_{ij}(1 - P_{ij}) \\cdot |\\Delta\\mathrm{NDCG}_{ij}|$。树分裂和叶子值的算法与普通 XGBoost 完全一样——只是梯度来源换成了 LambdaRank。

**为什么容量自动集中在 top**：位置 1 附近 $1/\\log_2(p+1)\\approx 1$，位置 100 附近只有 $\\approx 0.14$，所以同样的 label swap 在顶部产生 7 倍大的 $|\\Delta\\mathrm{NDCG}|$。**自调节收敛**：排序接近理想时 $(1 - P_{ij})$ 和 $|\\Delta\\mathrm{NDCG}_{ij}|$ 都在缩小，更新自然消失。

**口述捷径**："LambdaRank = RankNet 梯度乘以交换的 $|\\Delta\\mathrm{NDCG}|$。顶部误排的 $\\Delta\\mathrm{NDCG}$ 大、梯度占主导。LambdaMART 就是把这个伪梯度塞进 GBDT。"

## 3. Pointwise **BCE** vs Pairwise vs **ListNet**（什么场景用什么）

三种 **LTR** 范式差在"损失的单位"：

**LTR 范式对照表**

| 范式 | 损失公式 | 每 query 复杂度 | 使用场景 |
| --- | --- | --- | --- |
| Pointwise BCE | $L = \\sum_i [ -y_i \\log \\sigma(s_i) - (1 - y_i) \\log(1 - \\sigma(s_i)) ]$ | $O(n)$ | 二元参与标签（click / purchase）；需要可校准概率；MTL 里的 CTR、pOrder head |
| Pairwise (RankNet) | $L = \\sum_{i>j} \\log(1 + \\exp(-(s_i - s_j)))$ | $O(n^2)$ 对（可采样）| 有偏好对；只关心相对顺序、不关心绝对分数校准 |
| Listwise (ListNet) | $L = - \\sum_i \\mathrm{softmax}(y)_i \\cdot \\log \\mathrm{softmax}(s)_i$ | 每 query 一次 softmax，$O(n)$ | 整张列表；想让 top-1 分布对齐标签分布；listwise 的光滑替代 |
| Listwise (LambdaMART) | 伪梯度 $\\lambda_i = \\sum_j \\mathrm{RankNet} \\cdot |\\Delta\\mathrm{NDCG}|$ | $O(n^2)$ 对 / query | 有分级相关性；NDCG / MAP 是业务目标；GBDT 友好；生产默认 |


## 3. （续）

决策规则：

- 如果标签本身是标量概率（click / order），从 pointwise BCE 入手。便宜、可在 doc 上并行、给的分数可校准、可直接用来 bidding 和卡阈值。

- 如果只在乎排序（召回任务、候选再排），pairwise 是最小代价的升级，教模型相对偏好。

- 如果有分级相关性标签且 NDCG 是头条指标，就上 listwise——生产用 LambdaMART（GBDT 栈），神经网络栈用 ListNet 或 ApproxNDCG。这类损失天生就是位置感知的。

- 多任务排序场景（DoorDash / eBay feed、Etsy search）里，pointwise MTL head（pClick、pOrder、pGMV）通常线性融合成分数；纯 listwise 反而少见，因为下游 bidding 需要可校准 head。

**口述捷径**："Pointwise 用来当可校准的 head，pairwise 用来学相对顺序，listwise（LambdaMART）用在分级 NDCG 是目标的场景。ListNet 的 softmax 是神经 ranker 不用 GBDT 时的 listwise 光滑选项。"

## 4. Story Hook -- Sale NDCG to GMB Bidding (eBay Ranking-as-Allocation)

Google 面试官爱追问："为什么你选 NDCG？凭什么它就是对的目标？" 最好答案是 Sale-NDCG 反面教材，因为它说明你懂 NDCG 的失败模式，而不只是公式。

30 秒故事脚本：

- 团队优化的是 Sale NDCG = 用 purchase conversion 加权的 NDCG。标准选择，跑了几年都挺好。

- 发现系统性偏差：便宜 item 的 conversion 更高，所以 Sale NDCG 把 \\$5 的配件排到 \\$100 的项链前面。局部指标在涨，平台 GMB (Gross Merchandise Bought) 却平稳没动。

- 根因：Sale NDCG 的 gain = $2^y - 1$ 不含 item value。LambdaMART 在忠实地优化一个**错配**的代理目标。

- 修复：把排序重新表述成资源分配问题——分别预测 pClick、pOrder、预期每曝光收入（pointwise MTL、BCE / 回归 head），再按 GMB-bid 分数 $w_1 \\cdot \\text{pClick} + w_2 \\cdot \\text{pOrder} + w_3 \\cdot \\text{pOrder} \\cdot \\text{value} - w_4 \\cdot \\text{risk}$ 分槽位。这就是 Ranking-as-Allocation。

- 结果：首次 A/B +1% GMB，这个分配 primitive 还推广到了 Ads、Monetization、promo 模块。

**为什么这个故事在 Google ranking 岗上打得响**：

- 显示你理解 NDCG 是代理、不是业务目标。LambdaMART 把 NDCG 优化满格也照样可能伤 GMB。

- 展示对 pointwise MTL + score fusion 模式的熟练度——这种模式主宰了现代电商排序（DoorDash 第三节的 fusion score 结构上完全一样）。

- 给了通往 calibration 的桥：GMB bidding 一旦 pClick / pOrder 校准失灵就崩——自然接回 calibration drill（T-P0-417）。

**口述捷径**："NDCG 是代理。Sale NDCG 忽略 item value——便宜 item 在排名上压过贵 item。修复是 Ranking-as-Allocation：校准的 MTL head 融合成 GMB bid 分数。第一次实验就 +1% GMB。"

### 2-Minute Oral Self-Check

- [ ] 背 RankNet 损失：$\\log(1 + \\exp(-(s_i - s_j)))$
- [ ] 说出 RankNet 梯度 $\\partial L / \\partial s_i = -(1 - P_{ij})$
- [ ] 说出 RankNet 的致命缺陷（所有对权重一样）
- [ ] 背 $\\lambda_{ij} = -(1 - P_{ij}) \\cdot |\\Delta\\mathrm{NDCG}_{ij}|$
- [ ] 解释为什么 $|\\Delta\\mathrm{NDCG}|$ 把容量压到顶部（$1/\\log_2$ 折扣在顶部大）
- [ ] LambdaMART = $(\\lambda_i, w_i)$ 作为 (gradient, hessian) 喂给 GBDT
- [ ] Pointwise BCE -- 什么时候用（可校准的 click / order head、MTL）
- [ ] Pairwise RankNet -- 什么时候用（只要顺序、无分级标签）
- [ ] Listwise (ListNet / LambdaMART) -- 什么时候用（分级标签、NDCG 目标）
- [ ] Sale NDCG 故事：便宜 item 压过贵 item -> Ranking-as-Allocation -> +1% GMB
- [ ] 通往 calibration 的桥：GMB bidding 需要可校准的 pClick / pOrder

"""


# -------------------------------------------------------------------------
# Doc 61 -- NDCG / MAP / MRR + Position Bias Drill
# -------------------------------------------------------------------------
DOC_61 = """<!-- Generated by StudyNoteBuilder -->
""" + SENTINEL + """

# NDCG / MAP / MRR + Position Bias Drill -- Google R1 Prep

## Prerequisites

- 排序 + 排名列表基础，分级 vs 二元相关性标签
- 概率与期望（examination 假设用）
- LambdaMART / LTR 背景（见 google_lambdarank_drill.md 配套文档）

## Key Terms

- **DCG (Discounted Cumulative Gain，折损累计增益)**：对 top-K 排名文档按位置折损后的 gain 累加
- **NDCG (Normalized DCG，归一化折损累计增益)**：DCG 除以 IDCG，使不同 query 间可比
- **IDCG (Ideal DCG，理想 DCG)**：在最优排序下（按标签降序）的 DCG
- **MAP (Mean Average Precision，平均准确率均值)**：对所有 query 的 AP 求平均；AP 是在每个相关 hit 所在位置上的 precision 平均
- **AP (Average Precision，平均准确率)**：$\\sum_k \\mathrm{Precision}@k \\cdot \\mathbb{1}[\\text{第 }k\\text{ 位相关}]$ 除以相关文档数
- **MRR (Mean Reciprocal Rank，倒数排名均值)**：第一个相关 doc 的 $1/\\mathrm{rank}$ 平均；适合单正确答案任务
- **IPW (Inverse Propensity Weighting，逆倾向加权)**：每次点击乘 $1 / \\Pr(\\mathrm{examine} \\mid \\text{位置})$，在训练 / 评估中去除位置偏差
- **ULTR (Unbiased Learning to Rank，无偏学习排序)**：把点击因式分解为 $\\text{examine}(\\text{pos}) \\times \\text{relevance}(q, d)$，上线时只保留 relevance 塔

## 1. **DCG** 和 **NDCG** -- 必背

场景：query $q$ 下，把 $K$ 个文档排序；位置 $p_i \\in 1..K$ 上的文档 $i$ 有分级标签 $y_i \\in \\{0, 1, 2, 3, 4\\}$（0=无关，4=完美）。用对数折损来匹配用户注意力的经验下降。

分子 = gain，分母 = 位置折损：

$$\\mathrm{DCG}@K \\;=\\; \\sum_{i=1}^{K}\\;\\frac{2^{y_i} - 1}{\\log_2(i + 1)}$$

**IDCG** = 理想排序（标签降序）下的 DCG：

$$\\mathrm{IDCG}@K \\;=\\; \\sum_{i=1}^{K}\\;\\frac{2^{y^{\\star}_{i}} - 1}{\\log_2(i + 1)}$$

对每个 query 归一化，使不同 query 的 NDCG 可比：

$$\\mathrm{NDCG}@K \\;=\\; \\frac{\\mathrm{DCG}@K}{\\mathrm{IDCG}@K}\\;\\in\\;[0,\\,1]$$

**为什么用 $2^y - 1$（指数而非线性）gain**：指数放大完美文档（$y=4$）的价值到 $y=1$ 的 15 倍（$2^4 - 1 = 15$、$2^1 - 1 = 1$），顶部的 label 相等就不会主导分数；同时让 LambdaRank 里的交换差代数干净——只有交换的两个位置的项发生变化。

**为什么用 $\\log_2(i + 1)$ 折损（对数而非线性）**：对数折损是 web click 经验拟合——CTR 大致按 $1/\\log(\\mathrm{rank})$ 下降。位置 1 折损 $1/\\log_2(2) = 1.0$，位置 10 是 $1/\\log_2(11) \\approx 0.289$，位置 100 约 $0.150$。

**口述捷径**："DCG = $\\sum (2^y - 1) / \\log_2(i + 1)$。NDCG = DCG / IDCG，所以在 $[0,1]$ 内、跨 query 可比。指数 gain 奖励顶部高相关文档，对数折损匹配用户注意力衰减。"

## 2. **MAP** (Mean Average Precision) -- 二元标签世界

MAP 假设二元相关性 $y_i \\in \\{0, 1\\}$。query 有 $R$ 个相关文档，沿着排名列表下行，每遇到一个相关文档就记一次当前 Precision@k：

每 query 的 Average Precision：

$$\\mathrm{AP} \\;=\\; \\frac{1}{R}\\,\\sum_{k=1}^{N}\\mathrm{Precision}@k \\,\\cdot\\, \\mathbb{1}[y_{(k)} = 1]$$

排名 $k$ 上的滑动 precision：

$$\\mathrm{Precision}@k \\;=\\; \\frac{|\\{i\\,:\\,i\\le k,\\; y_{(i)} = 1\\}|}{k}$$

MAP = 所有 query 的 **AP** 平均：

$$\\mathrm{MAP} \\;=\\; \\frac{1}{|Q|}\\,\\sum_{q\\in Q}\\;\\mathrm{AP}(q)$$

**为什么 MAP 对分级标签是错的（Google 面试陷阱）**：

- MAP 把标签二值化。任意 $y > 0$ 都变成 hit——$y=1$ 和 $y=4$ 不分。把完美结果和勉强相关的互换，MAP 零变化。

- MAP 的位置折损只是隐式（后面的 hit 分母变大），但并不按 label grade 加权。两个排名中相关位置相同、但分级顺序不同，MAP 分数完全一致。

- MAP 没有对数折损——用的是 Precision@k 的 $1/\\mathrm{rank}$。这形状更贴近 MRR、而不是 NDCG，不匹配观测到的用户注意力曲线。

经验规则：MAP 用在二元评判（TREC 旧基准）；NDCG 用在分级标签（现代搜索 / 排序）；MRR 用在单正确答案 QA / 导航查询。

**口述捷径**："MAP 只吃二元标签；分辨不了完美文档和勉强相关文档。分级标签就用 NDCG，因为 $2^y - 1$ gain 让分级差异真正起作用。"

## 3. MRR 和指标速查

**MRR** 假设 query 只有一个正确答案（导航搜索、单答案 QA）。Reciprocal Rank = 那一个正确文档的 $1/\\mathrm{rank}$；MRR 对 query 取平均：

$\\mathrm{rank}_q^{\\star}$ = query $q$ 中唯一正确文档的排名：

$$\\mathrm{MRR} \\;=\\; \\frac{1}{|Q|}\\,\\sum_{q\\in Q}\\;\\frac{1}{\\mathrm{rank}_q^{\\star}}$$

MRR 忽略第一次 hit 之后的一切；它奖励"早点拿到一个对的"，不在乎整体列表形状。问"搜 Albert Einstein 有没有给我 Wikipedia"——很合适。问"给我前 10 家附近餐厅"——很不合适。

**排序指标速查表**

| 指标 | 标签类型 | 位置折损 | 适合场景 | 失效场景 |
| --- | --- | --- | --- | --- |
| NDCG@K | 分级（0..4）| $\\log_2(i + 1)$ | 分级相关性排序（web search、商品、feed）| 只有二元标签；或顶部 tie 主导分数 |
| MAP | 二元（0/1）| 通过 Precision@k 隐式 | 二元评判，全列表 precision 评估 | 分级相关性（分不清 $y=1$ 和 $y=4$）|
| MRR | 二元（单正确）| 第一次 hit 的 $1/\\mathrm{rank}$ | 导航搜索、单答案 QA、known-item | 多答案列表（完全忽略第 2..K 位）|
| Precision@K | 二元（0/1）| 无（硬截断）| 固定截断下的 top-K 质量 | 需要位置敏感；需要分级区分 |


## 4. Numerical Example -- MAP vs NDCG 分歧

同一 query 下两个排名列表，各 5 个 doc。分级标签 $y \\in \\{0, 1, 2, 3\\}$。MAP 按阈值 $y > 0$ 二值化。

**List A**（按排名顺序的分级标签）：$[3, 2, 1, 0, 0]$

**List B**（按排名顺序的分级标签）：$[1, 1, 3, 0, 0]$

两张表的相关文档数都是 $R = 3$，$K = 5$。IDCG 使用理想排序 $[3, 2, 1, 0, 0]$，所以 IDCG 对两者一样。

IDCG 计算：

IDCG = $7 + 3/\\log_2(3) + 1/\\log_2(4)$：

$$\\mathrm{IDCG} \\;=\\; \\frac{2^{3}-1}{\\log_2 2} + \\frac{2^{2}-1}{\\log_2 3} + \\frac{2^{1}-1}{\\log_2 4} \\;=\\; 7 + 1.893 + 0.500 \\;\\approx\\; 9.393$$

List A 的 DCG（本来就是理想）：

List A 就是理想排序：

$$\\mathrm{DCG}_A \\;=\\; \\frac{7}{1.000} + \\frac{3}{1.585} + \\frac{1}{2.000} \\;\\approx\\; 9.393 \\;\\Rightarrow\\; \\mathrm{NDCG}_A = 1.000$$

List B 的 DCG（最佳文档埋在第 3 位）：

$y=3$ 的 doc 在位置 3，折损损失大：

$$\\mathrm{DCG}_B \\;=\\; \\frac{1}{1.000} + \\frac{1}{1.585} + \\frac{7}{2.000} \\;\\approx\\; 1 + 0.631 + 3.500 \\;=\\; 5.131$$

NDCG 惩罚很重——比 List A 低 45 个点：

$$\\mathrm{NDCG}_B \\;=\\; \\frac{5.131}{9.393} \\;\\approx\\; 0.546$$

同样两个列表上的 MAP（二值化：$y > 0$ -> 相关）：

List A 二值化 $= [1, 1, 1, 0, 0]$；AP 每个位置都加分：

$$\\mathrm{AP}_A \\;=\\; \\tfrac{1}{3}\\bigl(\\tfrac{1}{1} + \\tfrac{2}{2} + \\tfrac{3}{3}\\bigr) \\;=\\; 1.000$$

List B 二值化 $= [1, 1, 1, 0, 0]$——模式一样、AP 一样：

$$\\mathrm{AP}_B \\;=\\; \\tfrac{1}{3}\\bigl(\\tfrac{1}{1} + \\tfrac{2}{2} + \\tfrac{3}{3}\\bigr) \\;=\\; 1.000$$

结论：NDCG 分数 $1.000$ vs $0.546$（A 胜出明显），MAP 分数 $1.000$ vs $1.000$（打平）。同样的 doc、同样的二值化位置，NDCG 抓到了完美 doc 被埋没、MAP 对分级视而不见。这就是为什么 Google / 分级标签排序团队不看 MAP。

**口述捷径**："拿 $[3,2,1,0,0]$ vs $[1,1,3,0,0]$ 的玩具例子。MAP 把两者打平在 1.0，因为二值化后位置一致；NDCG 分开成 1.0 vs 0.55，因为指数 gain 惩罚被埋的 $y=3$。"

## 5. Position Bias 污染 Offline NDCG

陷阱：标签来自点击日志而不是人工评判时，高位置 doc 仅因为被先看到就拿到更多点击。在这些点击标签上算的 offline NDCG 其实是在奖励 ranker 复现当前 UI，而不是真正的相关性。

**Examination 假设（Craswell et al. 2008 Cascade / PBM）**：一次点击需要两个独立事件同时发生——用户必须看到位置 $k$ **并且**认为 doc 相关。

Position bias = examine 因子；relevance 是要学的目标：

$$\\Pr(\\mathrm{click} \\mid q, d, k) \\;=\\; \\underbrace{\\Pr(\\mathrm{examine} \\mid k)}_{\\text{位置相关}}\\;\\cdot\\;\\underbrace{\\Pr(\\mathrm{relevant} \\mid q, d)}_{\\text{想要的}}$$

**为什么会污染 offline NDCG**：

- 训练标签 = 原始点击。模型学到的是 $P(\\mathrm{click} \\mid q, d, k)$，把位置先验焊进去了——高位仅因"被展示在高位"就得到正标签。

- 在同一批日志上算的 offline NDCG 对"与线上排序一致的 ranker"友好。对照模型和线上模型的 NDCG delta 被人为压小（位置一致性堆高了分数）。

- 新 item / 长尾 doc 从没出现在高位，点击标签全是 0——不是因为不相关、是因为根本没被 examine 过。NDCG 把它们当无关，但其实根本没测到。

**Fix #1 -- Inverse Propensity Weighting (IPW)**：估计 $\\Pr(\\mathrm{examine} \\mid k)$，训练 / 评估时对每个样本乘以 $1 / \\Pr(\\mathrm{examine} \\mid k)$，在期望上消除位置偏差：

压低顶部权重、抬高底部权重：

$$\\mathcal{L}_{\\mathrm{IPW}} \\;=\\; \\sum_{(q, d, k)}\\;\\frac{1}{\\Pr(\\mathrm{examine} \\mid k)}\\;\\cdot\\;\\ell\\bigl(y_{q,d},\\;\\hat{y}_{q,d}\\bigr)$$

- $\\Pr(\\mathrm{examine} \\mid k)$ 可以用 result-swap 随机化（生产里少见）或点击回归的 EM 估计。examine 概率低处方差极大——标准做法是把 $1/\\Pr(\\mathrm{examine})$ 夹在 10 或 20 这种上限内。

**Fix #2 -- Unbiased LTR / PAL（Position-Aware Learning）**：把点击模型拆成 relevance 塔和 position 塔，联合训练、上线只保留 relevance 塔：

Two-tower 点击模型；推理丢掉 position 塔：

$$\\Pr(\\mathrm{click} \\mid q, d, k) \\;=\\; \\sigma\\bigl(f_{\\mathrm{rel}}(q, d)\\bigr)\\;\\cdot\\;\\sigma\\bigl(f_{\\mathrm{pos}}(k)\\bigr)$$

- DoorDash / Google / Etsy 生产中的选择：PAL 带一个学到的 position feature，推理时置零。比 IPW 便宜（不用估 propensity），方差有界。

**即便用了修复，仍要有 guardrail**：offline NDCG 永远要配一个偏差更小的第二指标——或是对抽样 slate 做人工评判 NDCG、或是在均匀随机服务流上做 counterfactual IPS 估计——才敢上线。

**口述捷径**："点击标签上的 offline NDCG 被 examine 因子污染。修复是 IPW（按 $1 / \\Pr(\\mathrm{examine} \\mid k)$ 加权）或 ULTR（two-tower click = relevance $\\times$ position，只上 relevance）。上线前必须用人工评判或 counterfactual NDCG 做第二把关。"

### 2-Minute Oral Self-Check

- [ ] 背 $\\mathrm{DCG}@K = \\sum (2^{y_i} - 1) / \\log_2(i + 1)$
- [ ] 背 $\\mathrm{NDCG}@K = \\mathrm{DCG} / \\mathrm{IDCG}$，取值范围 $[0, 1]$
- [ ] 解释 $2^y - 1$（指数 gain）和 $\\log_2(i+1)$（注意力衰减）
- [ ] 说出 MAP 公式：$\\mathrm{AP} = (1/R) \\sum \\mathrm{Precision}@k \\cdot \\mathbb{1}[y_k \\text{ 相关}]$
- [ ] 说出 MAP 在分级标签上失败的原因（二值化把 $y=1$ 和 $y=4$ 合并了）
- [ ] 过一遍 $[3,2,1,0,0]$ vs $[1,1,3,0,0]$ 玩具例：NDCG 1.0 vs 0.55，MAP 1.0 vs 1.0
- [ ] 背 $\\mathrm{click} = \\Pr(\\mathrm{examine} \\mid k) \\cdot \\Pr(\\mathrm{relevant} \\mid q, d)$（examination 假设）
- [ ] 解释为什么点击日志上的 offline NDCG 对现线上 ranker 偏友好
- [ ] IPW 修复：$1 / \\Pr(\\mathrm{examine} \\mid k)$ 加权；高方差、做 clipping
- [ ] ULTR / PAL 修复：two-tower click = relevance $\\times$ position，上线只保留 relevance
- [ ] Guardrail：offline NDCG 配人工评判 slate 或 counterfactual IPS

"""


DOCS: dict[int, tuple[str, str]] = {
    55: ("Regularization Deep Dive (Google R1 Prep)", DOC_55),
    56: ("Bias-Variance + Overfitting Diagnosis Drill (Google R1 Prep)", DOC_56),
    60: ("LambdaRank / LambdaMART Drill (Google R1 Prep)", DOC_60),
    61: ("NDCG / MAP / MRR + Position Bias Drill (Google R1 Prep)", DOC_61),
}


def cjk_ratio(text: str) -> float:
    """Return CJK / (CJK + Latin letters) ratio for the given text."""
    cjk = sum(1 for c in text if "\u4e00" <= c <= "\u9fff")
    latin = sum(1 for c in text if c.isalpha() and ord(c) < 128)
    total = cjk + latin
    return cjk / total if total else 0.0


def main() -> int:
    conn = sqlite3.connect(str(DB_PATH))
    try:
        updated = 0
        unchanged = 0
        for did, (expected_title, new_content) in DOCS.items():
            row = conn.execute(
                "SELECT title, content FROM company_documents WHERE id = ?",
                (did,),
            ).fetchone()
            if row is None:
                print(f"[ERROR] doc {did} not found")
                continue
            cur_title, cur_content = row
            if SENTINEL in cur_content:
                print(f"[UNCHANGED] doc {did} ({cur_title}) -- sentinel present")
                unchanged += 1
                continue
            cur = conn.execute(
                "UPDATE company_documents SET content = ? WHERE id = ?",
                (new_content, did),
            )
            conn.commit()
            ratio = cjk_ratio(new_content)
            print(
                f"[UPDATE] doc {did} rows={cur.rowcount} new_len={len(new_content)} "
                f"cjk_ratio={ratio:.1%}"
            )
            updated += 1
        print(f"Summary: updated={updated}, unchanged={unchanged}")
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
