"""Translate Google R1 drill docs to Chinese -- Batch 2 (docs 62/63/64/67).

Per T-P1-475 [KG-G-01]. Idempotent: if the sentinel
`<!-- CN_TRANSLATED_20260416 -->` already appears in the target doc content,
the seeder prints [UNCHANGED] for that doc and skips.

Translation rules (project memory feedback_lc_notes_chinese):
- Chinese prose throughout
- Keep English: algorithm names (Platt / Isotonic / Temperature / IPS / SNIPS /
  HNSW / IVF-PQ / CUPED / SRM), complexity notation (O(n^2)),
  paper citations (Burges 2005 / Guo 2017 / Swaminathan-Joachims 2015),
  variable names (s_i, p_k, y_i), metric names (NDCG@k, recall@K)
- Glossary terms: first-use bold English with Chinese in parentheses, e.g.
  **Position Bias (位置偏差)**
- Math via $...$ inline and $$...$$ display (unchanged)
- Tables: header rows kept in English; prose cells translated to Chinese
"""
from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent.parent / "data" / "mle_prep.db"
SENTINEL = "<!-- CN_TRANSLATED_20260416 -->"


# -------------------------------------------------------------------------
# Doc 62 -- Calibration Drill: Platt / Isotonic / Temperature + GMB Bidding
# -------------------------------------------------------------------------
DOC_62 = """<!-- Generated by StudyNoteBuilder -->
""" + SENTINEL + """

# Calibration Drill -- Platt / Isotonic / Temperature + GMB Bidding Trap

## Prerequisites

- 二分类 / 多分类基础（logits 与 softmax）
- Logistic Regression，MLE / cross-entropy 损失
- 二价拍卖基础（bid = value * P，期望收益模型）

## Key Terms

- **ECE (Expected Calibration Error，期望校准误差)**：分桶后模型置信度与经验准确率之间差值的加权平均
- **Platt (Platt Scaling，Platt 缩放)**：在原始 logit 上拟合的两参数 logistic；把单调分数转成概率
- **Isotonic (Isotonic Regression，保序回归)**：通过 PAV 算法学出的分段常数、单调映射，非参数方法
- **Temperature (Temperature Scaling，温度缩放)**：对所有 logit 除以一个正标量 $T$ 再过 softmax；保留 argmax
- **NLL (Negative Log-Likelihood，负对数似然)**：交叉熵损失；温度缩放的拟合目标
- **GMB (Google Marketing Bidding，谷歌营销出价)**：二价广告出价场景，bid = value * 校准后 P(action)；miscalibration 会系统性高估或低估出价

## 0. Why Calibration Matters (The Framing)

分类器可能 **判别能力强**（高 AUC、排序正确）但 **校准得很糟**：模型吐出的那个数字根本不是概率。任何基于期望值的决策——出价、分诊、带成本的路由——关心的是 $P$ 的**幅值**，不是排序。

定义：在所有模型说 $p=0.3$ 的样本中，恰好 30% 是正例。

$$\\text{Perfect calibration: } \\Pr(Y=1 \\mid \\hat{p}(x)=p) = p \\quad \\forall p \\in [0,1]$$

现代神经网络以**过度自信**著称。Guo et al. 2017 展示 ResNet 在 CIFAR-100 上的置信度集中在 1.0 附近，而准确率却只有 0.75 左右——**ECE** 从 LeNet 的约 2% 爆到 ResNet-110 的约 15%。

**口述捷径**："AUC 衡量的是排序，校准衡量的是这个概率值能不能当概率用。出价、分诊等任何期望值决策依赖的是后者而不是前者。"

## 1. **Platt** Scaling = Logit 上的 Logistic

Platt (1999) 在模型原始分数 $z$（或 logit）之上拟合一个两参数 logistic。两个标量 $A, B$ 在 held-out 校准集上用 MLE 估计：

Platt 映射：把原始 logit 送进一个学出来的 sigmoid：

$$\\hat{p}(x) = \\sigma(A \\cdot z(x) + B), \\qquad \\sigma(u) = \\frac{1}{1 + e^{-u}}$$

参数在校准集上最小化 **NLL**：

$$(A^*, B^*) = \\arg\\min_{A,B} -\\sum_i \\bigl[y_i \\log \\sigma(A z_i + B) + (1-y_i) \\log(1 - \\sigma(A z_i + B))\\bigr]$$

**适用场景**：分数本身已近似为 log-odds 的线性函数——SVM margin、线性模型、浅层神经网。Platt 只有两个自由度，修不了根本上非单调的扭曲。

**踩坑点**：在训练集上拟合 Platt 会泄漏——必须用 held-out 校准集（10-20%）或交叉验证 fold-out。Platt smoothing 用伪标签 $y' = (N_+ + 1) / (N_+ + 2)$ 来防止边界附近的过自信。

**口述捷径**："Platt = logit 上的两参数 logistic。分数近似为 log-odds 时好用。必须在 held-out 上拟合，不能在 train 上。"

## 2. **Isotonic** Regression -- 保序但颗粒粗

保序回归拟合一个非参数的单调不减阶梯函数 $m: [0,1] \\to [0,1]$，把原始分数映射到校准概率，在单调约束下最小化加权平方误差：

目标：带单调约束的加权平方误差：

$$\\min_{m} \\sum_i \\bigl(y_i - m(z_i)\\bigr)^2 \\quad \\text{s.t.} \\quad z_i \\le z_j \\Rightarrow m(z_i) \\le m(z_j)$$

用 **Pool-Adjacent-Violators (PAV)** 算法求解，排序后 $O(n)$。输出是分段常数的阶梯函数。

因为 $m$ 单调，**预测的顺序被保留**——所以 AUC、NDCG 以及任何排序指标都不变，只有概率幅值被搬动。

**颗粒度权衡**：PAV 每当相邻两桶违反单调就合并它们，输出较粗——你得到的概率值数量有限（取决于数据）。比 Platt 灵活（不要求线性），但需要更多校准数据（约 1000+ 样本）以防过拟合。

**何时优于 Platt**：分数形状不是 sigmoid，或校准数据充足。**何时 Platt 优**：校准集小，或扭曲接近 sigmoid。

**口述捷径**："Isotonic = PAV 拟合的单调阶梯函数。保序所以 AUC 不变，但输出颗粒粗、需要的数据比 Platt 多。"

## 3. **Temperature** Scaling -- 只调 $T$，argmax 不变

对多类 logit $z \\in \\mathbb{R}^K$，温度缩放在 softmax 之前除以一个正标量 $T$：

温度缩放的 softmax：logit 除以 $T$ 再照常 softmax：

$$\\hat{p}_k(x) = \\frac{\\exp(z_k(x)/T)}{\\sum_{j=1}^{K} \\exp(z_j(x)/T)}$$

在 held-out 验证集上最小化 NLL 拟合 $T$：

这是一个一维凸优化问题（scipy.optimize 一维最小化即可）：

$$T^* = \\arg\\min_{T > 0} -\\sum_i \\log \\hat{p}_{y_i}(x_i; T)$$

**关键性质**：softmax 对所有 logit 的单调缩放保持不变，所以 argmax 不变：

argmax 不依赖 $T$；准确率、top-k 指标**一字不差**地保留：

$$\\arg\\max_k \\hat{p}_k(x; T) = \\arg\\max_k z_k(x) \\quad \\forall T > 0$$

**解释**：$T > 1$ 软化置信度（分布变平），$T < 1$ 锐化（分布变尖）。过自信的模型要的是 $T > 1$。

**为什么在深网里是主力**：只一个参数、不会过拟合校准集、可逆、且下游 argmax 决策不受任何影响。Guo et al. 2017 把 ResNet 在 CIFAR-100 的 ECE 从 15% 降到约 1%。

**局限**：$T$ 是全局标量。修不了按类不同的 miscalibration 和非单调扭曲——那些场景要用 vector scaling 或 Dirichlet calibration。

**口述捷径**："Temperature scaling = logit 除以一个标量 $T$，在 val NLL 上拟合。只改置信度形状，永远不翻转预测，深网过自信的默认修法。"

## 4. Three Methods at a Glance

按校准集大小、扭曲形状先验、是否需要 argmax 不变来选：

**Platt vs Isotonic vs Temperature**

|  | Platt | Isotonic | Temperature |
| --- | --- | --- | --- |
| Parameters | 2 (A, B) | O(unique z) | 1 (T) |
| 保序? | 是（单调 sigmoid） | 是（单调阶梯） | 是（argmax 不变） |
| 输出颗粒度 | 平滑 | 粗（阶梯函数） | 平滑 |
| 最少校准样本 | ~100 | ~1000 | ~50 |
| 最适合 | 小数据、sigmoid 形扭曲 | 数据多、形状未知 | 深网、全局过自信 |
| 典型使用 | SVM、浅层模型 | GBDT、任意模型 | CNN、transformer |
| 风险 | 欠拟合非 sigmoid 形状 | 小数据集上过拟合 | 修不了按类偏差 |


## 5. Reliability Diagram + ECE

**审计校准**：把预测概率分到 $M$ 个等宽桶 $B_1, \\ldots, B_M$（一般 $M=10$ 或 $15$）。每桶计算平均置信度和经验准确率：

每桶的平均置信度与经验准确率：

$$\\text{conf}(B_m) = \\frac{1}{|B_m|} \\sum_{i \\in B_m} \\hat{p}_i, \\quad \\text{acc}(B_m) = \\frac{1}{|B_m|} \\sum_{i \\in B_m} \\mathbb{1}[\\hat{y}_i = y_i]$$

画 $\\text{acc}(B_m)$ vs $\\text{conf}(B_m)$。完美校准就是 $y=x$ 对角线。点在对角线上方 = 欠自信，下方 = 过自信。

ECE 把整张图摘成一个数——按桶加权的 $L_1$ gap：

$$\\text{ECE} = \\sum_{m=1}^{M} \\frac{|B_m|}{N} \\bigl|\\text{acc}(B_m) - \\text{conf}(B_m)\\bigr|$$

**生产目标**：ECE < 2% 在 held-out 上一般对出价和排序下游是安全的；ECE > 5% 是红灯。**永远不要只看 ECE**，一定配着 reliability diagram 看——ECE 可能把相互抵消的误差（一桶过自信、另一桶欠自信）藏起来。

**兄弟指标**：MCE (Maximum Calibration Error，最坏桶) 用于尾风险审计；Brier score = 概率上的均方误差，可分解为 calibration + refinement + irreducible noise。

**口述捷径**："Reliability diagram = 按桶的 confidence vs accuracy，对照 $y=x$。ECE = 按桶加权的 $L_1$ gap。生产目标 ECE < 2%，且永远跟图一起看。"

## 6. **GMB** Bidding Calibration Trap (The Business Why)

在二价 Vickrey 拍卖、期望值出价模型下，点击-转化广告的最优诚实出价是：

bid 等于广告主价值乘以校准后的转化概率：

$$\\text{bid}^* = v \\cdot \\Pr(\\text{conversion} \\mid \\text{click}, x)$$

具体 CPA (cost-per-acquisition) 目标：bid = target_CPA * pCVR，$pCVR$ 是模型预测的转化率。**只有 pCVR 校准时**，期望 CPA 才等于目标。

**陷阱**：如果模型处处被全局倍数 $k$ 拉偏（$pCVR = k \\cdot \\text{true\\_CVR}$），AUC 完美无缺，但**每一个 bid 都偏了 $k$ 倍**。过预测（$k > 1$）在输掉的拍卖上烧钱；欠预测（$k < 1$）错过本能赢的拍卖。候选广告的**排序**可能完全一样，但花费结构系统性地错了。

校准系数 $k$ 直接写进实际 CPA：

$$\\text{If } \\hat{p} = k \\cdot p, \\text{ then } \\mathbb{E}[\\text{CPA}] = \\frac{\\text{target\\_CPA}}{k}$$

**为什么 offline AUC 抓不到**：AUC 只依赖 pairwise 排序。分数的任何单调变换都不改变 AUC，却会搬动概率幅值、改变 bid 水平。这就是广告系统即使 AUC 正常也要在**服务时**重新校准的原因。

**二阶陷阱**：miscalibration 常与特征漂移（周末 / 假期流量）和拍卖密度变化纠缠在一起，所以校准必须用**滑动窗口**监控（每日 ECE + reliability plot），而不是只在模型上线时测一次。

**生产模式**：训练一个判别性模型（XGBoost / DNN）冲 AUC，然后在最近滑动窗口上拟合 isotonic 或 Platt，每日刷新。Temperature scaling 在 DNN 模型里流行，isotonic 在 GBDT 模型里流行。

**口述捷径**："GMB 出价里 bid = value * P(action)。AUC 看排序，校准看幅值。偏 $k$ 倍 => CPA 偏 $1/k$ 倍。服务时按滑动窗口校准，每日监控 ECE。"

## 7. Numerical Sanity Check (k = 1.5 Over-Confidence)

假设目标 CPA = 10 USD，某切片上真实 CVR = 0.04。校准后最优 bid = 10 * 0.04 = 0.40 USD，该切片实际 CPA = 10 USD。

miscalibration 的模型预测 pCVR = 0.06（$k = 1.5$）。Bid = 10 * 0.06 = 0.60 USD。每次转化的实际成本 = bid / true_CVR = 0.60 / 0.04 = 15 USD。**每次获客超支 50%**，而 AUC 因为排序不变所以毫无异常。

欠校准（$k = 0.5$）会 bid 0.20 USD，输掉大部分拍卖、campaign 被饿死，AUC 依然一致。

**要点**：一个只能在 reliability diagram 上看到的全局 $k$，就能把 CPA 打偏 50%，而所有 offline 排序指标全绿。

### 2-Minute Oral Self-Check

- [ ] 校准定义：$\\Pr(Y=1 \\mid \\hat{p}=p) = p, \\forall p$
- [ ] Platt = $\\sigma(A \\cdot z + B)$，2 个参数，在 held-out 上用 NLL 拟合
- [ ] Isotonic = PAV，单调阶梯、保序、颗粒粗、需约 1000+ 样本
- [ ] Temperature = softmax(z / T)，一个标量、argmax 不变、NLL 拟合
- [ ] Reliability diagram：按桶 confidence vs accuracy 对 $y=x$ 对角线
- [ ] ECE = $\\sum |B_m|/N \\cdot |\\text{acc} - \\text{conf}|$；生产目标 < 2%
- [ ] AUC 只看排序；校准管幅值；出价里两者都要
- [ ] 二价 bid = value * P(action)；miscalibration $k$ => CPA 偏 $1/k$
- [ ] 服务时按滑动窗口校准；每日监控 ECE
- [ ] Platt 配小数据 + sigmoid 形；Isotonic 配大数据 + 形状未知；Temperature 配深网
"""


# -------------------------------------------------------------------------
# Doc 63 -- IPS / Counterfactual Eval / Debiased NDCG
# -------------------------------------------------------------------------
DOC_63 = """<!-- Generated by StudyNoteBuilder -->
""" + SENTINEL + """

# IPS / Counterfactual Eval / Debiased NDCG Drill -- SIGIR Paper Talking Points

## Prerequisites

- Learning to rank：NDCG / DCG / 相关性等级
- Logged bandit / off-policy evaluation 基础
- 点击模型（PBM / cascade）的高层认识
- 重要性采样 / Horvitz-Thompson 估计量

## Key Terms

- **IPS (Inverse Propensity Scoring，逆倾向加权)**：每条日志观测按 $1/P(\\text{shown})$ 加权，以无偏估计反事实策略
- **PBM (Position-Based Model，位置点击模型)**：点击可分解为 examination 和 relevance，$P(\\text{click}|q,d,k) = P(\\text{exam}|k) \\cdot P(\\text{rel}|q,d)$
- **SNIPS (Self-Normalized IPS，自归一 IPS)**：把 IPS 加权和除以权重之和；有偏但方差远低于 vanilla IPS
- **CEM (Counterfactual Evaluation Metric，反事实评估指标)**：仅用 $\\pi_0$ 的日志回答"部署 $\\pi$ 时 X 指标会是多少"的任何估计量
- **NDCG (Normalized Discounted Cumulative Gain，归一化折损累计增益)**：按位置折损的相关性和除以理想排序的值；LTR 标准指标
- **DCG (Discounted Cumulative Gain，折损累计增益)**：未归一化的相关性和，位置上带对数折损

## 0. Why Counterfactual Eval (The Framing)

在生产排序里，用户**只点击被展示过的结果**。直接在点击上训练学出的是**复现 logging 策略**，不是真实相关性。A/B 测试是金标准，但慢、贵、对差候选不安全。反事实评估问：**"只用 $\\pi_0$ 的日志，如果上线 $\\pi$ 的话 NDCG 会是多少？"**——而不跑真实 A/B。

Off-policy value：用策略比（Horvitz-Thompson）重新加权日志奖励：

$$V(\\pi) = \\mathbb{E}_{(q,\\mathbf{d}) \\sim \\pi_0}\\Bigl[\\tfrac{\\pi(\\mathbf{d}\\mid q)}{\\pi_0(\\mathbf{d}\\mid q)} \\cdot r(q,\\mathbf{d})\\Bigr]$$

天真地拿点击估 NDCG 会被两种偏差毒掉：(i) **Position Bias (位置偏差)**——顶部结果被看到的次数远高于底部，所以点击**高估**它们的相关性；(ii) **Selection Bias (选择偏差)**——$\\pi_0$ 根本没展示过大多数 $(q,d)$，点击只在有偏的子集上可观测。

**口述捷径**："天真点击把相关性和'$\\pi_0$ 选择展示什么、以什么位置展示'搅在一起。**IPS** 用 $1/P(\\text{shown})$ 把策略拿出来；examination model 用 click = exam * rel 把位置拿出来。"

## 1. IPS Reweighting by 1/P(shown)

**IPS** 就是在日志交互上套 Horvitz-Thompson。对日志里每个 $(q,d)$ 对，把观察到的奖励（点击或等级相关性）除以 $\\pi_0$ 在该位置展示该文档的概率：

IPS 估计量：新策略是否展示 $d_i$ 的指示函数，除以展示概率 $p_i$：

$$\\hat{V}_{\\text{IPS}}(\\pi) = \\frac{1}{N} \\sum_{i=1}^{N} \\frac{\\mathbb{1}[d_i \\in \\pi(q_i)]}{p_i} \\cdot c_i$$

这里 $c_i$ 是观察到的点击（或相关性判断），$p_i = P(d_i$ 在 $\\pi_0$ 下被展示在位置 $k_i)$。**倾向估对时无偏**——$\\mathbb{E}[\\text{IPS}] = V(\\pi)$。该性质要求 **full support (完全重叠)**：$\\pi$ 可能选的每个动作在 $\\pi_0$ 下倾向必须非零。如果 $\\pi_0$ 从不把 $d$ 放在位置 1，那再多加权也告诉不了你 $\\pi$ 把它放在位置 1 会怎样。

**排序场景的实际形式**：不用整个列表的联合倾向，**PBM** 分解让我们可以用**每位置的倾向** $p_k$——估计起来容易得多。

每位置 IPS：在 click = exam_k * rel 的假设下，只进位置倾向：

$$\\hat{\\Delta}(\\pi) = \\sum_{q,d} \\frac{c_{q,d}}{p_{k_0(q,d)}} \\cdot \\mathrm{rel\\text{-}gain}_\\pi(q,d)$$

**踩坑点**：极小 $p_i$（接近零）——一次点击除以 $10^{-4}$ 就会压倒整个求和。方差爆炸的速度比偏差收缩快。**标准缓解：propensity clipping**——$p_i \\leftarrow \\max(p_i, \\tau)$，$\\tau \\sim 0.01 \\sim 0.05$；用小偏差换大方差下降。

**口述捷径**："IPS = 按 $1/P(\\text{shown})$ 加权。重叠条件下无偏，但小倾向处方差爆炸。Clip 到 $\\tau$ 把方差拉回来。"

## 2. Examination Hypothesis -- Click = Exam * Relevance

**Examination Hypothesis (观察假设，Richardson 2007, Chapelle-Zhang 2009)** 说：用户**看到且结果相关时才点击**。经典 **PBM** 形式假设观察只依赖位置，不依赖内容：

**PBM**：点击可因式分解为 examination（只依位置）和 relevance（只依 query-doc）：

$$\\Pr(C = 1 \\mid q, d, k) = \\underbrace{\\Pr(E = 1 \\mid k)}_{\\text{position bias}} \\cdot \\underbrace{\\Pr(R = 1 \\mid q, d)}_{\\text{relevance}}$$

这是让去偏 LTR 可解的**根本假设**。两个直接结果：(i) $p_k = P(\\text{exam} \\mid$ 位置 $k)$ 充当倾向，只依位置；(ii) 用另一个位置的 examination 概率乘以相关性，就能恢复反事实点击率。

与 **cascade (Craswell 2008)** 对照：用户从上到下看，**在首次点击处停下**——位置 $k$ 的 examination 依赖前置结果，打破了"只依位置"的分解。PBM 在细节上是错的（examination 和 snippet、freshness、SERP 布局都有交互），但**在实际生产中够用**，去偏 LTR 基本就跑在它上面。

**口述捷径**："Examination hypothesis: click = P(exam at position) * P(rel | q,d)。PBM 下位置是唯一混淆——这一个假设是每位置 IPS 成立的基石。"

## 3. Propensity Estimation -- Where Does P(shown) Come From?

IPS 估计量的好坏完全取决于倾向估计。生产里四种标准的位置-观察倾向 $p_k$ 估法：

**(a) Result randomization (RandPair, Joachims 2017)**：对一小片流量，把位置 1 的文档和位置 $k$ 的文档**对调**。因为相关性跨对调保持不变，点击率的比值直接估计 examination 比 $p_k / p_1$。**最便宜的 ground truth**；代价是一小段 UX 损失。

RandPair 估计量：对调后的 CTR 比值给出相对 examination：

$$\\frac{p_k}{p_1} = \\frac{\\mathrm{CTR}(d \\text{ swapped to position } k)}{\\mathrm{CTR}(d \\text{ at position } 1)}$$

**(b) Intervention harvesting (Agarwal 2019)**：如果 logging 策略本来就在同一 $(q,d)$ 上跨 impression 变化位置（re-ranking、刷新、个性化翻转），**直接收割这些天然干预**，不再注入新的对调。UX 零成本，但需要日志策略足够多样。

**(c) EM on PBM (Wang 2018, Regression-EM)**：联合估计相关性 $R(q,d)$ 和 examination $p_k$，交替：E 步算 $P(\\text{exam} \\mid \\text{click}, q, d, k)$，M 步更新位置表和相关性模型。便宜、在 PBM 不成立时有偏、对标题党 / snippet 效应脆弱。

**(d) Inverse propensity model (CTR 拟合)**：在"无偏策略的顶部 $p_1 \\approx 1$"假设下，从日志拟合一个参数化或非参数 $p_k$ 曲线。最简单，常作没有更好选项时的默认 baseline。

**经验曲线**：桌面 web SERP 上 $p_k$ 一般在 $k=3$ 降到 $0.3 \\sim 0.5$，在 $k=10$ 以后低于 $0.1$；移动端更陡。**一定报告倾向估计的 error bar 和所用的 $\\tau$**——两者都是审稿人会盯的一阶旋钮。

**口述捷径**："倾向：能承担就 randomization；日志多样就 intervention harvesting；不能随机就 EM；都没有就参数化 $p_k$ 拟合做 baseline。"

## 4. **SNIPS** -- Self-Normalized IPS (Bias/Variance Tradeoff)

Vanilla IPS 无偏但高方差。**SNIPS (Swaminathan-Joachims 2015)** 用**权重之和**代替 $N$ 作分母，用小偏差换大方差下降：

SNIPS 估计量：IPS 比率、用重要性权重之和归一化：

$$\\hat{V}_{\\text{SNIPS}}(\\pi) = \\frac{\\sum_{i=1}^{N} w_i \\, c_i}{\\sum_{i=1}^{N} w_i}, \\quad w_i = \\frac{\\mathbb{1}[d_i \\in \\pi(q_i)]}{p_i}$$

**为什么有用**：如果某条日志的 $p_i$ 离谱地小，分子 ($w_i \\cdot c_i$) 和分母 ($w_i$) 会**一起爆**，比率稳住。SNIPS 不再无偏（偏差 $O(1/N)$），但真实世界倾向分布都有重尾，MSE 几乎总低于 vanilla IPS。

一句话的偏差-方差权衡：

MSE 分解：SNIPS 增加 $O(1/N)$ 的 bias² 但砍掉稀有小倾向贡献的方差：

$$\\mathrm{MSE}(\\hat{V}) = \\underbrace{\\bigl(\\mathbb{E}[\\hat{V}] - V\\bigr)^2}_{\\text{bias}^2} + \\underbrace{\\mathrm{Var}(\\hat{V})}_{\\text{variance}}$$

**实用阶梯**（偏差升、方差降）：

1. Vanilla IPS——无偏、高方差、小 $p_i$ 时不可用。

2. Clipped IPS——clip $p_i$ 到 $\\tau$；小偏差，大方差下降。

3. **SNIPS**——自归一；小偏差，真实日志上往往最优。

4. **Doubly Robust (DR，双重稳健)**——SNIPS 叠加 reward model；方差进一步下降；只要**倾向模型和 reward 模型之一正确**就无偏。

**口述捷径**："SNIPS 是 IPS 除以权重之和；偏差 $O(1/N)$ 但方差有界，MSE 常常更低。vanilla IPS 爆了之后第一个伸手抓的就是它。"

## 5. Estimator Ladder at a Glance

按倾向分布形状、是否能训一个 reward model 来选：

**IPS / SNIPS / DR Estimator Comparison**

|  | Naive CTR | IPS | Clipped IPS | SNIPS | DR |
| --- | --- | --- | --- | --- | --- |
| 是否无偏? | 否 | 是（重叠下） | 否（$\\tau$ bias） | 否（$O(1/N)$） | 是（两模型之一正确即可） |
| Variance | 低 | 非常高 | 中 | 低 | 最低 |
| 需要倾向? | 否 | 是 | 是 | 是 | 是 |
| 需要 reward 模型? | 否 | 否 | 否 | 否 | 是 |
| 何时失败 | 永远（被策略偏死） | 尾部小 $p_i$ | 过度 clip 丢信号 | $w_i$ 严重偏斜 | 两模型都错 |
| 典型 LTR 用法 | 只做 baseline | 罕见 | 生产 | 生产 | 生产 + reward 模型 |


## 6. Debiased NDCG (PBM-IPS NDCG)

标准 NDCG 假设到处都有标签。生产里我们**只有 $\\pi_0$ 选择展示的那些位置上的点击**。去偏 NDCG 把每文档的相关性估计替换为它的 IPS 修正版：

IPS-**DCG**：每次观测到的点击按 $1 /$ "在其日志位置上被 examination 的概率" 加权：

$$\\widehat{\\mathrm{DCG}}(\\pi) = \\sum_{k=1}^{K} \\frac{1}{\\log_2(k+1)} \\cdot \\frac{c_{\\pi_0(k)}}{p_{k_0(d)}}$$

**解释**：每一次点击"替所有新策略下会被 examination 但实际没被看到的位置买单"。在 PBM 和正确 $p_k$ 下，这是 $\\pi$ 的 DCG 的无偏估计。再照常除以理想列表 DCG 就得到去偏 NDCG。

**已知失败模式**：

1. **位置模型错指**（真实是 cascade 而不是 PBM）-> 系统性误加权，clipping 和 SNIPS 都救不了。

2. **Trust bias (信任偏差)**——用户点 rank 1 是因为信任而不是相关；倾向模型能吸收一部分但不能全部。

3. **Presentation effects (展示效应)**——snippet 质量、缩略图、上方广告——违反"只依位置"的 examination。

4. **长尾 query**——倾向估计的方差主导；务必报置信区间，做分层分析。

**口述捷径**："去偏 NDCG = 把每位置的 gain 换成 click / $p_k$，再照常除以理想 DCG。PBM 下无偏——这个假设就是 Google 审稿人会死咬的那一条。"

## 7. SIGIR Paper: Contribution + Biggest Limitation

面试官爱考：一句话贡献 + 一句话局限。两者都要**可测、非防御性**。模板：

**Contribution (one line)**："我们展示了 [某具体技术] 在 [某 benchmark / 生产切片] 上把 [某偏差源] 以 [指标 X] 降低了 [Y%]——在 [假设 A] 之下。"

具体样本：**"我们提出一个基于 intervention harvesting 的轻量倾向估计器，在已有生产 rerank 上把 $p_k$ 恢复到与 RandPair 在 top-5 位置上差 3% 以内，无需任何新的 randomized traffic，从而让全量日志流量上的无偏 NDCG 评估成为可能。"**

**Limitation (one line)**："本方法假设 [某假设]；当 [某具体违反] 时，估计量偏差约 [Z%]，我们认为 [缓解方案 / 未来工作]。"

具体样本：**"本方法假设 PBM（只依位置的 examination）；在移动端无限下滑 SERP 上 cascade 分量占主导，我们的位置倾向在尾部估计偏差约 10-15%——cascade 扩展或 DR overlay 可解。"**

**答案质量阶梯——逼自己往上爬**：

1. 含糊（"效果不错"）。弱——零信息。

2. 指标 + 幅度（"NDCG@10 提 2 点"）。及格。

3. 指标 + 幅度 + 制度（"在 mid-tail query 上 PBM 假设下 NDCG@10 提 2 点"）。好。

4. 指标 + 幅度 + 制度 + 诚实局限（"mid-tail 上 PBM 下 +2 NDCG；tail query 仍有 3% CI；移动 cascade 未处理"）。Senior-level。

**口述捷径**："Contribution = 具体技术 + 具体 delta + 具体假设。Limitation = 假设的锋利边 + 量级 + 偏差方向 + 计划的缓解。"

## 8. Numerical Sanity Check (Small p_k Blowup)

位置倾向：$p_1 = 1.0, p_2 = 0.5, p_{10} = 0.05$。在位置 10 观察到一次点击给 IPS 求和贡献 $1/0.05 = 20$。如果在位置 10 只 log 了 100 次 impression 仅有 1 次点击，该位置的 IPS 估计 = $20/100 = 0.20$——但它的标准误差大致 $\\sqrt{\\mathrm{Var}}/N \\sim 20/\\sqrt{100} = 2.0$。**点估计被噪声压垮**。

clip 到 $\\tau = 0.1$ 把 0.05 替成 0.10，单次点击权重从 20 降到 10。该位置的点估计向下偏约 2 倍；但方差降 4 倍。SNIPS 则按所有位置的权重之和归一化——位置 1 主导桶（权重 1.0）阻止位置 10 尾部主宰最终估计。

**要点**：**倾向的尾部就是估计量跌倒的地方**。信任任何数字之前先画权重分布（log-scale 下的 $1/p_i$ 直方图）。

### 2-Minute Oral Self-Check

- [ ] 说明目标：从 $\\pi_0$ 日志估 $V(\\pi)$，不跑 A/B
- [ ] 写 IPS $= (1/N) \\sum \\mathbb{1}[d \\in \\pi]/p \\cdot c$；重叠下无偏
- [ ] Examination hypothesis：$P(\\text{click} \\mid q, d, k) = P(\\text{exam} \\mid k) \\cdot P(\\text{rel} \\mid q, d)$
- [ ] 说出 4 种 $p_k$ 估法：RandPair、intervention harvesting、EM、参数拟合
- [ ] SNIPS $= \\text{IPS} / \\sum w$；偏差 $O(1/N)$、重尾下方差更低
- [ ] 偏差-方差阶梯：naive < IPS < clipped IPS < SNIPS < DR
- [ ] 去偏 NDCG：把每位置 gain 换成 click / $p_k$ 再归一化
- [ ] SIGIR contribution：技术 + delta + 假设 + 制度
- [ ] SIGIR limitation：假设锋利边 + 量级 + 缓解
- [ ] 踩坑：小 $p_k$ 致方差爆炸；永远报 clipping $\\tau$
"""


# -------------------------------------------------------------------------
# Doc 64 -- Two-Tower Retrieval Deep Dive
# -------------------------------------------------------------------------
DOC_64 = """<!-- Generated by StudyNoteBuilder -->
""" + SENTINEL + """

# Two-Tower Retrieval Deep Dive -- Beyond InfoNCE (Google R1 Prep)

## Prerequisites

- 方程级别的 InfoNCE / contrastive loss
- Sampled softmax + popularity bias 修正
- Dense vector retrieval，cosine / dot-product 相似度
- LTR 指标：NDCG、recall@K、MRR
- ANN（approximate nearest neighbor）的高层认识

## Key Terms

- **Two-Tower (Dual-Encoder Retrieval，双塔检索)**：query 与 doc 各由独立的塔编码；打分是纯点积——doc embedding 可离线预计算并建索引
- **ANN (Approximate Nearest Neighbor，近似最近邻)**：在离线索引上做亚线性时间的向量检索；以召回换延迟和内存
- **HNSW (Hierarchical Navigable Small World，分层小世界图)**：基于图的 ANN 算法，召回 95-97% @100、亚毫秒延迟；占内存、支持增量插入
- **IVF-PQ (Inverted File + Product Quantization，倒排 + 乘积量化)**：先 IVF 粗聚类再 PQ 压缩；省内存、要周期性重建、召回一般 85-92% @100
- **InfoNCE (Information Noise-Contrastive Estimation，信息噪声对比估计)**：在一正一负的相似度上做 softmax 交叉熵；双塔训练的主力损失
- **TSS (Training-Serving Skew，训练-服务偏移)**：训练阶段所见与在线服务之间任何分布或计算差异；线下-线上指标分歧的最大单一源

## 0. Why Deep-Dive Past **InfoNCE** (Framing)

Staging-11 单独覆盖 **InfoNCE** 本身——损失、temperature、梯度。应付 ML 基础题够用了，但应付不了系统设计题。**Google R1 L5/L6 ranking 会问："十亿文档、10ms SLA，给我走一下召回阶段。"** 有趣的回答都在架构层面：**Two-Tower** 分解本身、如何挖负样本而不毒害模型、什么 ANN 索引匹配你的更新频率、以及为什么你的 offline recall@1000 涨 3 点、online NDCG 却跌。

这个 drill 覆盖上面四个系统级关注点。串起它们的线是**解耦**：query 和 doc 靠点积打分、没有 cross-attention——换来离线建索引，同时禁掉任何跨 $(q, d)$ 边界的特征。栈里每一个 tradeoff 都从这**一个约束**推出来。

**口述捷径**："**Two-tower** = dot product = 离线索引。其他一切——负样本挖掘、**HNSW** vs IVF、线下-线上 gap——都是这句首话的二阶后果。"

## 1. Why Two Towers -- Decoupled Scoring Buys the Index

规范架构：query 塔把（用户特征、上下文、文本）映到 $u \\in \\mathbb{R}^d$；item 塔把（item 特征、文本、metadata）映到 $v \\in \\mathbb{R}^d$。打分是纯内积：

双塔打分：独立算出的 query 和 doc embedding 的点积：

$$s(q, d) = u_\\theta(q)^\\top v_\\phi(d), \\quad u, v \\in \\mathbb{R}^d$$

**关键性质**：$v_\\phi(d)$ **只依赖** $d$，永远看不到 query。这一个约束就是让十亿级召回成为可能的原因。具体三条：

1. **离线预计算 (Offline precomputation)**：每个 doc 的 $v$ 在每次 corpus snapshot 时计算一次，而不是每次 query 计算一次。对一个 $10^9$-doc 索引、1B 参数的塔，这就是 10ms SLA 和 10 分钟 SLA 的差距。

2. **ANN 索引构建 (ANN index build)**：所有 $v$ 固定后，在其上建向量索引（HNSW 或 **IVF-PQ**）。在线服务变成 encode(q) -> **ANN** search——$O(\\log N)$ 甚至更好，而不是 $O(N)$。

3. **实时 query 特征免费 (Fresh query features are free)**：$u_\\theta$ 每次请求重新计算，所以实时上下文（位置、session、时段）不额外掏钱。这就是双塔在上下文敏感检索里统治力的根源（DoorDash、YouTube 首页 feed、Pinterest homefeed）。

**代价是表达能力**。cross-encoder 能对 $(q, d)$ token 做联合注意力，学到"query 词 A 与 doc 词 B 的交互"；双塔学不了。任何**跨 $(q, d)$ 边界**的特征——"q 里多少词出现在 d"、"$(q, d)$ 对的历史 CTR"——都必须活在 reranker 里，不能在 retriever 里。标准生产模式是 retrieval (双塔) -> rerank (top-K 候选上的 cross-encoder)：

两阶段 pipeline：廉价点积召回喂昂贵 cross-attention rerank：

$$\\text{retrieve}: \\text{top-}K_{d} \\; u^\\top v \\;\\; \\longrightarrow \\;\\; \\text{rerank}: \\mathrm{score}_{\\text{cross}}(q, d)$$

口述答案里要提的系统影响：

- **索引刷新延迟 (Index refresh latency)**：换 item 塔要**重新编码整个 corpus**——留几小时的 rebuild 时间。孪生查询（"同一 item 有多套 metadata"）要版本化。

- **无 late interaction**：ColBERT 等模型用 per-token late interaction 放松双塔，内存大约 10 倍以换召回提升。能承担就上；Google 的规模往往不行。

- **User 塔必须纯净**：不能有任何依赖候选 doc 的特征。审稿人会死咬这条——如果你说"user embedding 里放了 top-candidate 信号"，你就破了解耦、失去了离线索引。

**口述捷径**："两塔意味着 $v$ 不知道 $q$，所以 $v$ 可预计算，所以 $v$ 上的 ANN 索引给你亚毫秒召回。架构代价是没有 cross-attention——所以我们**永远**加一个 reranker。"

## 2. Negative Sampling -- Four Strategies, Four Failure Modes

双塔用 **InfoNCE** 训练就是小负样本集上的纯 softmax；模型质量**被负样本分布支配**。全 corpus softmax 不可行，生产系统都从四种策略里挑（通常混合）。

InfoNCE over $K$ negatives：这 $K$ 负样本的分布选择是主导的设计变量：

$$\\mathcal{L}_{\\text{InfoNCE}} = -\\log \\frac{\\exp(u^\\top v^+ / \\tau)}{\\exp(u^\\top v^+ / \\tau) + \\sum_{j=1}^{K} \\exp(u^\\top v_j^- / \\tau)}$$

**(a) Random negatives**：从 corpus 均匀抽 $K$ 个 item。便宜、相对 corpus 先验无偏。*失败模式*：大多数随机 item **琐碎地是负的**——"query = 披萨" vs "doc = 电钻"根本不是难题。模型学会粗粒度主题，**却从不学到真正驱动用户满意度的同主题细区分**。

**(b) In-batch negatives**：把同一 minibatch 里其他行的正样本当本行的负样本。$K = \\text{batch\\_size} - 1$ 白送，不多做 forward。*失败模式*：**popularity bias (流行度偏差)**——高频 item **同时**按频次出现在正样本和负样本里。梯度**过度惩罚**流行 item，把它们从高频 query 那里**挤走**。教科书修法是 sampled-softmax **logit correction**：

流行度修正 logit：减去 log 采样概率，恢复"全 corpus 无偏 softmax"（Bengio-Senecal 2008, YouTube DNN）：

$$s'(q, d_j) = u^\\top v_j - \\log p_j, \\quad p_j = P(\\text{item } j \\text{ sampled})$$

不修正的话，in-batch negatives 会让索引系统性偏向**不利于头部分布**——而头部正是 reranker 最依赖的部分。

**(c) Hard negatives**：训练步 $t$ 用当前模型跑一次 ANN，把 top-K **未被点击**的 item 当 $t+1$ 步的负样本。把决策边界**锐化到真正重要的 margin 附近**。*失败模式 1*：**false negatives (假负样本)**——用户没点不是因为 item 不相关，而是**没看到**（折叠下、下一页）。训练把相关 item 推离 query。*失败模式 2*：**自我强化循环 (self-reinforcing loop)**——从当前模型挖出的 hard negative 编码了当前模型的偏差；用它们训练反而**收紧**这些偏差而不是纠正。**标准缓解：从上一版本的 snapshot 里挖，而不是 live 模型**。

**(d) Mixed / curriculum**：生产默认——比如 50% in-batch、30% random、20% hard。比例是值得 sweep 的超参。*失败模式*：混合比例常常**一次选定后再也不调**——即使 corpus 或 query 分布迁移了。

**贯穿的坑：positive-only bias (只看正样本偏差)**。训练对来自点击；点击只在 impression 过的 item 上发生。$\\pi_0$ 从不展示的 item 既不是正样本也不是 hard negative——它们**对训练不可见**。这和 **IPS**（见 IPS drill, T-P0-418）为评估解决的 selection bias 是同一个问题，它**对召回训练同样重要**：你学不会召回你从未 log 过的东西。

**口述捷径**："Random 无偏但太易；in-batch 便宜但流行度偏（减 $\\log p_j$）；hard 锐利但有 false negative 和自我强化（从 snapshot 挖）。三者混。Positive selection bias 是混合救不了的那条。"

## 3. HNSW vs IVF-PQ -- Recall, Latency, Memory, Updates

两大生产 ANN 索引有**正交的失败模式**；选哪一个是**系统设计决策，不是调参**。一张速查表：

**HNSW vs IVF-PQ vs Flat -- Production ANN Tradeoffs**

|  | HNSW | IVF-PQ | Flat (exact) |
| --- | --- | --- | --- |
| 结构 | 多层邻近图 | IVF 分桶 + PQ 压缩向量 | 线性扫描 |
| 构建时间 | 慢（$10^8$ 规模小时级） | 中（IVF k-means + PQ 训练） | 无 |
| 查询延迟 | 亚毫秒（约 0.3-0.5ms） | 约 1ms（nprobe 相关） | $O(N)$——$10^6$ 以上秒级 |
| 内存 | 高（图约 2-4x 向量大小） | 低（PQ 后每向量 4-16 字节） | 精确——$4 \\cdot d$ 字节 |
| Recall@100 | 95-98% | 85-92%（取决 PQ loss） | 100%（ground truth） |
| 增量插入 | 原生支持 | 要 IVF 重分配，一般 rebuild | 自由 |
| 距离度量 | dot / cosine / L2 均可 | L2 原生；dot 需变换 | 任意 |
| 失败模式 | $10^8$ 向量后内存爆 | 重尾 query 上召回崩 | $10^6$ 以上延迟致命 |


## 3.1 When to Pick Which

**选 HNSW**：corpus 能全塞内存（$d=128$ 下 $10^8$ 向量以下），延迟 SLA 紧（1ms 以下），item 按增量更新（开店 / 关店、商品上下架）。典型场景：DoorDash 商家召回、Pinterest 指定 board 上的 pin 召回。

**选 IVF-PQ**：corpus 是 $10^9+$ 向量、内存是绑定约束，更新按 batch（日级或周级 rebuild 可接受），且能接受 90-92% 召回——靠 rerank 阶段补。典型场景：YouTube 视频 corpus、Google Web 索引的召回 cell。

**选 Flat**：你在 debug、为 recall 测量做 ground truth、或 corpus 在 $10^5$ 以下且不关心延迟。**永远别上 prod**。

**混合 (Hybrid)**：很多系统外层用 IVF-PQ（粗 cell 路由），cell 内用 HNSW（被选中 cell 的细搜索）。Faiss 复合索引开箱就支持。

## 3.2 Recall vs Latency Curve

两个索引都暴露 recall / latency 旋钮——HNSW 的 `ef_search`、IVF-PQ 的 `nprobe`。面试官会压你怎么调：

- **召回目标要比下游需要的高一截**——比如 reranker 见 top-100、你要 95% 有效召回，就把 ANN 调到 recall@1000 = 97-98%，给 rerank 留 headroom。

- **永远 over-retrieve**：向 ANN 要 top-(K * 2-5)，让 reranker 剪枝。边际延迟成本几乎持平；召回提升显著，因为 ANN 的 2-5% 漏检与 rerank 误差**不相关**。

- **召回要对照 ground-truth Flat 报**，不是对照训练标签——你要把**索引近似误差**和**模型质量误差**分开。

**口述捷径**："HNSW 用于内存里亚毫秒；IVF-PQ 用于十亿级 + batch 更新。Over-retrieve 2-5x，让 reranker 收尾。对照 ground-truth Flat 调 `ef_search` / `nprobe`，不是训练标签。"

## 4. Offline Recall@K vs Online NDCG -- The Skew That Matters

Google R1 面试官在找的失败模式：**"我们上线了 v2，offline recall@1000 涨 3 点，online NDCG 跌 0.5 点、流量回到 baseline。"** 这不是测量误差，是 **Training-Serving Skew (TSS)** + **5 个具体来源**。**能把 5 条都说出来就是 senior 级答案**。

**Source 1: ANN 近似偏差 (ANN approximation skew)**。离线 recall 一般对照 Flat (exact) top-K 评；在线服务用 HNSW 或 IVF-PQ，漏检率 3-10%。离线数字**不反映用户实际看到的**。*诊断*：把 "index recall" = recall(ANN top-K, Flat top-K) 作为独立指标；不信任任何没把**模型召回**和**索引召回**分开的数字。

**Source 2: 特征偏差 (Feature skew)**。query 塔用的特征（session 历史、位置、实时上下文）离线（从日志去重回填）和在线（流式、新鲜、带时钟偏差）**计算方式不同**。*诊断*：拿 held-out 的已 log query 分别跑离线和在线 pipeline，比较两条分数分布。KL 散度超过约 0.05 就是冒烟枪。

**Source 3: 奖励错配 (Reward misalignment)**。离线 recall 把"相关 = 用户点击"；在线 NDCG 用等级标签或另一个 reward model。以**点击正样本召回**为目标训的 retriever 可能召回标题党、压过真正带来满意度的 item——online NDCG 跌而 recall@1000 涨。*诊断*：离线 recall 评估用**和在线指标同一套 relevance 函数**，不用"是否点击"。

**Source 4: Rerank 反转 (Rerank inversion)**。retrieval 按点积排；生产列表按 cross-encoder rerank。换了 retriever 后候选集可能一样但**顺序变了**——reranker 的校准基于旧 retriever 的分数分布训练，分布一动 ranker 校准就破（见 T-P0-417 Calibration drill）。*诊断*：每次换 retriever 都要**重训 rerank 或 temperature 重校准**；离线评估整**完整 pipeline (retrieve + rerank)**，不是单独 retrieval。

**Source 5: 流行度漂移 (Popularity drift)**。离线训练负样本从历史 corpus 分布抽；在线活跃候选集偏向更新、更流行的 item。如果 in-batch logit correction 用错了 $p_j$ 分布，**头部 item 会在线上被过度压制**。*诊断*：监控头/尾召回分解。如果头部 recall 跌了、尾部涨了，流行度修正过火了。

经典的全栈无偏评估做法：

去偏离线 NDCG via IPS（见 T-P0-418 drill）：把 selection 和 position bias 除掉，让离线和在线可比：

$$\\widehat{\\mathrm{NDCG}}(\\pi_{\\text{new}}) = \\sum_{q, d \\in \\text{logs}} \\frac{c_{q,d}}{p_{k_0(q,d)}} \\cdot g_\\pi(q,d)$$

**口述捷径**："五种偏移：索引召回 vs Flat、特征新鲜度、reward 函数、rerank 校准、流行度漂移。上线前每一个都做针对性离线诊断。Offline recall@K 单独不是 ship gate；debiased offline NDCG 更接近，仍然要小 A/B 兜底。"

## 5. Numerical Sanity Check -- Putting Scales on It

面试官爱听的具体数字：

- 典型 embedding 维度 $d$：64-256。$d$ 超过约 256 召回几乎不涨、ANN 延迟却线性增。

- HNSW 内存：约 $(4d + 8M)$ 字节 / 向量，$M$ 是图度数（典型 $M=16$）。$d=128, M=16$：每向量约 640 字节。$10^8$ 向量 -> 64 GB RAM——这就是 HNSW 单机顶格的地方。

- IVF-PQ PQ 压缩后内存：每向量 8-16 字节。$10^9$ 向量 -> 8-16 GB。这就是为什么 web 规模只能 IVF-PQ。

- Batch size 8192 的 in-batch negatives：每正样本白送 $K=8191$ 个负样本。这是为什么双塔训练能容易扩到超大 batch——**有效 $K$ 随 batch 长，item 塔却不多 forward 一次**。

- Temperature $\\tau$：典型 0.05-0.1。太小（< 0.01）-> 梯度集中在最近负样本，训练不稳。太大（> 0.5）-> 损失几乎均匀，模型学得慢。

- Rebuild 节奏：HNSW 秒级接受写入；IVF-PQ 一般日级 rebuild。若任务要"分钟级 fresh"，HNSW 或分层索引**必选**。

### 2-Minute Oral Self-Check

- [ ] 双塔架构：独立 $u_\\theta(q), v_\\phi(d)$，score = $u \\cdot v$
- [ ] 解耦 -> 离线预计算 + ANN 索引（这就是全部收益）
- [ ] 代价：无 cross-attention -> 跨特征必须活在 reranker
- [ ] 负样本：(a) random、(b) in-batch（修正 $-\\log p_j$）、(c) hard（从 snapshot 挖）、(d) 混合
- [ ] In-batch 流行度偏差 用 sampled-softmax log 修正
- [ ] Hard-negative 失败模式：false negatives + 自我强化循环
- [ ] HNSW：图、亚毫秒、增量、占内存、$\\le 10^8$ 规模
- [ ] IVF-PQ：粗桶 + PQ 压缩、省内存、batch rebuild、$10^9+$ 规模
- [ ] Over-retrieve 2-5x 喂 rerank；按 Flat ground truth 调 `ef_search` / `nprobe`
- [ ] 五种 **TSS** 来源：索引召回、特征偏差、reward 函数、rerank 校准、流行度漂移
- [ ] Offline recall@K 单独不是 ship gate；debiased NDCG + 小 A/B 兜底
"""


# -------------------------------------------------------------------------
# Doc 67 -- A/B Test Rigor Drill: Sample Size / SRM / CUPED / Novelty
# -------------------------------------------------------------------------
DOC_67 = """<!-- Generated by StudyNoteBuilder -->
""" + SENTINEL + """

# A/B Test Rigor Drill -- Sample Size / SRM / CUPED / Novelty + Etsy GMB Trap

## Prerequisites

- 假设检验：Type I / Type II 错误、power = $1 - \\beta$
- Central Limit Theorem、比例 / 均值的标准误差
- 二价拍卖出价（bid = value * P(action)）
- OLS regression 与 $R^2$ 作为方差解释比例

## Key Terms

- **MDE (Minimum Detectable Effect，最小可检测效应)**：给定 $\\alpha, \\beta$ 下实验有 power 检测到的最小真实 delta
- **SRM (Sample Ratio Mismatch，样本比不匹配)**：对 arm 尺寸做卡方检验；指向 randomization 或 logging bug，不是 treatment 效应
- **CUPED (Controlled-experiment Using Pre-Experiment Data，用实验前数据做受控实验)**：用 pre-period 协变量回归做方差缩减；把 $n$ 砍到 $n \\cdot (1 - \\rho^2)$
- **OEC (Overall Evaluation Criterion，总评估指标)**：事先声明的**唯一**主指标；guardrails 另外监控、另外做 FDR 控制
- **GMB (Google Merchant Bidding，Google 购物广告)**：付费购物渠道，bid = target_ROAS * 预测价值；Etsy 大量使用

## 0. Why Rigor Matters (The Framing)

大多数 A/B 灾难不是模型 bug——是**实验卫生**失败：under-powered 上线被报"flat"、peeking 把 Type I 吹涨、treatment 效应被 novelty 混淆。这个 rigor drill 就是**每次上线必过的五道独立检查**。

**心智顺序**：(1) 上线前算 sample size，(2) 看业务指标前先 **SRM**，(3) 分析时上 **CUPED** / 方差缩减，(4) 结论冻结前做 novelty washout，(5) 对历史踩过的坑做模式匹配。

**口述捷径**："开始前 power 足够、看指标前 SRM、分析时 CUPED、相信 lift 前 washout、永远看看你是不是踩了见过的坑。"

## 1. Sample Size Formula -- Continuous Metric

对均值相等的双边检验，总 variance 为 $\\sigma^2$、目标 lift 为 $\\delta$，每 arm 样本量：

双边检验，$\\alpha$ = Type I 风险，$\\beta$ = Type II 风险，power = $1 - \\beta$：

$$n = \\frac{2 \\sigma^2 (z_{\\alpha/2} + z_{\\beta})^2}{\\delta^2}$$

**推导草图**：在 $H_0$ 下检验统计量 $\\sim N(0, 1)$；在 $H_1$ 下 $\\sim N(\\delta / \\text{SE}, 1)$，其中 $\\text{SE} = \\sqrt{2 \\sigma^2 / n}$。在双边 $\\alpha$ 下拒绝 $H_0$ 要求 $|T| > z_{\\alpha/2}$；在 $H_1$ 下达到 power $1 - \\beta$ 要求 $\\delta / \\text{SE} \\ge z_{\\alpha/2} + z_{\\beta}$。解 $n$ 得公式。**两个 $z$ 分位数相加**是因为它们衡量**同一方向上**的临界位置和拒绝尾。

power 条件解出 $n$ 就是 sample-size 公式：

$$\\frac{\\delta}{\\mathrm{SE}} = \\frac{\\delta}{\\sqrt{2\\sigma^2 / n}} \\ge z_{\\alpha/2} + z_{\\beta}$$

**典型分位数**：$\\alpha = 0.05$ 双边、power = 0.80：$z_{\\alpha/2} = 1.96, z_{\\beta} = 0.84$，$(1.96 + 0.84)^2 \\approx 7.84$。

**数值锚点**：$\\sigma = 12$ USD/user 收入、$\\delta = 0.20$ USD（$\\approx 4\\%$ lift on 5 USD baseline） => $n = 2 \\cdot 144 \\cdot 7.84 / 0.04 \\approx 56{,}448$ /arm。用 CUPED 把 $\\sigma$ 砍半 => $n$ 降到约 14,000——**最大的单一杠杆**。

**比例指标**（CTR / CVR）baseline 为 $p$，代入 $\\sigma^2 = p(1-p)$。$p = 2\\%$、相对 **MDE** 10%（$\\delta = 0.002$）下 $n \\approx 80{,}600$ /arm（pooled variance）。

**口述捷径**："$n$ 规模随 $\\sigma^2 / \\delta^2$——MDE 减半，$n$ 翻 4 倍；$\\sigma$ 减半，$n$ 减半。公式背下：$2 \\sigma^2 (z_{\\alpha/2} + z_\\beta)^2 / \\delta^2$。"

## 2. SRM -- Randomization Health, Not a Business Result

**SRM = Sample Ratio Mismatch**：用卡方检验观测到的 arm 尺寸是否匹配设计分配（如 50/50 或 90/10）。

对比观测 arm 数 $N_k$ 与期望 $E_k$ 的卡方统计量：

$$\\chi^2 = \\sum_{k} \\frac{(N_k - E_k)^2}{E_k}, \\quad \\mathrm{df} = K - 1$$

**关键框架**：SRM 是**随机化诊断 (randomization diagnostic)**，**不是结果指标**。它不告诉你 treatment 有没有用。它告诉你**随机化、logging、过滤 pipeline 是否可信**。SRM 触发意味着你看到的是 pipeline bug，而不是 hypothesis test。

**SRM 触发的常见根因**：

- Bot / crawler 过滤**跨 arm 非对称**（某 arm 缓存方式不同、某 arm 被 pre-roll 过滤漏掉）

- Redirect 或 feature-flag 代码在某 arm 抛异常、用户被**静默丢失**

- Logging 被某变体**延迟或丢失**（例如 treatment 触发一个新信标而该信标在 Safari 里失败）

- Trigger 条件依赖**只在某 arm 里计算**的特征（post-treatment filtering）

**互联网规模下**，1M 用户的 49.4 / 50.6 就能跑出卡方 $p < 0.001$——SRM **非常敏感**。信任告警：SRM 触发**作废**所有下游指标。

**操作规则**：在生成任何 lift 报告**之前**，在 pipeline 内跑 SRM。如果 SRM 失败，把实验 gate 到"阻塞-调查中"——**不要用眼瞟 OEC**；那个数字已被造成偏移的原因污染。

**口述捷径**："SRM 是 arm 尺寸的卡方检验。管道健康检查，不是 treatment 结果。触发 => pipeline bug，不是 flat/lift。永远先于任何业务指标跑。"

## 3. CUPED -- Pre-Period Covariate for Variance Reduction

**CUPED (Deng et al. 2013, Microsoft)** 是方差缩减的主力。选一个**实验开始前**测量的协变量 $X_{\\text{pre}}$（比如同一用户实验开始前 14 天的 revenue）。把 $Y$ 对 $X_{\\text{pre}}$ 回归得到 $\\theta$，再分析残差：

调整后的指标：减去 pre-period 协变量的 OLS 预测：

$$Y_{\\mathrm{CUPED}} = Y - \\theta \\cdot (X_{\\mathrm{pre}} - \\bar{X}_{\\mathrm{pre}}), \\quad \\theta = \\frac{\\mathrm{Cov}(X_{\\mathrm{pre}}, Y)}{\\mathrm{Var}(X_{\\mathrm{pre}})}$$

**残差方差被 pre-post 相关系数 $\\rho$ 的平方砍掉**：

$$\\mathrm{Var}(Y_{\\mathrm{CUPED}}) = \\mathrm{Var}(Y) \\cdot (1 - \\rho^2)$$

因为随机分配保证了 $\\mathbb{E}[X_{\\text{pre}} \\mid \\text{treatment}] = \\mathbb{E}[X_{\\text{pre}} \\mid \\text{control}]$，减去 $\\theta \\cdot (X_{\\text{pre}} - \\bar{X})$ **不会偏估 treatment 效应**。它只是重新分解方差：**同一用户跨期共有的随机噪声被吸进协变量**。

**样本量按同一因子下降**：$n_{\\text{CUPED}} = n \\cdot (1 - \\rho^2)$。同用户 pre/post 的典型 $\\rho$：0.5 => 样本减 25%；0.7 => 减 51%。**Ads / revenue 类指标常能打到 $\\rho = 0.6 \\sim 0.8$**，因为重度用户在两个窗口都占优。

**踩坑点**：协变量**必须只用 pre-period 数据**、**绝不能被 treatment 污染**。如果 $X_{\\text{pre}}$ 偷偷包含了实验开始当天，它就变成 post-treatment，CUPED 会让估计有偏。**安全规则：在 randomization 时刻冻结 $X_{\\text{pre}}$、存下来、永不重算**。

**Type I 不变**：因为 $\\theta$ 在 pooled 数据上拟合、treatment 与 $X_{\\text{pre}}$ 期望下正交，$\\mathbb{E}[Y_{\\text{CUPED}} \\mid \\text{treat}] = \\mathbb{E}[Y_{\\text{CUPED}} \\mid \\text{control}]$ 的检验 Type I 不变。**方差缩减是免费的 power 提升**。

**口述捷释**："CUPED 减去 $\\theta$ 乘以 pre-period 协变量残差。方差降 $1 - \\rho^2$、样本降同一因子。只用 pre-period、在 randomization 时冻结。免费 power，无 bias，Type I 不变。"

## 4. Novelty vs Primacy -- Why You Need a 1-Week Washout

任何 UX 变化的前几天都会出现**两种相反**的时间偏差：

- **Novelty (新奇效应)**：用户点新东西是**因为它新**（第 1-3 天 CTR 高估、第 7 天衰减）。常见于视觉改版、新角标位置、新推荐位。

- **Primacy (首因效应)**：用户忽视或抵抗新东西——因为不熟悉、或隐藏了他们依赖的功能（第 1-3 天参与度压低、第 7 天恢复）。常见于布局重排、按钮移除、tab 改名。

两种效应都在**相近的 3-7 天时间尺度**上衰减。**一周 washout** 意味着：开始实验，**忽略前 7 天**做点估计，从稳定尾部读 lift。或者画 7 天滚动 lift 曲线，只信任**平台期**。

Washout 分析：在 novelty 窗口后 ($T \\ge 14$) 平均 lift：

$$\\Delta_{\\text{reported}} = \\frac{1}{T - 7} \\sum_{t=8}^{T} \\Delta_t, \\quad T \\ge 14$$

**为什么偏偏是一周**：产品使用周期**以周为单位**（工作日 vs 周末、发薪日、邮寄时间）。短于 7 天的窗口还携带 day-of-week 混淆，所以 7 天**一招处理 novelty + 周期性**。

**失败模式**：把第 3 天的 lift 当作定论。如果 novelty 是 +5%、真实效应是 0%，第 3 天说"上线"、第 2 个月说"指标怎么回来了？"。广告排序上线的事后分析里**常见 novelty 没 washout** 导致的回溯。

配套：**Cohort 新鲜度检验**——按"本实验内首次暴露" vs "已在前置重叠实验里暴露过"分组。如果 novelty 真的存在，新 cohort 的 gap 最大。

**口述捷径**："Novelty = 早期正向偏；primacy = 早期负向偏；两者都 3-7 天衰减。跑至少 14 天，lift 从第 8 天起读。7 天同时吞掉 day-of-week 混淆。"

## 5. Etsy **GMB** Bidding Trap -- Unit-of-Analysis + SRM Story

现实世界的复合陷阱，来自 Etsy Google Merchant Bidding (GMB) 实验。一次 bid multiplier 变化 A/B 跨合格 campaign 测试。**观察到的 lift 看起来又大又 stat-sig；上线被三次独立的 rigor 检查连续挡下**。

**Trap 1: Unit-of-analysis mismatch (分析单位错配)**。Randomization 在 **campaign 级**，但指标（revenue per impression）在 **impression 级**聚合。方差按"impression i.i.d."计算——系统性**低估** SE，因为同 campaign 内 impression 相关。**名义 $p = 0.02$ 在正确的 cluster-robust SE 下塌到 $p = 0.15$**。

Design effect：cluster size $m$、intra-cluster 相关 $\\rho_{\\text{icc}}$ 膨胀方差：

$$\\mathrm{Var}_{\\mathrm{cluster}}(\\hat{\\Delta}) = \\frac{\\sigma^2}{n} \\cdot \\bigl(1 + (m - 1) \\rho_{\\mathrm{icc}}\\bigr)$$

**Trap 2: 拍卖密度不对称造成的 SRM**。Treatment 因为 multiplier 更高**赢更多拍卖**，所以 treatment campaign 在同窗口里**服务了更多 impression**。这看起来像 SRM（campaign 级 50/50 没问题、impression 级 53/47 报警）。**但这不是 bug——是 treatment 效应泄漏进了分配比例**。教训：**SRM 必须在 randomization 单位（campaign）上跑，不是 analysis 单位（impression）**，否则正当的赢会看起来像 pipeline 失败。

**Trap 3: 出价曲线里的 novelty**。第 1-4 天显示 +8% revenue lift——因为 Google smart-bidding 系统还没**重新校准竞争响应**。第 10 天 lift 稳定在 +1.5%——竞品 bid 已调整。**把第 4 天数字当上线定论 = 三倍计了这个过渡性优势**。

**结果**：ship 决策翻为"iterate"。14 天 washout + cluster-robust SE + campaign-level SRM 后的最终读数：lift = +1.1%, $p = 0.08$，$\\alpha = 0.05$ 下**不 stat-sig**。加宽合格范围 + CUPED on pre-period GMV 增加 power，下季度成功检测到稳健的 +0.9% lift。

**要点模式**：在 bidding / auction 实验里盯紧 (a) randomization 单位与 analysis 单位的相关、(b) treatment 效应泄漏进分配比例、(c) novelty 不光来自用户、还来自周边拍卖生态。**广告平台是对抗系统——竞品在几天内响应你的 treatment，而不是瞬间**。

**口述捷径**："Etsy GMB 我见过复合陷阱——impression 级 SE 低估、拍卖密度触发 SRM、拍卖级 novelty。用 campaign 级 cluster-robust SE、campaign 级 SRM、14 天 washout 修掉。把 $p=0.02$ 的 ship 翻成 $p=0.08$ 的 iterate。"

## 6. Five Rigor Checks at a Glance

**顺序关键**：上线前算样本量、出指标前跑 SRM、分析时做方差缩减、结论前 washout、前后做模式匹配。

**Five A/B Test Rigor Checks**

| Check | When | What it verifies | Red flag |
| --- | --- | --- | --- |
| Sample size | 上线前 | 对 MDE 的 power | $n$ 太低 -> under-powered 'flat' |
| SRM | 运行中每日 | Randomization / logging 健康 | arm 尺寸卡方 $p < 0.001$ |
| CUPED | 分析时 | 方差缩减增 power | 协变量泄漏进 post-treatment |
| Novelty washout | 分析时 | 稳定长期效应 | 第 3 天和第 14 天结论不同 |
| Prior-trap audit | 前后 | 已知失败模式模式匹配 | 拍卖密度 / 分析单位 / cohort 效应 |


## 7. Numerical Memory Pegs

背几个锚点、30 秒内估出 $n$：

**Sample-size anchors (两边、pooled variance)**

| Scenario | Assumption | n per arm (approx) |
| --- | --- | --- |
| CTR 2%, 相对 MDE 10% | $\\alpha=0.05$, power=0.80 | ~80,600 |
| CTR 2%, 相对 MDE 5% | $\\alpha=0.05$, power=0.80 | ~320,000 |
| CTR 2%, 相对 MDE 1% | $\\alpha=0.05$, power=0.80 | ~7,900,000 |
| Revenue $\\sigma=12$, $\\delta=0.20$ USD | $\\alpha=0.05$, power=0.80 | ~56,500 |
| 同上，CUPED $\\rho=0.5$ | 方差 x (1 - 0.25) | ~42,400 |
| 同上，CUPED $\\rho=0.7$ | 方差 x (1 - 0.49) | ~28,800 |


### 2-Minute Oral Self-Check

- [ ] 样本量公式：$n = 2 \\sigma^2 (z_{\\alpha/2} + z_\\beta)^2 / \\delta^2$
- [ ] 两个 $z$ 分位数相加是因为衡量的都是**同方向**的距离
- [ ] SRM = arm 尺寸卡方；随机化健康，不是结果
- [ ] SRM 在 randomization 单位上跑，不在 analysis 单位
- [ ] CUPED = $Y - \\theta (X_{\\text{pre}} - \\bar{X})$；方差降 $(1 - \\rho^2)$
- [ ] CUPED 协变量**严格 pre-treatment**、randomization 时冻结
- [ ] Novelty = 早期正偏、Primacy = 早期负偏
- [ ] 一周 washout 同时吞 novelty 和 day-of-week 周期
- [ ] **永远声明分析单位和 randomization 单位**
- [ ] Etsy GMB 陷阱 = cluster SE + 拍卖密度 SRM + 拍卖 novelty
"""


DOCS: dict[int, tuple[str, str]] = {
    62: (
        "Calibration Drill: Platt / Isotonic / Temperature + GMB Bidding Trap (Google R1 Prep)",
        DOC_62,
    ),
    63: (
        "IPS / Counterfactual Eval / Debiased NDCG Drill (Google R1 Prep, SIGIR talking points)",
        DOC_63,
    ),
    64: (
        "Two-Tower Retrieval Deep Dive (Google R1 Prep, beyond InfoNCE)",
        DOC_64,
    ),
    67: (
        "A/B Test Rigor Drill: Sample Size / SRM / CUPED / Novelty + Etsy GMB Trap (Google R1 Prep)",
        DOC_67,
    ),
}


def cjk_ratio(text: str) -> float:
    """Return CJK / (CJK + Latin letters) ratio for the given text."""
    cjk = sum(1 for c in text if "\u4e00" <= c <= "\u9fff")
    latin = sum(1 for c in text if c.isalpha() and ord(c) < 128)
    total = cjk + latin
    return cjk / total if total else 0.0


def main() -> int:
    conn = sqlite3.connect(str(DB_PATH))
    try:
        updated = 0
        unchanged = 0
        for did, (_expected_title, new_content) in DOCS.items():
            row = conn.execute(
                "SELECT title, content FROM company_documents WHERE id = ?",
                (did,),
            ).fetchone()
            if row is None:
                print(f"[ERROR] doc {did} not found")
                continue
            cur_title, cur_content = row
            if SENTINEL in cur_content:
                print(f"[UNCHANGED] doc {did} ({cur_title}) -- sentinel present")
                unchanged += 1
                continue
            cur = conn.execute(
                "UPDATE company_documents SET content = ? WHERE id = ?",
                (new_content, did),
            )
            conn.commit()
            ratio = cjk_ratio(new_content)
            print(
                f"[UPDATE] doc {did} rows={cur.rowcount} new_len={len(new_content)} "
                f"cjk_ratio={ratio:.1%}"
            )
            updated += 1
        print(f"Summary: updated={updated}, unchanged={unchanged}")
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
