"""Tests for StudyNoteBuilder and FormulaBlock."""

import importlib.util
import sqlite3
import sys
from pathlib import Path

import pytest

_BUILDER_PATH = Path(__file__).resolve().parent.parent / "scripts" / "study_note_builder.py"
_spec = importlib.util.spec_from_file_location("study_note_builder", _BUILDER_PATH)
_mod = importlib.util.module_from_spec(_spec)  # type: ignore[arg-type]
sys.modules["study_note_builder"] = _mod  # register before exec to resolve dataclass
_spec.loader.exec_module(_mod)  # type: ignore[union-attr]
FormulaBlock = _mod.FormulaBlock
StudyNoteBuilder = _mod.StudyNoteBuilder


class TestFormulaBlock:
    """Tests for FormulaBlock dataclass."""

    def test_build_wraps_in_double_dollar(self) -> None:
        fb = FormulaBlock(latex=r"x^2 + y^2 = z^2")
        result = fb.build()
        assert "$$x^2 + y^2 = z^2$$" in result

    def test_build_never_uses_single_dollar(self) -> None:
        fb = FormulaBlock(latex=r"\alpha + \beta")
        result = fb.build()
        # Should have $$ but no standalone $
        assert "$$" in result
        # Remove $$...$$ and check no $ remains
        stripped = result.replace("$$\\alpha + \\beta$$", "")
        assert "$" not in stripped

    def test_build_with_explanation(self) -> None:
        fb = FormulaBlock(
            latex=r"E = mc^2",
            explanation="Einstein's mass-energy equivalence:",
        )
        result = fb.build()
        assert "Einstein's mass-energy equivalence:" in result
        assert "$$E = mc^2$$" in result
        # Explanation comes before formula
        assert result.index("Einstein") < result.index("$$")

    def test_build_without_explanation(self) -> None:
        fb = FormulaBlock(latex=r"\sum_{i=1}^{n} x_i")
        result = fb.build()
        assert result.startswith("$$")


class TestStudyNoteBuilder:
    """Tests for StudyNoteBuilder."""

    def _make_builder(self) -> StudyNoteBuilder:
        """Create a builder with minimal content for testing."""
        b = StudyNoteBuilder()
        b.set_title("Test Note")
        b.add_prerequisites(["Basic math", "Python"])
        b.add_term("DDPM", "Denoising Diffusion Probabilistic Model", "Generates data via noise reversal")
        b.add_section("Introduction", [
            "This is a test section about DDPM.",
            FormulaBlock(latex=r"q(x_t|x_{t-1}) = \mathcal{N}(x_t; \sqrt{\alpha_t}x_{t-1}, (1-\alpha_t)I)"),
        ])
        return b

    def test_build_contains_header_comment(self) -> None:
        b = self._make_builder()
        content = b.build()
        assert "<!-- Generated by StudyNoteBuilder -->" in content

    def test_build_contains_title(self) -> None:
        b = self._make_builder()
        content = b.build()
        assert "# Test Note" in content

    def test_build_contains_prerequisites(self) -> None:
        b = self._make_builder()
        content = b.build()
        assert "## Prerequisites" in content
        assert "- Basic math" in content
        assert "- Python" in content

    def test_build_contains_key_terms(self) -> None:
        b = self._make_builder()
        content = b.build()
        assert "## Key Terms" in content
        assert "**DDPM**" in content
        assert "Denoising Diffusion Probabilistic Model" in content

    def test_build_contains_section_heading(self) -> None:
        b = self._make_builder()
        content = b.build()
        assert "## Introduction" in content

    def test_formula_block_uses_double_dollar(self) -> None:
        b = self._make_builder()
        content = b.build()
        assert "$$q(x_t|x_{t-1})" in content
        assert content.count("$$") >= 2  # at least one pair

    def test_auto_bold_first_term_occurrence(self) -> None:
        b = StudyNoteBuilder()
        b.set_title("Test")
        b.add_term("VAE", "Variational Autoencoder", "A generative model")
        b.add_section("Overview", [
            "A VAE learns latent representations. The VAE architecture is simple.",
        ])
        content = b.build()
        # First occurrence in prose should be bolded
        # Find the Overview section
        overview_start = content.index("## Overview")
        overview_text = content[overview_start:]
        # First VAE after Overview should be bolded
        assert "**VAE**" in overview_text
        # Second occurrence should NOT be bolded (only first)
        after_first_bold = overview_text[overview_text.index("**VAE**") + 7:]
        # The second VAE should remain unbolded
        assert "VAE" in after_first_bold

    def test_orphan_single_dollar_raises_error(self) -> None:
        b = StudyNoteBuilder()
        b.set_title("Bad Note")
        b.add_section("Math", [
            "This costs $ but is not math.",
        ])
        with pytest.raises(ValueError, match="Orphan single-dollar"):
            b.build()

    def test_paired_inline_math_allowed(self) -> None:
        b = StudyNoteBuilder()
        b.set_title("Inline Math Note")
        b.add_section("Math", [
            "The variable $x_0$ decays as $\\bar{\\alpha}_t \\to 0$.",
        ])
        content = b.build()
        assert "$x_0$" in content
        assert "$\\bar{\\alpha}_t \\to 0$" in content

    def test_double_dollar_does_not_raise(self) -> None:
        b = StudyNoteBuilder()
        b.set_title("Good Note")
        b.add_section("Math", [
            "Here is an equation:",
            FormulaBlock(latex=r"x^2"),
        ])
        # Should not raise
        content = b.build()
        assert "$$x^2$$" in content

    def test_dollar_in_code_block_ignored(self) -> None:
        b = StudyNoteBuilder()
        b.set_title("Code Note")
        b.add_section("Example", [
            "Here is code:\n\n```python\nprice = $100\n```\n\nEnd.",
        ])
        # Dollar in code block should not trigger error
        content = b.build()
        assert "```python" in content

    def test_dollar_in_inline_code_ignored(self) -> None:
        b = StudyNoteBuilder()
        b.set_title("Inline Code Note")
        b.add_section("Example", [
            "Use `$PATH` to check the variable.",
        ])
        # Dollar in inline code should not trigger error
        content = b.build()
        assert "`$PATH`" in content

    def test_add_diagram_html(self) -> None:
        b = StudyNoteBuilder()
        b.set_title("Diagram Test")
        html = '<div style="background:#1a1a2e;">Pipeline</div>'
        b.add_diagram_html(html)
        content = b.build()
        assert html in content

    def test_add_comparison_table(self) -> None:
        b = StudyNoteBuilder()
        b.set_title("Table Test")
        b.add_comparison_table(
            headers=["Method", "Speed", "Quality"],
            rows=[
                ["DP", "Fast", "Good"],
                ["TP", "Medium", "Better"],
            ],
            title="Parallelism Comparison",
        )
        content = b.build()
        assert "**Parallelism Comparison**" in content
        assert "| Method | Speed | Quality |" in content
        assert "| DP | Fast | Good |" in content

    def test_add_interview_qa(self) -> None:
        b = StudyNoteBuilder()
        b.set_title("QA Test")
        b.add_interview_qa(
            "What is DDPM?",
            "A generative model that learns to reverse noise.",
        )
        content = b.build()
        assert "**Q: What is DDPM?**" in content
        assert "A generative model that learns to reverse noise." in content

    def test_add_checklist(self) -> None:
        b = StudyNoteBuilder()
        b.set_title("Checklist Test")
        b.add_checklist("Self-Check", [
            "Can you explain the forward process?",
            "Can you derive the loss function?",
        ])
        content = b.build()
        assert "### Self-Check" in content
        assert "- [ ] Can you explain the forward process?" in content

    def test_method_chaining(self) -> None:
        b = StudyNoteBuilder()
        result = b.set_title("Chain Test").add_prerequisites(["Math"])
        assert result is b  # Returns self for chaining

    def test_validate_clean_doc(self) -> None:
        b = self._make_builder()
        content = b.build()
        warnings = StudyNoteBuilder.validate(content)
        assert warnings == []

    def test_validate_detects_orphan_dollar(self) -> None:
        content = "Some text with a stray $ sign."
        warnings = StudyNoteBuilder.validate(content)
        assert any("single-dollar" in w for w in warnings)

    def test_validate_allows_paired_inline_math(self) -> None:
        content = "<!-- Generated by StudyNoteBuilder -->\n# Title\n\nThe value $x^2$ is fine."
        warnings = StudyNoteBuilder.validate(content)
        assert warnings == []

    def test_validate_detects_missing_header(self) -> None:
        content = "# Just a title\n\nSome content."
        warnings = StudyNoteBuilder.validate(content)
        assert any("header comment" in w for w in warnings)


class TestSaveToDb:
    """Tests for save_to_db with a temporary SQLite database."""

    def _setup_db(self, db_path: Path) -> None:
        """Create the minimal schema needed for save_to_db."""
        conn = sqlite3.connect(str(db_path))
        conn.execute(
            "CREATE TABLE companies (id INTEGER PRIMARY KEY, name TEXT)"
        )
        conn.execute("INSERT INTO companies (id, name) VALUES (1, 'TestCo')")
        conn.execute(
            "CREATE TABLE company_documents ("
            "id INTEGER PRIMARY KEY AUTOINCREMENT, "
            "company_id INTEGER, "
            "title TEXT NOT NULL, "
            "content TEXT NOT NULL, "
            "source_type TEXT, "
            "created_at DATETIME DEFAULT CURRENT_TIMESTAMP, "
            "updated_at DATETIME DEFAULT CURRENT_TIMESTAMP"
            ")"
        )
        conn.commit()
        conn.close()

    def test_save_inserts_document(self, tmp_path: Path) -> None:
        db_path = tmp_path / "test.db"
        self._setup_db(db_path)

        b = StudyNoteBuilder()
        b.set_title("Test Doc")
        b.add_section("Intro", ["Hello world."])

        doc_id = b.save_to_db(
            company_id=1, doc_title="Test Doc", db_path=db_path
        )
        assert doc_id is not None

        # Verify in DB
        conn = sqlite3.connect(str(db_path))
        row = conn.execute(
            "SELECT title, content, source_type FROM company_documents WHERE id = ?",
            (doc_id,),
        ).fetchone()
        conn.close()
        assert row[0] == "Test Doc"
        assert "<!-- Generated by StudyNoteBuilder -->" in row[1]
        assert row[2] == "manual"

    def test_save_is_idempotent(self, tmp_path: Path) -> None:
        db_path = tmp_path / "test.db"
        self._setup_db(db_path)

        b = StudyNoteBuilder()
        b.set_title("Idempotent Doc")
        b.add_section("Intro", ["Content here."])

        id1 = b.save_to_db(company_id=1, doc_title="Idempotent Doc", db_path=db_path)
        id2 = b.save_to_db(company_id=1, doc_title="Idempotent Doc", db_path=db_path)
        assert id1 == id2

        # Only one record
        conn = sqlite3.connect(str(db_path))
        count = conn.execute(
            "SELECT COUNT(*) FROM company_documents"
        ).fetchone()[0]
        conn.close()
        assert count == 1
