"""One-shot helper: append T-P0-634 PROGRESS.md entry. Idempotent via marker check."""
from pathlib import Path

ENTRY = """## 2026-04-29 14:00 -- [T-P0-634] UBER-VO-7: Multi-charter wiring + content-correctness smoke (verbal-recall ACs out-of-scope for autonomous run)
- **What I did**: Programmatically executed the 6 wiring/content steps of the UBER-VO-7 smoke spec against the live `data/mle_prep.db`. (1) Doc-level smoke on id=37 -- confirmed all 5 charter rows in `<!-- T-P0-632:CHARTERS BEGIN/END -->` resolve to existing targets (db://81, db://84, db://85, /behavioral/themes?company=uber, db://36). (2) Anchor-scroll smoke -- confirmed all 5 deep anchors referenced from id=37 exist as `<h2 id="...">` tags in their target docs: id=85 has `uber-eats-restaurant-rec` / `budget-promo-recommendation` / `cross-cutting-senior-signals`; id=84 has `geometric-median` / `kmeans-numpy` / `linear-regression-from-scratch` / `logistic-regression-from-scratch` / `cross-cutting-tactics`. (3) Strengthening verification -- all 10 T-P1-631 keywords present in id=33 with case-insensitive >=1 hit; DIN additionally verified as a word-boundary token (4+ matches incl. heading "Two-tower / MMoE / DIN"). (4) Heading-stability invariant on id=33 -- diff of `logs/id33_headings_before.txt` vs `logs/id33_headings_after.txt`: 0 missing/renamed, 4 added (5.6/5.7/5.8/5.9 -- additive only, no destructive edits). (5) Source-TXT cross-check: 5 distinctive phrases sampled from `src/backend/seed_data/uber/ml_sd_golden.md` (around lines 286, 635, 762, 286, 767 across both Uber Eats + Budget Promo sections) all appear verbatim in id=85 -- no source drift. (6) Banner redirect smoke on id=81 -- `<!-- T-P2-633:REDIRECT-BANNER BEGIN -->` at byte 0, ends at byte 402, ahead of the legacy `<!-- UBER_LC_INDEX_V1 -->` sentinel (byte 404); single `db://37` deep-link present; total content len 8538, sha256 prefix `0fc3ae6af82b`. Out-of-scope for this autonomous run: VR-1..VR-5 verbal-recall ACs are explicit human-only criteria ("I can talk through ... without re-reading", "I can recite ... without notes") and require a single-sitting practice run before May 4 Coding 2.
- **Deliverables**: NEW `logs/uber_vo_smoke_20260429_085743.md` (~5 KB structured smoke log: doc inventory snapshot + step-by-step pass/fail table + verbal-recall practice plan + go/no-go verdict).
- **Sanity check result**: (a) **All 6 wiring/content checks PASS**. (b) **Heading-stability nuance**: strict literal "diff is empty" does NOT hold because T-P1-631 explicitly added 4 new H3 sub-sections -- but the underlying invariant (no existing heading was renamed, removed, or reordered) holds. The smoke log flags this discrepancy and recommends amending T-P1-631's strengthening protocol to forbid new headings if a strict empty-diff invariant is desired going forward. (c) **No source-TXT drift detected** -- 5/5 spot checks verbatim. (d) **Regression tests**: `pytest tests/` -> 1216 passed, 20 warnings, no failures. (e) **NOT verified by autonomous agent**: VR-1..VR-5 verbal-recall ACs (require human practice run); live browser scroll-to-anchor behavior (assumed correct based on react-markdown + rehype-raw stack used elsewhere; T-P0-632 vitest cases cover the click-handler regex layer). (f) **Final wiring/content go/no-go**: PASS for May 4 Coding 2 + future ML SD readiness from a content-correctness standpoint. Verbal-recall verdict pending human practice run.
- **Status**: [PARTIAL] -- wiring + content-correctness checks all pass; verbal-recall ACs (VR-1..VR-5) remain open as human-only criteria. Per the task spec, this closes wiring concerns; verbal-recall practice is tracked separately and will not block any merge.
- **Request**: `task_db.py update T-P0-634 --status completed`. UBER-VO chain is closed from the autonomous agent's perspective. Recommend a follow-up checklist task before May 4 to walk through VR-1..VR-5 in a single sitting.
"""

MARKER = "## 2026-04-29 14:00 -- [T-P0-634]"
p = Path("PROGRESS.md")
existing = p.read_text(encoding="utf-8")
if MARKER in existing:
    print("[NOOP] T-P0-634 entry already present")
else:
    with p.open("a", encoding="utf-8") as f:
        f.write(ENTRY)
    print(f"[APPEND] wrote {len(ENTRY)} chars")
