"""T-P1-582 BQ-DEPTH-11: idempotent seed for batch probe_notes (top-40 tail).

Source of truth (Invariant 3): this script + the human-approved DeepSeek sidecar
``docs/bq_probe_notes_batch{N}_20260421.deepseek.json`` (generated by
``scripts/_bq_582_probe_notes_deepseek.py`` and spot-checked by the user).

Parametric over batches 1-4 (one script, not four near-duplicates -- the project
"no duplicate utilities" rule). Run once per batch AFTER user approval:

  PYTHONUTF8=1 /c/Anaconda/python.exe scripts/seed_bq_probe_notes_20260421.py --batch 1

Idempotent: writes ``behavioral_questions.probe_notes`` (canonical JSON dump) +
``probe_notes_updated_at`` keyed on ``question_id``. Re-running an unchanged batch
prints [SKIP] for every row and writes nothing. DB-backup-guarded: takes a
timestamped ``.bak`` copy before the first write of a run.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "data" / "mle_prep.db"
DOCS = ROOT / "docs"
BACKUP_DIR = ROOT / "data" / "backups"

# The 4 schema fields, in canonical order, that must all be present + non-empty.
REQUIRED_FIELDS = ("core_signal", "what_good_looks_like", "what_L5_adds", "common_failure_modes")


def _canonical(pn: dict) -> str:
    """Serialize probe_notes to the canonical JSON string stored in the DB.

    Field order fixed; ensure_ascii=False so CJK is stored as-is. This is the
    exact string compared for idempotency, so the renderer must be stable.
    """
    ordered = {k: pn[k] for k in REQUIRED_FIELDS}
    return json.dumps(ordered, ensure_ascii=False)


def _validate(pn: dict, qid: str) -> None:
    """Raise ValueError if the entry violates the locked 4-field schema."""
    if "_parse_error" in pn:
        raise ValueError(f"{qid}: sidecar entry has a DeepSeek parse error -- regenerate")
    for f in REQUIRED_FIELDS:
        v = pn.get(f)
        if v is None or (isinstance(v, (str, list)) and len(v) == 0):
            raise ValueError(f"{qid}: empty/missing field {f!r}")
    extra = set(pn) - set(REQUIRED_FIELDS)
    if extra:
        raise ValueError(f"{qid}: unexpected field(s) {sorted(extra)}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--batch", type=int, required=True, choices=[1, 2, 3, 4])
    args = ap.parse_args()

    sidecar = DOCS / f"bq_probe_notes_batch{args.batch}_20260421.deepseek.json"
    if not sidecar.exists():
        print(f"[ERROR] sidecar not found: {sidecar}\n"
              f"        run _bq_582_probe_notes_deepseek.py --batch {args.batch} first.")
        return 2
    entries = json.loads(sidecar.read_text(encoding="utf-8"))

    # Validate the whole batch BEFORE touching the DB (fail loud, write nothing).
    for e in entries:
        _validate(e["probe_notes"], e["question_id"])
    print(f"[seed] batch {args.batch}: {len(entries)} entries validated OK.")

    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    # probe_notes_updated_at uses the DB's own clock (sqlite CURRENT_TIMESTAMP).

    backed_up = False
    n_write = n_skip = 0
    for e in entries:
        qid = e["question_id"]
        new_json = _canonical(e["probe_notes"])
        row = conn.execute(
            "SELECT probe_notes FROM behavioral_questions WHERE question_id=?", (qid,)
        ).fetchone()
        if row is None:
            print(f"  [WARN] {qid}: no such question row -- skipped")
            continue
        if (row["probe_notes"] or "") == new_json:
            print(f"  [SKIP] {qid}: probe_notes unchanged")
            n_skip += 1
            continue
        if not backed_up:
            BACKUP_DIR.mkdir(parents=True, exist_ok=True)
            stamp = conn.execute("SELECT strftime('%Y%m%d_%H%M%S','now','localtime')").fetchone()[0]
            bak = BACKUP_DIR / f"mle_prep_pre_T-P1-582_b{args.batch}_{stamp}.db"
            shutil.copy2(DB_PATH, bak)
            print(f"  [backup] {bak}")
            backed_up = True
        conn.execute(
            "UPDATE behavioral_questions SET probe_notes=?, "
            "probe_notes_updated_at=CURRENT_TIMESTAMP WHERE question_id=?",
            (new_json, qid),
        )
        print(f"  [WRITE] {qid}: probe_notes set ({len(new_json)} chars)")
        n_write += 1
    conn.commit()
    conn.close()
    print(f"[seed] batch {args.batch} done: {n_write} written, {n_skip} skipped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
