"""Translate Google R1 drill docs to Chinese -- Batch 3 (docs 65/68/69).

Per T-P1-475 [KG-G-01]. Idempotent: if the sentinel
`<!-- CN_TRANSLATED_20260416 -->` already appears in the target doc content,
the seeder prints [UNCHANGED] for that doc and skips.

Translation rules (project memory feedback_lc_notes_chinese):
- Chinese prose throughout
- Keep English: algorithm names (MMR / DPP / MGDA / PCGrad / PSI / KL / JS / KS /
  MMD / NDCG / OOF / GroupKFold / AS-OF / PIT), complexity notation (O(k|C|)),
  paper citations (Chen 2018 / Gong 2014 / Kendall 2018 / Endres-Schindelin 2003 /
  Saerens EM / BBSE), variable names (L_S, d_i, phi_i, q_i, p, q, n_c)
- Glossary terms: first-use bold English with Chinese in parentheses, e.g.
  **Intent Collapse (意图塌缩)**
- Math via $...$ inline and $$...$$ display (unchanged)
- Tables: header rows kept in English; prose cells translated to Chinese
"""
from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent.parent / "data" / "mle_prep.db"
SENTINEL = "<!-- CN_TRANSLATED_20260416 -->"


# -------------------------------------------------------------------------
# Doc 65 -- Multi-Objective Ranking: DPP / MMR + Etsy Diversity Playbook
# -------------------------------------------------------------------------
DOC_65 = """<!-- Generated by StudyNoteBuilder -->
""" + SENTINEL + """

# Multi-Objective Ranking -- DPP / MMR + Etsy Diversity (Google R1 Prep)

## Prerequisites

- 标量化多任务排序损失：$L = \\sum_k w_k L_k$
- Uncertainty Weighting (Kendall 2018) 与 GradNorm (Chen 2018) 的方程级细节
- Pareto 优化 / MGDA / PCGrad 的概念级认识
- Embedding 空间中的 cosine 相似度与点积打分
- Two-tower 召回 + cross-encoder 精排流水线

## Key Terms

- **MMR (Maximal Marginal Relevance，最大边际相关性)**：贪心逐槽选择——每一槽挑使 $\\lambda \\cdot \\text{rel}$ 减 $(1-\\lambda) \\cdot \\max \\text{sim}$ 最大化的候选
- **DPP (Determinantal Point Process，行列式点过程)**：子集上的概率模型，$P(S) \\propto \\det(L_S)$；对角编码质量、非对角编码相似度，行列式同时打分相关性与多样性
- **MTL (Multi-Task Learning，多任务学习)**：共享参数模型针对多个损失头（click / purchase / dwell）联合训练；与 slate 级多样性（一个 SERVING-TIME 问题）是两条解耦的轴
- **Intent Collapse (意图塌缩失败模式)**：标量化排序器把单一主流意图（如 GMB 高价卖家）塞满整个 slate；少数意图用户看不到任何相关物品，尽管平均 NDCG 看着很健康
- **Allocation Primitive (槽位预算分配原语)**：平台级机制，给每个模块 / 意图 / 业务规则保留固定槽位份额，用模块仲裁替代标量权重的相互拉扯
- **GMB (Gross Merchandise Bookings，总商品交易额)**：Etsy 的电商北极星指标；围绕 GMB 调出价的精排是经典意图塌缩陷阱，因为高 GMB 卖家会淹没 slate
- **MGDA (Multiple Gradient Descent Algorithm，多重梯度下降算法)**：Pareto 优化方法，找到对所有任务损失都非递增的梯度方向；与 slate 多样性正交——MGDA 平衡**训练**，DPP/MMR 平衡**服务**

## 0. Framing -- 多样性在多目标栈里的位置

Staging-5 与 DoorDash 多目标 drill 覆盖了标量化（$L = \\sum w_k L_k$）、**Uncertainty Weighting**、**GradNorm**、**MGDA**。这些都属于**训练时**工具：决定多个损失项如何分享梯度更新。面向排序岗（Etsy / Pinterest / DoorDash / YouTube Home）的 Google R1 压着的是另一条这些工具不覆盖的轴：**最终 slate 的组成**。即使训练损失已经完美平衡，贪心 top-K 排序仍可能返回 9 个几乎重复的卖家加 1 个离群值的 slate。

本 drill 覆盖这类对话里必然出现的四个问题：(1) **MMR** 闭式与它为何是业界默认；(2) **DPP** 行列式与它虽然数学更干净却大多不上线的原因；(3) **Intent Collapse** 失败模式与为何修复手段是槽位级 **Allocation Primitive** 而不是再加一个标量权重；(4) 为何 **DPP/MMR** 与 **MTL** 损失平衡是正交的——生产栈里**必须同时存在**。

**口述捷径**："MTL 平衡 LOSS，多样性平衡 SLATE。两者跑在不同层——训练 vs 精排服务——所以可以叠加。MMR 是带单一标量旋钮的业界默认，DPP 是更干净的数学；**intent collapse** 是标量化解不掉的失败模式，所以平台才上 slot budget。"

## 1. MMR -- 业界主力（单旋钮、贪心、$O(k|C|)$）

**MMR** 是**贪心精排**。给定来自 L2 heavy rank 的 candidate 集合 $C$（通常是 top-200）与目标 slate 长度 $k$（通常是 20），迭代挑选使以下量最大化的候选：

MMR 对候选 $d_i$ 的打分（已选集合 $S$）；$\\lambda$ 是唯一可调旋钮（相关性 vs 排斥强度）：

$$\\mathrm{MMR}(d_i) = \\lambda \\cdot \\mathrm{rel}(d_i, q) - (1 - \\lambda) \\cdot \\max_{d_j \\in S} \\mathrm{sim}(d_i, d_j)$$

其中 $\\mathrm{rel}(d, q)$ 是 L2 打分（或任何标量化效用），$\\mathrm{sim}(d_i, d_j)$ 是 embedding 空间中的 cosine 相似度（PinSage、item2vec、topic one-hot 交集——空间的选择本身是一个系统设计决策）。各项含义：

- **$\\lambda = 1$**：纯相关性，无多样性——等价于 `argsort(rel)[:k]`。产出重复严重的 slate。

- **$\\lambda = 0$**：纯排斥——挑与已选最不同的候选，完全忽略 query。产出看起来随机的 slate。

- **$\\lambda \\approx 0.7$**：feed 排序论文与 DoorDash / Pinterest 精排的业界默认。按 surface 做 A/B 微调。

**复杂度**：槽位 $t$ 下，在 $|C| - t$ 个候选里挑，每个需要与 $t$ 个已选做相似度比较。总计 $O(k \\cdot |C|)$ 次相似度查询——如果 sim 是预缓存或低维点积，微秒级别。这也是为什么 MMR 能塞进 15ms 的精排预算，而 **DPP** 推理塞不进。

**为何 MMR 上线、DPP 通常不上线**：

- 延迟：$O(k \\cdot |C|)$ vs DPP 的 $O(k \\cdot |C|^2)$ 或 greedy-MAP 的 $O(k^2 \\cdot |C|)$。

- 可解释性：`lambda` 是一个数字；PM 可以调；A/B 测试是一维的。

- 确定性：给定候选顺序，贪心 MMR 天然可复现；DPP 的随机采样难以调试与重放。

- 特征可插拔：MMR 的 sim 接受任何相似度函数——topic Jaccard、cosine、甚至学出来的 pairwise penalty 头。DPP 的核矩阵 $L$ 必须 PSD（半正定），这排除了若干自然选择。

**面试者会深挖的实战坑**：

- **尺度失配**：BCE logit 出的 rel 与 $[0, 1]$ 区间的 sim。如果 rel 无界而 sim 有界，有效 $\\lambda$ 会坍缩到 1。修法：每请求对 rel 做 min-max 归一化，或让 rel 过 sigmoid。

- **相似度空间选错 = 失败模式泄露**：如果 sim 用标题文本的 cosine，排序器多样化了标题但没多样化卖家；**GMB** 重度账户照样霸屏。要用**复合相似度**：$\\max(\\text{title\\_cos},\\ \\text{seller\\_id\\_one\\_hot},\\ \\text{category\\_match})$。

- **业务规则次序**：MMR 之后通常跟广告插入、policy 去重、freshness boost。顺序至关重要——如果广告在 MMR 之后插入，就会吃掉你刚挣来的多样性槽位。标准次序：`rank -> MMR -> rules`。

**口述捷径**："$O(k|C|)$ 贪心配单 $\\lambda$ 旋钮，sim 必须又便宜又有表达力。离线 NDCG vs slate entropy 上调 $\\lambda \\approx 0.7$，之后 A/B 验证一对。业界上 MMR 而不上 DPP，是因为延迟和 PM 可调性。"

## 2. DPP -- 一个行列式同时编码相关性与排斥

**DPP** 把概率赋在候选集合的每一个子集 $S$ 上，正比于一个矩阵的行列式：

$L$ 是 $N \\times N$ DPP 核：对角是单品质量的平方，非对角是质量加权的 embedding 相似度。一个行列式同时编码两者：

$$P(S) \\propto \\det(L_S), \\quad L_{ii} = q_i^2, \\quad L_{ij} = q_i \\cdot \\phi_i^\\top \\phi_j \\cdot q_j$$

关键技巧：$\\det(L_S) = \\prod \\lambda_i$（$L_S$ 的特征值之积），近似重复的物品会让某个特征值逼近 0，从而行列式逼近 0。具体地：

- 对角 $L_{ii}$ 是**相关性**：高质量单品 -> 大对角元 -> 更大行列式。

- 非对角 $L_{ij}$ 是**相似度**：两个相似单品 -> 大非对角元 -> 矩阵近奇异 -> 小行列式。

- 所以在 $|S| = k$ 约束下的 MAP 推理 $\\arg\\max_S \\det(L_S)$ 会同时挑高质量**且**多样的单品——**没有 $\\lambda$ 旋钮**。这正是 DPP 相对 MMR 的卖点。

**MAP 推理 NP-hard**；标准近似是 **greedy MAP** (Chen et al. 2018, Gong et al. 2014)：

Greedy MAP：每步挑使 $\\log \\det$ 增幅最大的候选。配 Cholesky update trick 后复杂度 $O(k^2 |C|)$：

$$d^* = \\arg\\max_{d_i \\in C \\setminus S} \\log \\det(L_{S \\cup \\{d_i\\}}) - \\log \\det(L_S)$$

由于 $\\det$ 在 $S$ 上是子模的（PSD 核的标准结果），贪心 MAP 对真最优具有 $(1 - 1/e)$ 近似保证——与子模最大化的贪心界一致。

**为何 DPP 数学上比 MMR 更诚实**：

- MMR 的 `max sim` 惩罚只看已选中最近的那一个；DPP 通过行列式把整个子集联合考虑。$k = 20$ 时，从第 5 个单品起就能吃到全谱视角的红利。

- DPP 天然跨簇扩展：候选集有 3 个质量接近的意图时，DPP 会把 slate 分散到 3 个意图上；MMR 在 $\\lambda$ 调得非常激进之前仍可能堆到最高相关性的那一个意图上。

- 质量与多样性**不是**两个目标加权混合——它们是同一个矩阵两种参数化的方式。这就是"数学更干净"的说法。

**为何 DPP 实际上很少上线（面试官会问）**：

- **Kernel 设计是承重墙**：必须选 $\\phi$ 与质量 $q_i$。线上团队有多个噪声重的质量头（CTR / CVR / dwell）和多个自然的相似度空间；没有明显的单一 kernel。

- **延迟**：即使 greedy MAP 的 $O(k^2 |C|)$ + Cholesky 分解，在 $k = 20,\\ |C| = 200$ 下也是 MMR 的 5-20 倍。多数 feed surface 在 15ms 精排预算里吃不下。

- **可解释性与 A/B 测试维度**：调 DPP 意味着重学 kernel，而不是动一个旋钮。PM 讨厌这点。

- **随机推理**：用 k-DPP 采样做探索时，相同输入两次调用可能返回不同 slate——审计困难。

- **DPP 真的上线的地方**：邮件摘要（延迟预算以秒计，rerun 稀少）、YouTube related-videos 研究原型、学术 benchmark。Airbnb 2021 年那篇 "diversity via DPP" 是业界典型引文，但部署是**离线**精排，不是在线服务。

**口述捷径**："$\\det(L_S)$——对角 = 质量的平方，非对角 = 质量加权相似度。一个矩阵，两种意义。Greedy MAP $O(k^2 |C|)$，带 $(1 - 1/e)$ 保证。生产上仍是 MMR，因为 DPP 的 kernel 设计与延迟都比单旋钮贪心差。"

## 3. Intent Collapse -- 为何平台用 Allocation 替代标量化

无论是 **MMR** 还是 **DPP**，只要 **Intent Collapse** 咬得够深，都解决不了这个问题。Intent collapse 是指标量化效用分系统性地饿死整类用户意图，它也是 Google R1 真正在意的多样性问题。

**具体失败**（Etsy GMB 精排，2019-2021 时期）：生产精排器训练目标是预测点击加权 GMB。它学到的是"好照片、多评论的高价卖家"最大化每次曝光的期望 GMB。喂给 MMR 的 top-200 candidate 已经被这类卖家塞满；MMR 的 sim 惩罚多样化了**图片**（不同商品照），但底层的卖家集中度保持不变。带**少数意图**（"20 刀以内的礼物"、"复古专卖"、"独立艺术家"）到访的用户看不到任何相关物品，CTR 静默下滑。聚合 NDCG 看着没问题——主流意图依然被服务得好——但长尾留存在几个月的尺度上退化。

**为何标量权重修不了**：问题不在于某个损失权重调偏了。任何 $w_\\text{click} L_\\text{click} + w_\\text{GMB} L_\\text{GMB} + w_\\text{relevance} L_\\text{relevance}$ 的组合都只是训练一个单一效用函数。少数意图在训练数据里支持度很小，因此对任何损失项的贡献都小。把 $w_\\text{relevance}$ 调大也没用，因为"相关性"本身就是**多数派对齐**的——模型没有"这个用户意图很小众"这条通道。即使 **Uncertainty Weighting** 与 **GradNorm** 也修不了；它们平衡任务，但仍然对每个 $(q, d)$ 只输出一个标量。

**生产修复 = Allocation Primitive**。平台不再只有一个标量化排序器，而是把 slate 拆成**模块槽位**，每个模块负责一种意图或一种业务目标，**槽位预算**决定每个模块拥有多少槽位。模块仲裁用简单规则决定每槽赢家（例如："广告拿槽位 3 和 7；new-seller-boost 拿 1 槽；当 query 带预算意图时 budget-intent 模块最多拿 2 槽；剩余 slate 归基础排序器"）。

**Allocation primitive**：slate 是各模块 top-K 的并集，每个模块对 query $q$ 产出至多 $\\text{budget}(m, q)$ 个槽位，通过固定仲裁策略合并：

$$\\text{slate} = \\bigcup_{m \\in \\mathcal{M}} \\mathrm{topK}_m\\bigl(c_m \\cdot \\mathrm{budget}(m, q)\\bigr)$$

**为何它结构上优于标量化**：

- **少数意图拿到保留地**：预算不是在损失函数里与多数派信号抢，而是预先**保留**好的。

- **模块问责**：每个模块有自己的损失、团队、A/B 测试。单模块回归不会污染整个 slate。

- **业务规则成为一等公民**：广告插入、cold-start boost、policy 槽位与 ML 模块是同一原语，不再是补丁。

- **与 DPP/MMR 组合而非替代**：模块内部多个单品时，MMR 照样在模块内多样化。

**平台例子**：

- Facebook News Feed 的 "mixer" 层在帖子、故事、广告、群组之间仲裁。

- YouTube Home 的短视频、长视频、Live、订阅的槽位预算。

- Pinterest Home 的 "candidate sources" 模式：Board-Follow、Interest、Topic、Search-interest 是独立模块，各有 quota。

- DoorDash Home：`for you` / `new on DoorDash` / `value` / `cuisines` carousel 是模块槽位——标量排序器在 carousel 内运行，而**不是跨 carousel**。

- Etsy 2022 年之后的多样性改造：显式卖家多样性预算、少数意图管道、MMR 只在模块内运行。

**口述捷径**："标量化无法解决少数意图饥饿——信号在损失里太小。平台修法是 ALLOCATION PRIMITIVE：模块槽位预算 + 仲裁，MMR/DPP 在**模块内**跑。这是 senior 排序面试想听到的术语。"

## 4. 与 Uncertainty Weighting / GradNorm / Pareto 的正交性

Google R1 里承重的一个考察点：候选人把训练时 MTL 平衡与服务时 slate 多样性混为一谈。两者是**正交轴**，生产栈**同时应用**。

**Training-time MTL vs Serving-time Slate Diversity (正交轴)**

| Axis | Training-time MTL balancing | Serving-time slate diversity |
| --- | --- | --- |
| Tools | Scalarization, Uncertainty Weighting, GradNorm, **MGDA**, PCGrad | MMR, DPP, allocation primitive, slot budgets |
| What it balances | 不同 LOSS 头（click / purchase / dwell）的梯度贡献 | 展示给用户的最终 SLATE 组成（单品多样性、意图覆盖） |
| Layer | 训练期的共享参数 tower | 服务路径上的 post-ranker 精排 |
| Per-request cost | 服务时为 0（权重已经 bake 进模型） | 精排延迟占主导（$k = 20$, $\\|C\\| = 200$ 下 ~1-15ms） |
| Failure mode it fixes | 损失尺度不平衡、单任务梯度主导 | slate 重复、intent collapse、位置偏差型近似重复 |
| Failure mode it does NOT fix | slate 级重复、少数意图覆盖 | 训练期不同头之间的梯度冲突 |
| A/B test surface | 离线 NDCG / ROC-AUC，很少在线可见为多样性 | slate entropy、intent coverage@k、长尾留存 |


## 4.1 标准生产栈的组合方式

完整栈长这样：

1. **训练**：共享 MMoE tower 带 $K$ 个头（click / purchase / dwell / hide）。损失先由 **Uncertainty Weighting** 在初始化时平衡，然后由 **GradNorm** 在训练中动态平衡。离线 Pareto sweep 选定上线标量权重。

2. **推理**：单次前向输出每个 $(q, d)$ 的 $K$ 个分数。固定线性组合 $\\text{utility} = \\sum_k w_k \\cdot \\text{score}_k$ 合成标量相关性。

3. **召回 -> L1 -> L2 heavy rank**：按 `utility` 产出 top-200。

4. **Slate 多样性**：Allocation primitive 在 20 槽间分配模块；每个模块内，MMR 基于 utility + 复合相似度（title / seller / category）精排。

5. **业务规则**：广告插入、policy 过滤、freshness boost 放到**最后**，以免吃掉多样性槽位。

每个阶段都有自己的 A/B surface。任何单阶段回归都应该能从该阶段指标捕获。

**面试官会下的陷阱**："那你在 MTL 训练里加一个多样性损失项不就行了吗，serving 就不需要 MMR 了。" 答案：**不行**——per-item 损失里的多样性项**没有 slate 上下文**。Slate 级指标（slate 内两两 cosine 之和、意图覆盖）是**不可分解**的。你**可以**在 slate 级 reward 上端到端训练精排（listwise RL，比如 SlateQ），但你**不能**用 pointwise 损失替代 slate 级机制。

**口述捷径**："MTL 在训练期平衡 LOSS GRADIENTS。DPP/MMR/allocation 在服务期平衡 SLATE COMPOSITION。不同层、不同指标、不同 owner。生产栈三件同时上：训练用 Uncertainty Weighting + GradNorm，服务用 allocation + MMR。"

## 5. Etsy GMB 多样性战况 -- 两旋钮修复

Google R1 会问："给我一个你见过或研究过的具体多样性陷阱。" 标准答案：**Etsy GMB-bidding reranker, 2019-2021**。

**场景**：Etsy 生产精排器预测每个 listing 的点击加权 **GMB** 贡献。模型校准良好（温度缩放）、MTL 由 Uncertainty Weighting 平衡、用每会话 GMV 做 A/B。MMR 用 title cosine 多样化，$\\lambda \\approx 0.6$。

**症状**：每次 A/B 聚合 GMV-per-session 都持平或上升，但季度尾部卖家留存下降，长尾回访用户 CTR 下滑。事后分析发现：top 1% 卖家占据了精排 slate 40%+ 的曝光；少数意图（"15 刀以内礼物"、"复古"、"personalized"）被喂的是通用 top-tier 卖家的 listing，而不是意图匹配的少数派卖家 listing。

**为何 MMR 漏掉了这个**：title-cosine 相似度空间里的 intra-slate 熵很高（商品不同），但卖家熵很低（同一批店铺）。MMR 多样化的是表面信号，不是潜在的集中度。

**修复（两旋钮）**：

1. **复合相似度**：$\\text{sim}(d_i, d_j) = \\max(\\text{title\\_cos},\\ \\mathbb{1}[\\text{seller\\_id}_i = \\text{seller\\_id}_j],\\ \\mathbb{1}[\\text{category}_i = \\text{category}_j])$。直接压制了 MMR 内部的同卖家抱团。

2. **Allocation primitive**：从 20 槽中保留 2-4 槽给 "minority-intent" 与 "long-tail-seller" 模块，各用**自己的排序器**，不与 GMB 竞争。模块预算按 query-intent 类别调（budget / vintage / personalized）。

**结果**：聚合 GMV 在 A/B 里持平（两个模块挤掉的是高 GMB 但非高毛利的 listing），但卖家多样性指标（Gini、top 1% 占比）明显下降，90 天回访用户在少数意图上的 CTR 上升 5-8%。这就是 Google R1 想听到的修复形状：不是"我们调了 $\\lambda$"，而是"我们**改了相似度空间**并**加了槽位预算**"。

**其他平台的变体陷阱**：

- **Pinterest 创作者集中**：同模式，只是对象从卖家换成创作者；修法是对 `creator_id` 加 MMR 惩罚 + 创作者 freshness 槽位。

- **DoorDash 商家集中在 `For You` carousel**：top-20 商家霸屏；修法是每商家上限（每 slate 每商家最多 2 槽）。

- **YouTube 上传者集中在 Home**：每 channel 槽位预算 + 排序器里的多样性损失项（这是少数几个多样性**损失**项有效的场景——因为 slate 够大，slate 级 A/B 也成熟）。

**口述捷径**："Etsy 2020：GMB 精排 -> 卖家塌缩。MMR 多样化了标题不是卖家，因为**相似度空间选错**。修法是复合相似度（title 或 seller 或 category）**加**槽位预算给少数意图。这就是 senior-diff：知道**哪个旋钮错了**、**为何标量化抓不到**。"

## 6. 数值量级自检 -- 面试官期待的规模

系统设计口试里常见的具体数值：

- **候选集大小** $|C|$（L2 heavy rank 输出）：100-500 典型，200 是默认。

- **Slate 大小** $k$：home feed 20-25，邮件摘要 10，搜索结果 10-50。

- **MMR 延迟预算**：在 $k = 20,\\ |C| = 200$ 且 sim 是缓存好的 cosine 时约 1-2ms。DPP greedy-MAP 在同尺度下 10-20ms。这 5-10 倍的差距就是 MMR 上线的原因。

- **$\\lambda$ 调参区间**：0.5 到 0.8 覆盖 95% 的线上部署。起点 0.7，A/B $\\pm 0.1$。

- **Allocation 预算**：典型 home feed 给非基础排序器的模块保留 15-25%（广告 10-15%、cold start 2-5%、少数意图 5-10%）。基础排序器保 75-85%。

- **Slate entropy 目标**：运营指标是类别分布的 Shannon entropy。Home feed 在 $k = 20$ 时目标 $\\ge 2.5$ nats（约等价于 12 个大致均衡的类别）。

- **卖家集中的 Gini**：修复前 Etsy top-100 曝光 Gini $\\approx 0.85$；修复后目标 $\\le 0.6$。0.9+ 是常见告警阈值。

- **DPP kernel 维度**：$\\phi$ 维度 32-64 典型；超过 128 会把延迟打爆，因为 Cholesky 是 $O(k^2 d)$。

### 2-Minute Oral Self-Check

- [ ] MMR 闭式：$\\lambda \\cdot \\text{rel} - (1 - \\lambda) \\cdot \\max \\text{sim}$，贪心 $O(k|C|)$
- [ ] $\\lambda$ 旋钮：0 = 纯排斥、1 = 纯相关性、默认 ~0.7
- [ ] DPP：$P(S) \\propto \\det(L_S)$；对角 = 质量平方、非对角 = 相似度
- [ ] Greedy MAP 是 $O(k^2 |C|)$、子模、$(1 - 1/e)$ 近似
- [ ] MMR 上线而非 DPP：延迟、PM 可调性、相似度灵活性
- [ ] Intent collapse：标量化饿死少数意图，权重怎么调都不行
- [ ] 修法 = allocation primitive（槽位预算 + 模块仲裁）
- [ ] MTL 在训练期平衡 LOSS；DPP/MMR 在服务期平衡 SLATE——正交
- [ ] 生产栈**两件一起上**（Uncertainty + GradNorm + allocation + MMR）
- [ ] Etsy 2020 GMB 战况：复合相似度 + 槽位预算，不是只调 $\\lambda$
- [ ] pointwise ranker 里的 slate 级多样性损失项**不能替代** MMR
"""


# -------------------------------------------------------------------------
# Doc 68 -- Feature Drift Drill: PSI / KL / JS / KS
# -------------------------------------------------------------------------
DOC_68 = """<!-- Generated by StudyNoteBuilder -->
""" + SENTINEL + """

# Feature Drift Drill -- PSI / KL / JS / KS + Concept vs Covariate Shift

## Prerequisites

- 概率分布、期望、对数似然
- 经验 CDF 与顺序统计量
- 假设检验：零分布、p 值、临界值
- 训练-服务 skew 与特征流水线在生产 ML 中的角色

## Key Terms

- **PSI (Population Stability Index，总体稳定性指数)**：分桶分布漂移分数；0.1 告警、0.25 严重；在信贷 / 广告广泛使用
- **KL (Kullback-Leibler divergence，KL 散度)**：非对称、无界，衡量 $q$ 相对参考 $p$ 的信息增益
- **JS (Jensen-Shannon divergence，JS 散度)**：在中点分布 $m = (p + q) / 2$ 周围对 KL 做对称、有界的平滑
- **KS (Kolmogorov-Smirnov test，KS 检验)**：两条经验 CDF 之间的最大垂直间隙；连续、非参、无需分桶
- **ICC (Intra-Cluster Correlation，组内相关)**：簇可解释的总方差比例；忽略它会导致 SE 被低估

## 0. Why Drift Monitoring Matters (The Framing)

生产 ML 静默退化。用 Q1 数据训练、到 Q4 还在服务的模型，会因用户行为、上游特征流水线、标注惯例三者同时漂移而掉 AUC。Drift 监控就是在业务指标被打之前的**早期预警层**。

三种不同的 shift，各有不同的修法：

- **Covariate shift**：$P(x)$ 变了，$P(y \\mid x)$ 稳定 -> 训练集重加权或重采样，**不需要重新标注**。

- **Concept drift**：$P(y \\mid x)$ 变了，$P(x)$ 可能变也可能不变 -> **必须**拿新标签重训；重加权**帮不了**。

- **Label / prior shift**：$P(y)$ 变了，$P(x \\mid y)$ 稳定 -> 重校准输出概率（Saerens / BBSE）。

心里的检查顺序：(1) 每个特征每日算 **PSI**；(2) 在 0.1 / 0.25 阈值告警；(3) 连续特征用 **KS**；(4) 多维分布用 **KL** 或 **JS**；(5) 在决定重训之前**先归因**到 shift 类型（covariate vs concept vs label）。

**口述捷径**："PSI 是每日主力。KL / JS 在你需要信息论框架时用。KS 处理连续且无需分桶。Covariate shift = 输入动了，concept drift = 输入-输出关系动了。永远要按**每个特征、每个 segment** 告警，绝不仅看聚合。"

## 1. PSI -- 分桶漂移主力

PSI 比较**相同桶边界**下的两条分布：参考（训练）分布 `e` 与当前（服务）分布 `a`，分别表示为和为 1 的比例。

分桶漂移分数，$K$ 桶，参考 $e_i$、实际 $a_i$：

$$\\mathrm{PSI} = \\sum_{i=1}^{K} (a_i - e_i) \\cdot \\ln\\!\\left(\\frac{a_i}{e_i}\\right)$$

每桶贡献 $(a_i - e_i) \\cdot \\ln(a_i / e_i)$。贡献的符号**永远非负**，因为 $(a - e)$ 与 $\\ln(a / e)$ 同号（$a > e$ 时都正，$a < e$ 时都负）。PSI 因此是类似距离的量，但**不是严格意义的度量**。

业界标准阈值（起源于信贷评分，广告 / 搜索排序广泛沿用）：

- PSI $< 0.1$：无显著漂移，继续监控

- $0.1 \\le$ PSI $< 0.25$：中等漂移，调查并考虑重训

- PSI $\\ge 0.25$：显著漂移，模型很可能退化，重训

**桶数敏感性**：用在**参考期**上算出的等频分桶（典型 10 桶）。把桶边界钉死在参考集是关键——如果每天用当前数据重新分桶，锚就丢了，分数会 trivially 漂移。另外空桶要 clip 到小 $\\varepsilon$（例如 $10^{-4}$），避免 $\\ln(0)$ 爆炸。

数值锚点：设参考 $e = [0.2, 0.3, 0.3, 0.2]$，实际 $a = [0.1, 0.2, 0.4, 0.3]$。
$\\text{Contribution}_1 = (0.1 - 0.2) \\cdot \\ln(0.1 / 0.2) = -0.1 \\cdot (-0.693) = 0.0693$。
$\\text{Contribution}_2 = (0.2 - 0.3) \\cdot \\ln(0.2 / 0.3) = -0.1 \\cdot (-0.405) = 0.0405$。
$\\text{Contribution}_3 = (0.4 - 0.3) \\cdot \\ln(0.4 / 0.3) = 0.1 \\cdot 0.288 = 0.0288$。
$\\text{Contribution}_4 = (0.3 - 0.2) \\cdot \\ln(0.3 / 0.2) = 0.1 \\cdot 0.405 = 0.0405$。
$\\text{PSI} = 0.0693 + 0.0405 + 0.0288 + 0.0405 = 0.179$——落在 WARN 区间。

**口述捷径**："PSI = $\\sum (a - e) \\ln(a / e)$。0.1 告警、0.25 严重。**等频分桶钉死在参考期**，$\\varepsilon$-clip 零桶，按**每个特征**告警。对 $a / e$ 互换对称，因为两个因子同时变号。"

## 2. KL vs JS -- 信息论视角的分布距离

KL 散度衡量使用为 $q$ 优化的编码去编码来自 $p$ 的样本所需的**额外比特数期望**。它是 PSI 的信息论近亲（PSI $\\approx$ 分桶分布上的对称化 KL）：

KL 散度（期望在 $p$ 下取）：

$$D_{\\mathrm{KL}}(p \\,\\|\\, q) = \\sum_{x} p(x) \\cdot \\ln\\!\\left(\\frac{p(x)}{q(x)}\\right)$$

KL 的关键性质：

- **非对称**：$D_{\\mathrm{KL}}(p \\,\\|\\, q) \\ne D_{\\mathrm{KL}}(q \\,\\|\\, p)$。方向有含义——`p || q` 读作 "用 $q$ 做 $p$ 的编码有多浪费"。

- **无界**：若 $q(x) = 0$ 而 $p(x) > 0$，KL 爆到无穷。任何分母零都让 KL 无定义。实用 workaround：加 $\\varepsilon$ 平滑，但这会掩盖确切的病态。

- **非度量**：不满足三角不等式。

JS 散度通过中点 $m = (p + q) / 2$ 把 KL 对称化：

JS 散度：两个分布到中点的 KL 的均值：

$$D_{\\mathrm{JS}}(p, q) = \\tfrac{1}{2} D_{\\mathrm{KL}}(p \\,\\|\\, m) + \\tfrac{1}{2} D_{\\mathrm{KL}}(q \\,\\|\\, m), \\quad m = \\tfrac{1}{2}(p + q)$$

JS 的关键性质：

- **对称**：$D_{\\mathrm{JS}}(p, q) = D_{\\mathrm{JS}}(q, p)$，by construction。

- **有界**：nats 下 $0 \\le D_{\\mathrm{JS}} \\le \\ln 2$（bits 下 $\\le 1$）。**有界**这一点让 JS 适合用于告警阈值；KL 需要 log 轴才看得清。

- **$\\sqrt{D_{\\mathrm{JS}}}$ 是度量**：满足三角不等式 (Endres-Schindelin 2003)，这对聚类漂移指纹很重要。

线上何时用哪一个：

- 每日单特征 dashboard 用 **PSI**（阈值历史沉淀、分级容易）

- 存在自然参考 / 目标方向的场景（例如模型预测 vs 真实标签分布）用 **KL**

- 跨多个时间窗口做告警、尤其是文本 / embedding 分布时用 **JS**（需要对称、有界分数）

**口述捷径**："KL 非对称、无界、在零支撑上爆炸；JS 对称、界在 $\\ln 2$，$\\sqrt{\\text{JS}}$ 是度量。PSI 是对称化 KL 的分桶近亲，带固定阈值。按**你需要方向（KL）、需要度量（JS）还是需要标准化阈值（PSI）**来选。"

## 3. KS Test -- 不分桶的连续特征

分桶一个连续特征会扔掉信息，也让 PSI 对分桶网格敏感。Kolmogorov-Smirnov 检验通过比较**经验 CDF** 完全绕过分桶：

KS 统计量：两个样本经验 CDF 之间的最大垂直间隙：

$$D_{\\mathrm{KS}} = \\sup_{x} \\bigl|F_1(x) - F_2(x)\\bigr|$$

在零假设（同分布）下，放缩后的统计量有已知分布（Kolmogorov 分布）。对尺寸为 $n_1, n_2$ 的两个样本，在水平 $\\alpha$ 上拒绝 $H_0$ 的条件：

两样本 KS 在 $\\alpha = 0.05$ 下的经典 1.36 常数：

$$D_{\\mathrm{KS}} > c(\\alpha) \\cdot \\sqrt{\\frac{n_1 + n_2}{n_1 \\cdot n_2}}, \\quad c(0.05) \\approx 1.36$$

性质：

- **非参**：除连续性外不假设分布形式

- **无分桶**：直接使用顺序统计量

- **对中位数附近最敏感**：CDF 间隙在密度最大处被放大。对罕见事件的尾部漂移欠敏。尾部漂移要用 Anderson-Darling 或按分位切分后对每段跑 KS。

实战坑：

- 互联网尺度 $n \\gg 10^6$ 时 KS 过度敏感——表面上极小的漂移都会拒绝 $H_0$。要么改用 **effect-size 阈值**（例如 $D > 0.05$）替代 p 值，要么下采样到固定参考尺寸。

- KS 是**单变量**检验。多变量漂移用每特征 KS 加 **MMD (Maximum Mean Discrepancy，最大均值差异)**，或训一个 domain classifier（训一个二分类器区分参考 vs 当前；AUC $> 0.6$ 即漂移信号）。

**口述捷径**："KS = 两条经验 CDF 的 sup 间隙。无分桶、非参、每特征一个数字。$\\alpha = 0.05$ 时临界约 $1.36 \\cdot \\sqrt{(n_1 + n_2) / (n_1 n_2)}$。尾部弱；尾部重要时换 AD 或按分位切分。"

## 4. Concept Drift vs Covariate Shift vs Label Shift

漂移类型决定修法。**搞错类型会浪费几周**：concept drift 却在用旧标签重训，或者 covariate shift 却在重校准。

把联合分布分解成两种因式化，各自隔离一种 shift：

联合分布的两种分解，分别隔离一种 shift：

$$P(x, y) = P(y \\mid x) \\cdot P(x) = P(x \\mid y) \\cdot P(y)$$

- **Covariate shift**：$P(x)$ 变了，$P(y \\mid x)$ 稳定。经典例子：进入新市场后用户画像变了，但输入到标签的关系没变。修法：重要性重加权 $w(x) = P_\\text{target}(x) / P_\\text{source}(x)$，或重采样训练数据匹配新 $P(x)$。**不需要新标签**。

- **Concept drift**：$P(y \\mid x)$ 变了，$P(x)$ 可能变也可能不变。经典例子：垃圾邮件过滤器——对抗者适应后，同样的输入特征对应到不同的标签。修法：**重新标注**并重训。对**同一**批标签做重加权只会让事情更糟，因为标签本身已经过时。

- **Label / prior shift**：$P(y)$ 变了，$P(x \\mid y)$ 稳定。经典例子：不同医院的疾病流行率不同，但症状到疾病的生成模型稳定。修法：用 **Saerens-Latinne-Decaestecker EM** 或 **BBSE (black-box shift estimation)** 重校准。如果模型是概率型的，**不用重训**。

诊断流程：

- **Step 1**：$P(x)$ 在漂移吗？每特征跑 PSI / KS。

- **Step 2**：$P(y)$ 在漂移吗？比较近期标签分布与训练期（前提是有标签——通常延迟到达）。

- **Step 3**：$P(y \\mid x)$ 在漂移吗？在一个新鲜小样本标注切片上对比模型准确率。如果**准确率下降但 $P(x)$ 没动**，那就是 concept drift。

**经典陷阱**：看到 $P(x)$ 漂移 -> 假设 covariate shift -> 重加权。线上指标没回升。真因其实是 concept drift 碰巧与 covariate shift 同时发生。**总是先查标签（step 3）**，再把锅甩给 $P(x)$ 单独。

重要性重加权恒等式：**仅在 covariate shift 下成立**，concept drift 下不成立：

$$w(x) = \\frac{P_{\\text{target}}(x)}{P_{\\text{source}}(x)}, \\quad \\mathbb{E}_{\\text{target}}[\\ell(f(x), y)] = \\mathbb{E}_{\\text{source}}\\bigl[w(x) \\cdot \\ell(f(x), y)\\bigr]$$

**口述捷径**："三种 shift：$P(x)$ covariate、$P(y \\mid x)$ concept、$P(y)$ label。Covariate -> 用 $P_\\text{target} / P_\\text{source}$ 重加权。Concept -> 重标注重训。Label -> 重校准。$P(x)$ 漂移是 covariate shift 的**必要**条件，但**不充分**；永远要回头查标签准确率。"

## 5. 按特征与按 Segment 告警

聚合漂移分数是经典**假阴性陷阱**。500 个特征的模型可能有 5 个特征被打爆，而均值 PSI 看着还好。修法是**多维告警**。

告警轴清单：

- **Per feature**：一个特征一个 PSI / KS，按分数排序，告警 top-K。任何单个特征 PSI $> 0.25$ 都触发调查，即便模型级聚合很平静。

- **Per segment**：按设备、国家、用户 cohort、day-of-week 切。漂移常常集中在某个 segment（例如 iOS 17 放量只改了 iOS 用户的屏幕时间分布）。

- **Per time window**：在 1 日、7 日、30 日窗口上分别算 PSI。1 日快速尖峰通常是流水线 bug；30 日慢趋势才是真正的人口漂移。

- **Per feature family**：把相关特征（例如所有 engagement 计数器）聚类，这样一个流水线 bug 表现为一个 cluster 级告警，而不是 50 个嘈杂的特征级告警。

**多重检验修正**：500 个特征、$\\alpha = 0.05$，你每天期望 25 个假阳性。对日级 p 值做 **Benjamini-Hochberg FDR 控制**；或者需要严格 Bonferroni 时换 $\\alpha / K$。对 **effect-size gate**（例如 PSI $> 0.25$），FDR 无关紧要——阈值**本身**就是多重检验控制。

Benjamini-Hochberg step-up，排序后的 p 值 $p_{(1)} \\le \\ldots \\le p_{(K)}$：

$$\\mathrm{FDR}_{\\text{BH}}\\!: \\text{ reject } H_{(k)} \\text{ if } p_{(k)} \\le \\frac{k}{K} \\cdot \\alpha$$

告警疲劳的对抗措施：

- **分级严重度**：只在 critical（PSI $> 0.25$ + segment 相关 + SHAP 重要性高）才 page。其他的进 dashboard，不进 pager。

- **抑制窗口**：一个特征已在告警，则 24 小时内抑制重复，避免 slack 刷屏。

- **自动归因**：某个特征的漂移如果能用上游流水线配置变更解释，自动把告警链到 deploy 时间线（Grafana annotation），让 on-call 一眼看到因果。

**口述捷径**："永远**不要只信一个聚合漂移数字**。按**每特征、每 segment、每时间窗口**告警。对日级 p 值做 FDR 修正，或者用 effect-size gate 像 PSI $> 0.25$。只对高重要性特征 page，其他一律进 dashboard。"

## 6. Drift Metrics at a Glance

按特征类型、对称性需求、问题本身来选指标。

**Feature drift metrics comparison**

| Metric | Feature type | Symmetric? | Bounded? | Thresholds | When to use |
| --- | --- | --- | --- | --- | --- |
| PSI | Binned (cat or numeric) | Yes (de facto) | No (但有限) | 0.1 / 0.25 | 每日单特征 dashboard |
| KL | Binned | No | No | 场景相关 | 参考 vs 当前有自然方向时 |
| JS | Binned | Yes | Yes ($\\le \\ln 2$) | ~0.05 告警、~0.1 严重 | 对称告警、embedding |
| KS | Continuous | Yes | Yes ($\\le 1$) | $D > 0.05$ 或 $p < \\alpha$ | 连续特征不分桶 |
| MMD | Any (kernel) | Yes | Yes | 场景相关 | 多变量 / embedding |
| Domain classifier AUC | Any | Yes | Yes ($\\le 1$) | AUC $> 0.6$ | 高维 covariate shift |


## 7. Three Shifts and Their Fixes

修法取决于**哪个分布动了**。错判 shift 类型是最常见的生产失败原因。

**Three drift types vs remediation**

| Shift | What moves | What stays | Fix | Relabel? |
| --- | --- | --- | --- | --- |
| Covariate | $P(x)$ | $P(y \\mid x)$ | 重要性重加权 $w(x) = P_\\text{target} / P_\\text{source}$ | No |
| Concept | $P(y \\mid x)$ | $P(x)$ 可能动也可能不动 | 用新鲜标签重训 | Yes |
| Label / Prior | $P(y)$ | $P(x \\mid y)$ | 重校准（Saerens EM / BBSE） | No |


### 2-Minute Oral Self-Check

- [ ] PSI = $\\sum (a - e) \\cdot \\ln(a / e)$，$K$ 桶求和
- [ ] PSI 阈值：0.1 告警、0.25 严重（信贷评分起源）
- [ ] 等频分桶**钉死在参考期**；$\\varepsilon$-clip 零桶
- [ ] KL 非对称、无界；JS 对称、界 $\\ln 2$
- [ ] $\\sqrt{\\text{JS}}$ 是**正宗度量**（三角不等式成立）
- [ ] KS = $\\sup |F_1 - F_2|$，非参、无分桶、尾部弱
- [ ] KS 临界 $\\approx 1.36 \\cdot \\sqrt{(n_1 + n_2) / (n_1 n_2)}$，$\\alpha = 0.05$
- [ ] Covariate shift = $P(x)$ 动、$P(y \\mid x)$ 稳 -> 重加权
- [ ] Concept drift = $P(y \\mid x)$ 动 -> 重标注 + 重训
- [ ] Label shift = $P(y)$ 动、$P(x \\mid y)$ 稳 -> 重校准
- [ ] 按**特征 / segment / 时间窗口**告警——不能只看聚合
- [ ] 日级 p 值做 FDR 修正**或**用 effect-size gate 像 PSI $> 0.25$
"""


# -------------------------------------------------------------------------
# Doc 69 -- Train-Serve Skew / Leakage / Temporal Split Drill
# -------------------------------------------------------------------------
DOC_69 = """<!-- Generated by StudyNoteBuilder -->
""" + SENTINEL + """

# Train-Serve Skew Drill -- Target Encoding Leakage, Time Split, Feature Store Parity, Future-Only Aggregates

## Prerequisites

- K-fold 交叉验证与 out-of-fold 预测概念
- 高基数类别的 target encoding / mean encoding
- 特征存储基础：离线训练 store vs 在线服务 store
- 排序评估：NDCG、时序 holdout、rolling-origin CV

## Key Terms

- **OOF (Out-of-fold，折外)**：第 $k$ 折的预测 / 编码仅用其他 $K - 1$ 折计算
- **CTR (Click-through rate，点击率)**：点击除以曝光；排序标签的标准聚合
- **AS-OF (As-of-time join，时点连接)**：返回给定事件时刻**之前或等于**该时刻的特征值，**绝不返回之后的值**
- **TTL (Time-to-live，存活时间)**：缓存 / 特征值的新鲜度窗口；不匹配会导致服务时的陈旧 skew
- **PIT (Point-in-time correctness，时点正确性)**：训练特征**仅**反映事件时间戳可见的信息，不含之后的任何数据

## 0. Why Train-Serve Skew Matters (The Framing)

训练-服务 skew 是模型**训练时看到的**与**推理时看到的**之间的结构性差。与 drift（随时间逐步出现）不同，skew 是**第一天就存在**的结构性缺陷——离线 NDCG 是骗你的。你会看到 +0.5 到 +2.0 点的幻象离线涨幅，上线后消失。

四个正交来源，各有不同修法：

- 特征数据泄露（target encoding、未来聚合）-> 用**时点正确性**与**out-of-fold 编码**修

- 切分策略错（在时序领域做随机切分）-> 用**时间切分 / walk-forward CV**修

- 特征存储 skew（离线-在线实现差异）-> 用**单一特征定义 spec + 共享服务代码 + 服务时记录的特征 join 回训练**修

- 标签构造 skew（标签用未来信息构造）-> 用严格 **AS-OF** 截止与显式 **label-time 戳**修

**口述捷径**："Skew 住在**切分、特征、存储、标签**四处。时序问题做随机切分，NDCG 离线上 2 点、线上掉 1 点。修法永远是：训练行看到的一切都必须能从**严格**事件时间之前的数据在推理时复现。"

## 1. Target Encoding Leakage + Out-of-Fold Fix

Target encoding 把高基数类别（user_id、item_id、creator_id、邮编）替换成**在该类别条件下的标签均值**。它是**表格排序最强**的一招，也是最常见的**泄露源**。

朴素 target encoding（类别 $c$）——对所有训练行（类别 $= c$）的标签求均值：

$$\\hat{y}_{\\text{naive}}(c) = \\frac{1}{|D_c|} \\sum_{i \\in D_c} y_i$$

泄露点：只出现一行的用户，编码后的特征**就是标签本身**。即使是出现多行的用户，当前行**自己的标签**也参与了当前行特征的计算，模型学到的是一个**服务时无法复现**的捷径。离线 AUC 好看，线上和 baseline 一样。

正确做法：K-fold **OOF** target encoding。对每折 $k$，类别均值**只用其他 $K - 1$ 折**算，再把这些均值分配给第 $k$ 折的行作为编码：

OOF 编码：第 $k$ 折某行的编码**只用其他折**的数据，**绝不用自己折**：

$$\\hat{y}_{\\text{OOF}}(c, \\text{row } i \\in \\text{fold } k) = \\frac{1}{|D_c \\setminus \\text{fold}_k|} \\sum_{j \\in D_c \\setminus \\text{fold}_k} y_j$$

**稀有类别方差问题**：类别只有 3 行训练数据时，OOF 均值方差巨大。向全局均值做**收缩**（贝叶斯 / Laplace 平滑），先验权重 $m$：

收缩估计：类别内 $n_c$ 行，先验权重 $m$（典型 10-100），未见 / 稀有类别退到全局均值：

$$\\hat{y}_{\\text{smooth}}(c) = \\frac{n_c \\cdot \\bar{y}_c + m \\cdot \\bar{y}_{\\text{global}}}{n_c + m}$$

**服务时**：使用在**全量训练集**上计算的编码（推理不需要分折），未见类别回退到全局均值。这与模型预期一致——$n_c$ 较大时 OOF 训练值与全量服务值在统计上接近；$n_c$ 较小时收缩让两者靠近。

基础修法之外的坑：

- **时间泄露叠加 CV 泄露**：即使做了 OOF，如果折**跨时间随机**，编码仍可能用**未来**行编码**过去**行。要把 OOF 套进时间切分里（外层时序切分、内层每折 OOF）。

- **多标签 target encoding**：排序任务上用 $y$ 编码，即使做了 OOF，只要分折**不感知 group**，标签仍会泄进特征。按 **query / session** 做 GroupKFold，让同 query 的所有行落在同一折。

- **Leave-one-out encoding** 是 OOF 极端化（$K = N$）。方差高、过拟合严重；偏好 $K = 5$ 或 $K = 10$ 加收缩。

**口述捷径**："Target encoding 通过**自己的那一行**泄露。修法是 K-fold OOF：第 $k$ 折只用其他折编码。再加先验收缩 $(n_c \\bar{y}_c + m \\bar{y}_\\text{global}) / (n_c + m)$ 处理稀有类别。按 query 做 **group-by-query fold**，否则跨 query 也泄。服务时用全量编码 + 全局均值兜底。"

## 2. Why Ranking MUST Use Time-Based Split

排序是**时序领域**：模型用**昨天的交互**训练，部署去预测**明天**。随机 80/20 切分打乱了时间，让模型通过三个机制"偷看未来"：

- **流行度泄露**：明天会火的物品在明天的行里就会有曝光。随机切分让模型学到"这个 item_id = 高相关"，但推理时这个趋势还没发生——**不可复现**。

- **用户历史重叠**：用户 session 级特征若按 session 内所有交互构造，就包含了**被打分那一行之后**发生的交互。随机切分把这掩盖掉；时间切分立刻暴露。

- **Concept drift 被吸进训练**：模型拟合的分布**同时**包含明天的世界。离线 NDCG $=$ 明天的 NDCG；在线 NDCG $=$ 后天的 NDCG，两者的**差就是漂移**。

**正确切分**：用 cutoff 时间戳 $T$。所有 $t < T$ 的行训练，所有 $T \\le t < T + H$ 的行 holdout。$T$ 在窗口里滚动前进（walk-forward / rolling origin CV）。离线数字通常会**比随机切分差**——这是 feature 不是 bug。它逼模型架构师正视**真实**泛化任务。

Walk-forward 评估：在 cutoff $T$ 之前的数据上训练，在下一个 $H$ 长度窗口内打分 holdout：

$$\\mathrm{Offline\\_NDCG}(T) = \\mathrm{NDCG}\\bigl(\\{(x_i, y_i) : T \\le t_i < T + H\\}\\bigr), \\quad \\text{train on } \\{t_i < T\\}$$

为什么"**用户级**"随机切分对排序仍然**错**：即使训练与测试的用户不相交，物品、query、季节模式依然在时间上重叠。你仍会得到流行度与趋势泄露。用户切分解决**冷启动用户**评估，而**不是时序 skew**。

**校准后果**：在随机切分 holdout 上拟合的温度 / Platt / isotonic 校准参数**过于激进**，因为 holdout 分布与训练同分布。**在时序 holdout 上重拟校准**，否则上线一周内会漂移。

排序特有的额外坑：

- **Query 级切分在 session 边界**：绝不把单 session 跨训练 / holdout 切分。session 内曝光共享的上下文特征会**反向泄露**。

- **负采样时间线**：two-tower / 召回用的负样本若从**明天的曝光日志**里采，就暴露了明天的库存构成。要严格从**过去**那段日志采负样。

- **标签延迟**：转化 / 购买标签可能在曝光后几天才落地。"新鲜"的时间切分要么等标签成熟，要么用**明确标注**的短周期代理标签。

**口述捷径**："时序领域做随机切分泄流行度、session 上下文、drift。永远 walk-forward：$t < T$ 训练，$[T, T + H)$ 评估。用户切分**不是替代品**——它修冷启动而非时间。校准一定在**时序 holdout** 上做，否则温度一周内就在线上漂了。"

## 3. Feature Store Parity -- 三类 Skew

Feature store 坐在原始日志与训练 + 服务之间。每个在线特征值都必须能从离线查询**以匹配的时点语义**复现出来。三类 subtle-but-deadly 的 skew 类型：

**(a) 时间戳 skew**：训练用**事件时**（曝光时间戳）的特征值；服务用**"现在"**（query 到达时间）的值。若特征是滚动 24 小时 **CTR**、且事件日志摄入延迟 10 分钟，服务值会**滞后于**从成熟日志算出的离线值。

- 修法：在**服务时刻**记录特征值，连同 request id 存起来，按 request id join 回训练。训练行用**字面上的服务值**，消除任何离线重算的 skew 可能。叫 "feature logging" 或 "log-and-wait"。

**(b) 空值语义 skew**：离线查询对缺失值返回 NULL；在线服务返回哨兵（$-1$、$0$、`'UNKNOWN'`）。模型把它们当成**不同类别**，标签空间一分为二——学到了线上不存在的伪信号。

- 修法：在**特征 spec** 里规范化空值处理。每个特征一个标准缺失值表示，由**离线 ETL 与在线服务共享**的库强制。集成测试：随机 1% 的请求双算离线与在线，断言相等（在浮点 $\\varepsilon$ 内）。

**(c) 填充 / 默认 skew**：特征稀疏时，离线流水线用均值回填，在线服务用零回填。embedding-of-embeddings 里的经典案例：冷启动用户的 embedding 离线用**平均用户 embedding**，在线用**零向量**。模型静默地把均值学成强信号（任何看起来像新用户的人都被给了"平均体验"）。

- 修法：填充值**本身就是特征定义**的一部分，不是流水线决策。把它连同 dtype 与 null-policy 一起登记在**特征 registry**。若填充有语义（例如"零 embedding 表示冷启动"），配一个显式的 `is_cold_start` 布尔特征，让模型能分辨。

还有一类值得为 Google / R1 记住：

**(d) 计算 skew**：离线用 pandas groupby float64，在线用 C++ 流式 sum float32 且求和顺序不同。大窗口下相对误差复合。用 100 万行的 parity 单测对每个特征比较离线与在线实现能抓到。

**验证配方**：仪表板按每个特征、每天画 $\\frac{\\lvert \\text{offline\\_value} - \\text{logged\\_serving\\_value} \\rvert}{\\max(\\varepsilon, \\lvert \\text{offline\\_value} \\rvert)}$ 的分布，p99 $> 10^{-3}$ 告警。这能统一捕获以上三类。

**口述捷径**："Feature store skew 有三味：**时间戳**（AS-OF 不一致）、**空值语义**（NULL vs 哨兵）、**填充值**（均值 vs 零）。修法是共享 spec、共享代码路径，以及**核武器选项**——记录服务值并 join 回训练，让离线与在线字面相等。"

## 4. Label Leakage via Future-Only Aggregates

聚合特征——"过去 7 天 item 的 CTR"、"用户平均 session 长度"、"这个创作者内容被 like 的次数"——是二阶泄露向量。聚合概念上是"过去"，但若 ETL 在**跨越事件时间戳**的窗口上计算，过去里就混进了**未来**。

**时点正确**的聚合：函数 $g$ 只看事件时间 $t_e$ **严格之前**的事件：

$$\\text{AS-OF aggregate at event time } t_e\\!: \\quad f(t_e) = g\\!\\left(\\{x_j : t_j < t_e\\}\\right)$$

面试里要能点名的三个子模式：

- **自己这一行被包进去**：聚合用了**所有**同 key 的行，包括当前行。"item $x$ 的总点击数"在曝光时算，却把当前曝光**之后**会产生的点击也算进去了。修法：用 $t < t_e$ 严格之前的行计算；**排除正在被打分的行**。

- **未来窗口渗漏**：7 天滚动聚合若**以事件时间为中心**或**包含**事件时间就错了。必须**严格后向**：$[t_e - 7\\text{d},\\ t_e)$。面试陷阱："一个以事件时间为中心的 7 天 CTR" 就是错的；必须是**滞后**窗口。

- **流水线 join 粒度错误**：训练流水线按**天**粒度 join 聚合，服务按**请求**粒度 join。按天 join 隐式把**当天结束时**的统计量用到**当天所有行**，包括 00:01 的那一行。任何当天结束之前的请求，在服务时看到的信息都比离线流水线承认的少。

**Label-time stamping**：每一行必须带 `label_time_ns` 字段。所有特征都定义为 `label_time_ns` **严格之前**数据的纯函数。简单回归测试：在同一天内**打乱** `label_time_ns`——模型性能不应比噪声退化得更多。若退化了，**有东西在偷用精确时间戳**。

Label 本身的泄露（与聚合泄露独立）：

- **未来 label**："用户在接下来 30 天内有没有购买"被当作 10 天前那次曝光的 label。训练看得到整个 30 天窗口；推理只看到今天为止。修法：label 定义在**所有**训练行都已**完全走完**的窗口上，**绝不**在仍未关闭的窗口上。

- **Label 当特征**：lag-1 label（"用户上一次曝光有没有点击"）没问题；lag-0（"用户对**这次**曝光有没有点击"）就**是 label 本身**——明显但**出乎意料地常见**，因为一次不小心的 left-join 就把当前行带进来了。

**口述捷径**："聚合特征在窗口**跨越事件时间**时泄露。规则：(1) **严格后向**窗口，(2) 排除当前行自身，(3) 按 request 粒度 join 而非天粒度，(4) 每行戳 `label_time_ns`，特征是 $t < \\text{label\\_time}$ 数据的纯函数。打乱时间戳的回归测试能抓到大多数这类泄露。"

## 5. One Real Production Gotcha (Candidate Story)

Etsy Search 上线一个 creator 级 target-encoded 特征（`creator_id ->` 曝光均 GMB）：离线 NDCG $+1.2$ 点、训练 AUC $+0.8$ 点。上线计划：1% 交错 A/B，后 ramp。

线上结果：新买家 GMB 持平，**回访买家 $-0.4\\%$ GMB**，长尾创作者曝光微降 $-1\\%$。经典"离线涨、线上跌"模式。

逐步倒查根因：

- **Step 1 -- 切分验证**：时间切分 walk-forward，正确。

- **Step 2 -- OOF 验证**：实现了 5 折 OOF 编码。**但是**：折按 `creator_id` **分层**（为了稀有创作者在各折间均衡）。问题——**同一个 query-session 的曝光被分到不同折**，于是第 $k$ 折一个曝光用的编码里掺进了**同 session 的兄弟曝光**对该 creator_id 的贡献。**session 级上下文通过编码泄露**。

- **Step 3 -- 平滑验证**：先验权重 $m = 20$，先验是全局均值。原则正确。**但**全局均值是在**全量训练集**（所有折合起来）上算的，把**一小撮 label 信息**重新塞进每折的编码里。（边际效应小但非零。）

- **Step 4 -- 服务 parity**：离线编码用 pandas groupby float64，在线服务用同一批值在 float32 kv store 里物化。无 parity 问题。

上线的修复：

- OOF 折改为 **GroupKFold by session_id**。平滑先验**每折单独**从其他折的全局均值计算（而不是总体）。

- 加服务时空值策略守门：未见 creator_id 退到**上次训练刷新时**的全局均值，而不是当日全局均值（否则会把当日趋势泄进冷启动 creator）。

- 回归测试：在**包含**和**不包含**当前行的两种编码数据集上各跑一次流水线；若 AUC 差 $> 0.1$ 点，CI 失败。

修复后结果：离线 NDCG 涨幅从 $+1.2$ 降到 $+0.4$，线上 GMB $+0.2\\%$（$n = 4$M sessions 下统计显著）。教训一句话："**$+1.2$ 离线涨幅通常一半是真、一半是泄露**——在宣布胜利之前，先去审编码流水线。"

面试里可复用的一般原则：

- 永远问"**折边界**在哪里"。那里通常就是泄露源。

- 在**每折编码里使用全局统计量**是二阶泄露。

- **打乱时间戳 + 当前行排除**测试是便宜的保险。

- 离线涨幅 $> 1$ 点是**红旗**，不是绿灯。按"证明这**不是**泄露"来审，直到审过。

## 6. Skew Taxonomy at a Glance

诊断时要**说出类型名字**——面试官会看你能不能区分这四个正交来源。

**Four sources of train-serve skew**

| Skew type | Symptom | Where it hides | Canonical fix |
| --- | --- | --- | --- |
| Feature leakage | 离线 AUC 涨，线上持平或跌 | Target encoding、未来聚合 | OOF 编码 + AS-OF join + `label_time_ns` 纪律 |
| Temporal split | Ramp 后线上下滑，校准漂移 | 时序领域的随机 80/20 切分 | Walk-forward / rolling-origin CV、时序校准 |
| Feature store | 同一输入离线 / 在线预测不同 | NULL 哨兵、填充默认、AS-OF 摄入滞后 | 共享特征 spec + 服务时记录 + parity 测试 |
| Label construction | 特征在 holdout 上"解释 label 太好" | Label 窗口未关闭、自己行被包进去 | 关闭窗口的 label、严格排除当前行 |


## 7. Feature Store Skew Flavors -- Side-by-Side

Feature store（第 3 节）值得单独展开；每一味有不同的诊断签名。

**Feature store skew flavors**

| Flavor | Offline pipeline | Online pipeline | Diagnostic signal | Remediation |
| --- | --- | --- | --- | --- |
| Timestamp / AS-OF | 从成熟日志取事件时的值 | 从新鲜日志取"现在"的值 | 随摄入延迟漂移的系统性偏移 | 记录服务时值，按 request_id join |
| Null semantics | 保留 NULL | 强制成 $-1$ 或 `'UNKNOWN'` | 训练集里空值率 $\\ne$ 服务时哨兵率 | 特征 spec + registry 里共享 null-policy |
| Fill / default | 均值填充或最后值延续 | 零填充或空 embedding | 冷启动预测系统性偏斜 | Registry 里规范化填充 + `is_cold_start` 特征 |
| Computation / float 精度 | pandas float64 groupby | C++ 流式 float32 sum | p99 \\|offline $-$ online\\| 相对误差随窗口增长 | 每特征 parity 单测，p99 $> 10^{-3}$ 告警 |


**Q: 面试官说："你提到 target encoding，怎么避免泄露？"**

两层。第一层，K-fold out-of-fold：每折 $k$ 只用其他 $K - 1$ 折算类别均值。第二层，先验权重 $m$ 向全局均值收缩，稀有类别（$n_c < m$）回归到先验。关键坑：(a) **GroupKFold by query / session**——随机分折会切开兄弟曝光，通过编码泄露；(b) 全局均值先验**按折**从其他折计算，不要用全量训练集，否则会把一小片 label 漏回去；(c) 服务时用**全量**编码加全局均值兜底处理未见类别——这匹配 OOF 折在统计上近似的行为。

**Q: 面试官说："为什么随机 80/20 切分给出的离线 NDCG 比时间切分高？"**

三个原因。(1) **流行度泄露**：holdout 周里上升的物品在前 80% 训练里有样本，模型学到它们的 item_id 是高相关——服务时明天的趋势还没发生。(2) **Session 渗漏**：session 级上下文特征（`session_length`、`items_seen_so_far`）在 session 被切开时包含了打分行**之后**的事件。(3) **Concept drift 吸收**：模型拟合的分布**同时**包含过去与未来世界状态；在线推理只有过去。随机切分 NDCG 与时序切分 NDCG 的差，**就是**模型在从未来**偷借**的 drift 预算。

**Q: 面试官说："讲一个离线看起来不错、线上挂掉的线上特征。"**

Etsy creator 级 target encoding，离线 NDCG $+1.2$，线上 GMB 持平到负。根因是 OOF 折的 session 渗漏——同一次搜索 session 的曝光被切到不同折，所以第 $k$ 折里某个 creator_id 的编码实际上被 session 内的兄弟曝光（来自第 $j$ 折）告知了。再加上全局均值先验用全量数据算。修法：**GroupKFold by session_id**、**每折全局均值**、以及 CI 里的**当前行排除回归测试**。修后线上 $+0.2\\%$ GMB。教训：**$> 1$ 点离线涨幅是去审编码流水线的信号，不是庆祝的信号**。

### 2-Minute Oral Self-Check

- [ ] Target encoding 必须 K-fold OOF：第 $k$ 折用其他 $K - 1$ 折编码
- [ ] 收缩平滑：$(n_c \\bar{y}_c + m \\bar{y}_\\text{global}) / (n_c + m)$
- [ ] GroupKFold by query / session，否则兄弟曝光互相泄
- [ ] 每折全局均值（而非全量）以避免二阶泄露
- [ ] 排序要**时间切分 / walk-forward**，绝不随机 80/20
- [ ] 用户切分修冷启动用户，**不**修时序 skew
- [ ] **在时序 holdout 上校准**，避免温度上线就漂
- [ ] Feature store skew $=$ 时间戳 + 空值语义 + 填充 + 浮点精度
- [ ] 记录**服务时**特征值并按 request_id join（核武器选项）
- [ ] 聚合特征**严格后向**，排除当前行
- [ ] 每行戳 `label_time_ns`；特征 $=\\ t < \\text{label\\_time}$ 数据的纯函数
- [ ] 打乱时间戳的回归测试能抓住大多数隐蔽时间泄露
- [ ] 离线 $+1$ NDCG 点是**红旗**，不是绿灯
"""


DOCS: dict[int, tuple[str, str]] = {
    65: (
        "Multi-Objective Ranking: DPP / MMR + Etsy Diversity Playbook (Google R1 Prep)",
        DOC_65,
    ),
    68: (
        "Feature Drift Drill: PSI / KL / JS / KS + Concept vs Covariate Shift (Google R1 Prep)",
        DOC_68,
    ),
    69: (
        "Train-Serve Skew / Leakage / Temporal Split Drill: Target Encoding, Feature Store Parity, Future-Only Aggregates (Google R1 Prep)",
        DOC_69,
    ),
}


def cjk_ratio(text: str) -> float:
    """Return CJK / (CJK + Latin letters) ratio for the given text."""
    cjk = sum(1 for c in text if "\u4e00" <= c <= "\u9fff")
    latin = sum(1 for c in text if c.isalpha() and ord(c) < 128)
    total = cjk + latin
    return cjk / total if total else 0.0


def main() -> int:
    """Apply the batch-3 Chinese translations idempotently."""
    conn = sqlite3.connect(str(DB_PATH))
    try:
        updated = 0
        unchanged = 0
        for did, (expected_title, new_content) in DOCS.items():
            row = conn.execute(
                "SELECT title, content FROM company_documents WHERE id = ?",
                (did,),
            ).fetchone()
            if row is None:
                print(f"[ERROR] doc {did} not found")
                continue
            cur_title, cur_content = row
            if SENTINEL in cur_content:
                print(f"[UNCHANGED] doc {did} ({cur_title}) -- sentinel present")
                unchanged += 1
                continue
            cur = conn.execute(
                "UPDATE company_documents SET content = ? WHERE id = ?",
                (new_content, did),
            )
            conn.commit()
            ratio = cjk_ratio(new_content)
            print(
                f"[UPDATE] doc {did} rows={cur.rowcount} new_len={len(new_content)} "
                f"cjk_ratio={ratio:.1%}"
            )
            updated += 1
        print(f"Summary: updated={updated}, unchanged={unchanged}")
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
