"""StudyNoteBuilder: typed builder for study note content.

Provides FormulaBlock for guaranteed double-dollar math wrapping,
auto-bolding of registered terms, and fail-fast single-dollar detection.
"""

from __future__ import annotations

import re
import sqlite3
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import ClassVar

DB_PATH = Path(__file__).resolve().parent.parent / "data" / "mle_prep.db"

# Regex for orphan single-dollar signs (not part of $$).
# Matches $...$ where the content is NOT preceded/followed by another $.
_SINGLE_DOLLAR_RE = re.compile(
    r"(?<!\$)\$(?!\$)"  # a single $ not adjacent to another $
)


@dataclass
class FormulaBlock:
    """A typed math formula that guarantees double-dollar wrapping."""

    latex: str
    explanation: str = ""

    def build(self) -> str:
        """Render as markdown with double-dollar delimiters."""
        parts: list[str] = []
        if self.explanation:
            parts.append(self.explanation)
            parts.append("")
        parts.append(f"$${self.latex}$$")
        parts.append("")
        return "\n".join(parts)


@dataclass
class StudyNoteBuilder:
    """Builder for structured study note content.

    Usage::

        builder = StudyNoteBuilder()
        builder.set_title("Diffusion Models Deep-Dive")
        builder.add_prerequisites(["Basic probability", "Neural networks"])
        builder.add_term("DDPM", "Denoising Diffusion Probabilistic Model",
                         "Generates data by learning to reverse a noise process")
        builder.add_section("Forward Process", [
            "The forward process adds Gaussian noise over T steps.",
            FormulaBlock(latex=r"q(x_t|x_{t-1}) = ...", explanation="Each step adds noise:"),
        ])
        content = builder.build()
    """

    _title: str = ""
    _prerequisites: list[str] = field(default_factory=list)
    _terms: list[tuple[str, str, str]] = field(default_factory=list)
    _sections: list[tuple[str, list[str | FormulaBlock]]] = field(
        default_factory=list
    )
    _raw_blocks: list[str] = field(default_factory=list)

    # Class-level constants
    HEADER_COMMENT: ClassVar[str] = "<!-- Generated by StudyNoteBuilder -->"

    def set_title(self, title: str) -> StudyNoteBuilder:
        """Set the document title."""
        self._title = title
        return self

    def add_prerequisites(self, items: list[str]) -> StudyNoteBuilder:
        """Add prerequisite knowledge items."""
        self._prerequisites.extend(items)
        return self

    def add_term(
        self, abbrev: str, full_name: str, description: str = ""
    ) -> StudyNoteBuilder:
        """Register a domain term for auto-bolding and glossary."""
        self._terms.append((abbrev, full_name, description))
        return self

    def add_section(
        self, heading: str, blocks: list[str | FormulaBlock]
    ) -> StudyNoteBuilder:
        """Add a content section with prose strings and FormulaBlocks."""
        self._sections.append((heading, blocks))
        return self

    def add_diagram_html(self, html: str) -> StudyNoteBuilder:
        """Add a raw HTML diagram block."""
        self._raw_blocks.append(("diagram", html))  # type: ignore[arg-type]
        # Store as section with raw HTML
        self._sections.append(("__diagram__", [html]))
        return self

    def add_comparison_table(
        self,
        headers: list[str],
        rows: list[list[str]],
        title: str = "",
    ) -> StudyNoteBuilder:
        """Add a styled comparison table."""
        lines: list[str] = []
        if title:
            lines.append(f"**{title}**")
            lines.append("")
        # Build markdown table
        lines.append("| " + " | ".join(headers) + " |")
        lines.append("| " + " | ".join("---" for _ in headers) + " |")
        for row in rows:
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")
        self._sections.append(("__table__", ["\n".join(lines)]))
        return self

    def add_interview_qa(
        self, question: str, answer: str
    ) -> StudyNoteBuilder:
        """Add an interview Q&A pair."""
        block = f"**Q: {question}**\n\n{answer}"
        self._sections.append(("__qa__", [block]))
        return self

    def add_checklist(
        self, title: str, items: list[str]
    ) -> StudyNoteBuilder:
        """Add a self-check checklist."""
        lines = [f"### {title}", ""]
        for item in items:
            lines.append(f"- [ ] {item}")
        lines.append("")
        self._sections.append(("__checklist__", ["\n".join(lines)]))
        return self

    def build(self) -> str:
        """Build the final markdown content.

        Pipeline:
        1. Insert HTML comment header
        2. Generate title
        3. Generate Prerequisites section
        4. Generate Term Registry
        5. Render all sections (prose + FormulaBlocks)
        6. Auto-bold first occurrence of each registered term in prose
        7. FAIL-FAST: scan for orphan single-dollar signs

        Returns:
            The complete markdown string.

        Raises:
            ValueError: If any prose block contains orphan single-dollar signs.
        """
        parts: list[str] = []

        # 1. Header comment
        parts.append(self.HEADER_COMMENT)
        parts.append("")

        # 2. Title
        if self._title:
            parts.append(f"# {self._title}")
            parts.append("")

        # 3. Prerequisites
        if self._prerequisites:
            parts.append("## Prerequisites")
            parts.append("")
            for prereq in self._prerequisites:
                parts.append(f"- {prereq}")
            parts.append("")

        # 4. Term registry / glossary
        if self._terms:
            parts.append("## Key Terms")
            parts.append("")
            for abbrev, full_name, desc in self._terms:
                line = f"- **{abbrev}** ({full_name})"
                if desc:
                    line += f": {desc}"
                parts.append(line)
            parts.append("")

        # 5. Sections
        for heading, blocks in self._sections:
            # Special internal headings for diagram/table/qa/checklist
            if heading.startswith("__"):
                for block in blocks:
                    if isinstance(block, FormulaBlock):
                        parts.append(block.build())
                    else:
                        parts.append(block)
                        parts.append("")
            else:
                parts.append(f"## {heading}")
                parts.append("")
                for idx, block in enumerate(blocks):
                    if isinstance(block, FormulaBlock):
                        parts.append(block.build())
                    else:
                        parts.append(block)
                        # Don't add blank line between consecutive table rows
                        is_table_row = isinstance(block, str) and block.strip().startswith("|")
                        next_block = blocks[idx + 1] if idx + 1 < len(blocks) else None
                        next_is_table = isinstance(next_block, str) and next_block.strip().startswith("|")
                        if not (is_table_row and next_is_table):
                            parts.append("")

        content = "\n".join(parts)

        # 6. Auto-bold first occurrence of registered terms in prose
        content = self._auto_bold_terms(content)

        # 7. Fail-fast: scan for orphan single-dollar
        self._check_single_dollars(content)

        return content

    def _auto_bold_terms(self, content: str) -> str:
        """Bold the first occurrence of each registered term in prose.

        Only bolds terms that appear as whole words outside of:
        - Code blocks (``` ... ```)
        - Math blocks ($$ ... $$ and $ ... $)
        - Already bolded text (** ... **)
        - The Key Terms section itself
        """
        # Split content into protected (math/code) and unprotected (prose) spans
        # so auto-bolding only touches prose. A literal "MSE" inside
        # \mathrm{MSE} must not become \mathrm{**MSE**}.
        protect_re = re.compile(
            r"(```[\s\S]*?```"      # fenced code block
            r"|`[^`\n]*`"           # inline code
            r"|\$\$[\s\S]*?\$\$"    # display math
            r"|\$[^\$\n]+?\$)"      # inline math
        )

        key_terms_marker = "## Key Terms"

        def bold_once_in_prose(text: str, pattern: re.Pattern) -> tuple[str, bool]:
            """Apply pattern.sub on prose spans only; stop after first hit."""
            done = False
            out_parts: list[str] = []
            pos = 0
            for m in protect_re.finditer(text):
                if not done:
                    prose = text[pos:m.start()]
                    new_prose, n = pattern.subn(r"**\1**", prose, count=1)
                    out_parts.append(new_prose)
                    if n:
                        done = True
                else:
                    out_parts.append(text[pos:m.start()])
                out_parts.append(m.group(0))
                pos = m.end()
            tail = text[pos:]
            if not done:
                tail, n = pattern.subn(r"**\1**", tail, count=1)
                if n:
                    done = True
            out_parts.append(tail)
            return "".join(out_parts), done

        for abbrev, _full_name, _ in self._terms:
            pattern = re.compile(
                r"(?<!\*\*)"
                r"\b(" + re.escape(abbrev) + r")\b"
                r"(?!\*\*)",
                re.IGNORECASE,
            )
            if key_terms_marker in content:
                before_terms = content[: content.index(key_terms_marker)]
                terms_section_start = content.index(key_terms_marker)
                rest = content[terms_section_start:]
                next_heading = re.search(r"\n## (?!Key Terms)", rest)
                if next_heading:
                    terms_end = terms_section_start + next_heading.start()
                    terms_section = content[terms_section_start:terms_end]
                    after_terms = content[terms_end:]
                else:
                    terms_section = rest
                    after_terms = ""

                new_after, _ = bold_once_in_prose(after_terms, pattern)
                content = before_terms + terms_section + new_after
            else:
                content, _ = bold_once_in_prose(content, pattern)

        return content

    def _check_single_dollars(self, content: str) -> None:
        """Raise ValueError if orphan single-dollar signs are found.

        Scans all prose blocks (skips code blocks, double-dollar blocks,
        and paired inline math ``$...$``).
        """
        # Remove code blocks
        no_code = re.sub(r"```[\s\S]*?```", "", content)
        # Remove double-dollar blocks
        no_math = re.sub(r"\$\$[\s\S]*?\$\$", "", no_code)
        # Remove inline code
        no_inline_code = re.sub(r"`[^`]+`", "", no_math)
        # Remove paired inline math ($...$) -- non-greedy, same-line only
        no_inline_math = re.sub(r"\$[^$\n]+\$", "", no_inline_code)

        matches = list(_SINGLE_DOLLAR_RE.finditer(no_inline_math))
        if matches:
            # Find context around first match
            pos = matches[0].start()
            start = max(0, pos - 30)
            end = min(len(no_inline_math), pos + 30)
            context = no_inline_math[start:end].replace("\n", "\\n")
            raise ValueError(
                f"Orphan single-dollar sign found ({len(matches)} total). "
                f"Use FormulaBlock for math or $$ for display math. "
                f"Context: ...{context}..."
            )

    @classmethod
    def validate(cls, content: str) -> list[str]:
        """Validate an existing document for common issues.

        Returns:
            List of warning messages (empty if clean).
        """
        warnings: list[str] = []

        # Check for orphan single-dollars
        no_code = re.sub(r"```[\s\S]*?```", "", content)
        no_math = re.sub(r"\$\$[\s\S]*?\$\$", "", no_code)
        no_inline_code = re.sub(r"`[^`]+`", "", no_math)
        # Remove paired inline math ($...$)
        no_inline_math = re.sub(r"\$[^$\n]+\$", "", no_inline_code)
        singles = list(_SINGLE_DOLLAR_RE.finditer(no_inline_math))
        if singles:
            warnings.append(
                f"Found {len(singles)} orphan single-dollar sign(s). "
                "Use $$ for display math."
            )

        # Check for missing header comment
        if cls.HEADER_COMMENT not in content:
            warnings.append("Missing StudyNoteBuilder header comment.")

        return warnings

    def save_to_db(
        self,
        company_id: int,
        doc_title: str,
        *,
        db_path: Path | None = None,
    ) -> int:
        """Build content and save to company_documents table.

        Args:
            company_id: The company ID in the database.
            doc_title: Document title (used for idempotency check).
            db_path: Override database path (defaults to data/mle_prep.db).

        Returns:
            The document ID.

        Raises:
            SystemExit: If database or company not found.
        """
        path = db_path or DB_PATH
        if not path.exists():
            print(f"[FAIL] Database not found: {path}")
            sys.exit(1)

        content = self.build()
        conn = sqlite3.connect(str(path))

        try:
            # Check company exists
            row = conn.execute(
                "SELECT id FROM companies WHERE id = ?", (company_id,)
            ).fetchone()
            if not row:
                print(f"[FAIL] Company id={company_id} not found in DB")
                sys.exit(1)

            # Idempotent: skip if exists
            existing = conn.execute(
                "SELECT id FROM company_documents WHERE company_id = ? AND title = ?",
                (company_id, doc_title),
            ).fetchone()
            if existing:
                print(
                    f"[SKIP] Document already exists (id={existing[0]}): {doc_title}"
                )
                return existing[0]

            # Insert
            conn.execute(
                "INSERT INTO company_documents (company_id, title, content, source_type) "
                "VALUES (?, ?, ?, ?)",
                (company_id, doc_title, content, "manual"),
            )
            conn.commit()

            # Verify
            doc = conn.execute(
                "SELECT id, length(content) FROM company_documents "
                "WHERE company_id = ? AND title = ?",
                (company_id, doc_title),
            ).fetchone()
            print(
                f"[DONE] Inserted document id={doc[0]}, "
                f"title='{doc_title}', content_length={doc[1]} chars"
            )
            return doc[0]
        finally:
            conn.close()
